// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stripe_webhooks.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createStripeWebhook = `-- name: CreateStripeWebhook :one
INSERT INTO stripe.stripe_webhooks (
    stripe_id, url, secret, events, connect, config_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, stripe_id, url, secret, events, connect, config_id, created_at, updated_at
`

type CreateStripeWebhookParams struct {
	StripeID string     `json:"stripe_id"`
	Url      string     `json:"url"`
	Secret   string     `json:"secret"`
	Events   []string   `json:"events"`
	Connect  bool       `json:"connect"`
	ConfigID *uuid.UUID `json:"config_id"`
}

type CreateStripeWebhookRow struct {
	ID        uuid.UUID  `json:"id"`
	StripeID  string     `json:"stripe_id"`
	Url       string     `json:"url"`
	Secret    string     `json:"secret"`
	Events    []string   `json:"events"`
	Connect   bool       `json:"connect"`
	ConfigID  *uuid.UUID `json:"config_id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

func (q *Queries) CreateStripeWebhook(ctx context.Context, arg CreateStripeWebhookParams) (CreateStripeWebhookRow, error) {
	row := q.db.QueryRow(ctx, createStripeWebhook,
		arg.StripeID,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.Connect,
		arg.ConfigID,
	)
	var i CreateStripeWebhookRow
	err := row.Scan(
		&i.ID,
		&i.StripeID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Connect,
		&i.ConfigID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStripeWebhookByStripeID = `-- name: DeleteStripeWebhookByStripeID :exec
DELETE FROM stripe.stripe_webhooks
WHERE stripe_id = $1
`

func (q *Queries) DeleteStripeWebhookByStripeID(ctx context.Context, stripeID string) error {
	_, err := q.db.Exec(ctx, deleteStripeWebhookByStripeID, stripeID)
	return err
}

const getStripeWebhookByStripeID = `-- name: GetStripeWebhookByStripeID :one
SELECT id, stripe_id, url, secret, events, connect, config_id, created_at, updated_at
FROM stripe.stripe_webhooks
WHERE stripe_id = $1
`

type GetStripeWebhookByStripeIDRow struct {
	ID        uuid.UUID  `json:"id"`
	StripeID  string     `json:"stripe_id"`
	Url       string     `json:"url"`
	Secret    string     `json:"secret"`
	Events    []string   `json:"events"`
	Connect   bool       `json:"connect"`
	ConfigID  *uuid.UUID `json:"config_id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

func (q *Queries) GetStripeWebhookByStripeID(ctx context.Context, stripeID string) (GetStripeWebhookByStripeIDRow, error) {
	row := q.db.QueryRow(ctx, getStripeWebhookByStripeID, stripeID)
	var i GetStripeWebhookByStripeIDRow
	err := row.Scan(
		&i.ID,
		&i.StripeID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Connect,
		&i.ConfigID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStripeWebhooks = `-- name: ListStripeWebhooks :many
SELECT id, stripe_id, url, secret, events, connect, config_id, created_at, updated_at
FROM stripe.stripe_webhooks
ORDER BY created_at DESC
`

type ListStripeWebhooksRow struct {
	ID        uuid.UUID  `json:"id"`
	StripeID  string     `json:"stripe_id"`
	Url       string     `json:"url"`
	Secret    string     `json:"secret"`
	Events    []string   `json:"events"`
	Connect   bool       `json:"connect"`
	ConfigID  *uuid.UUID `json:"config_id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

func (q *Queries) ListStripeWebhooks(ctx context.Context) ([]ListStripeWebhooksRow, error) {
	rows, err := q.db.Query(ctx, listStripeWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStripeWebhooksRow
	for rows.Next() {
		var i ListStripeWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.StripeID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Connect,
			&i.ConfigID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStripeWebhooksByConfigID = `-- name: ListStripeWebhooksByConfigID :many
SELECT id, stripe_id, url, secret, events, connect, config_id, created_at, updated_at
FROM stripe.stripe_webhooks
WHERE config_id = $1
ORDER BY created_at DESC
`

type ListStripeWebhooksByConfigIDRow struct {
	ID        uuid.UUID  `json:"id"`
	StripeID  string     `json:"stripe_id"`
	Url       string     `json:"url"`
	Secret    string     `json:"secret"`
	Events    []string   `json:"events"`
	Connect   bool       `json:"connect"`
	ConfigID  *uuid.UUID `json:"config_id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

func (q *Queries) ListStripeWebhooksByConfigID(ctx context.Context, configID *uuid.UUID) ([]ListStripeWebhooksByConfigIDRow, error) {
	rows, err := q.db.Query(ctx, listStripeWebhooksByConfigID, configID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStripeWebhooksByConfigIDRow
	for rows.Next() {
		var i ListStripeWebhooksByConfigIDRow
		if err := rows.Scan(
			&i.ID,
			&i.StripeID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Connect,
			&i.ConfigID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStripeWebhook = `-- name: UpdateStripeWebhook :exec
UPDATE stripe.stripe_webhooks
SET url = $2,
    events = $3,
    secret = $4
WHERE stripe_id = $1
`

type UpdateStripeWebhookParams struct {
	StripeID string   `json:"stripe_id"`
	Url      string   `json:"url"`
	Events   []string `json:"events"`
	Secret   string   `json:"secret"`
}

func (q *Queries) UpdateStripeWebhook(ctx context.Context, arg UpdateStripeWebhookParams) error {
	_, err := q.db.Exec(ctx, updateStripeWebhook,
		arg.StripeID,
		arg.Url,
		arg.Events,
		arg.Secret,
	)
	return err
}
