GRANT USAGE ON SCHEMA public, auth, storage, permissions, stripe, email, migrations TO anon_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public, auth, storage, permissions, stripe, email, migrations TO anon_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT SELECT ON TABLES TO anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA storage GRANT SELECT ON TABLES TO anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA permissions GRANT SELECT ON TABLES TO anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA stripe GRANT SELECT ON TABLES TO anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA email GRANT SELECT ON TABLES TO anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA migrations GRANT SELECT ON TABLES TO anon_user;
