DO $$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'anon_user') THEN
        CREATE ROLE anon_user NOLOGIN NOBYPASSRLS;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'super_user') THEN
        CREATE ROLE super_user NOLOGIN BYPASSRLS;
    END IF;
END $$;

DO $$ BEGIN
    ALTER ROLE super_user BYPASSRLS;
EXCEPTION WHEN insufficient_privilege THEN
    RAISE NOTICE 'Skipping ALTER ROLE super_user BYPASSRLS';
END $$;

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

GRANT USAGE ON SCHEMA permissions, migrations, email TO super_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA permissions, migrations, email TO super_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA permissions, migrations, email TO super_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA permissions GRANT ALL ON TABLES TO super_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA migrations GRANT ALL ON TABLES TO super_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA email GRANT ALL ON TABLES TO super_user;

GRANT USAGE ON SCHEMA public TO anon_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO anon_user;

GRANT USAGE ON SCHEMA auth TO anon_user;
REVOKE SELECT ON ALL TABLES IN SCHEMA auth FROM anon_user;
GRANT SELECT ON auth.tenants TO anon_user;
GRANT SELECT ON auth.tenant_users TO anon_user;
GRANT SELECT ON auth.tenant_settings TO anon_user;
GRANT SELECT ON auth.tenant_invites TO anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth REVOKE SELECT ON TABLES FROM anon_user;

GRANT USAGE ON SCHEMA storage TO anon_user;
REVOKE SELECT ON ALL TABLES IN SCHEMA storage FROM anon_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON storage.objects TO anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA storage REVOKE SELECT ON TABLES FROM anon_user;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA permissions FROM anon_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA permissions FROM anon_user;
REVOKE USAGE ON SCHEMA permissions FROM anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA permissions REVOKE SELECT ON TABLES FROM anon_user;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA stripe FROM anon_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA stripe FROM anon_user;
REVOKE USAGE ON SCHEMA stripe FROM anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA stripe REVOKE SELECT ON TABLES FROM anon_user;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA email FROM anon_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA email FROM anon_user;
REVOKE USAGE ON SCHEMA email FROM anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA email REVOKE SELECT ON TABLES FROM anon_user;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA migrations FROM anon_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA migrations FROM anon_user;
REVOKE USAGE ON SCHEMA migrations FROM anon_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA migrations REVOKE SELECT ON TABLES FROM anon_user;
