import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";
import { clearRegistry, getRegistry } from "./policies";
import { generateRlsDiffFromMigrations } from "./rls-policies";

// Register tsx so we can import .ts policy files in Node.js
import "tsx";

export interface GenerateOptions {
  projectRoot: string;
  dbUrl?: string;
  migrationName: string;
  // Create an empty migration to fill in by hand (data backfills, manual DDL)
  // instead of diffing the Prisma schema.
  blank?: boolean;
}

// Throwaway database prisma replays the migration history into so it can diff
// the resulting schema against the Prisma datamodel. Created and dropped per run.
const SHADOW_DB_NAME = "omnibase_migrate_shadow";

function resolveDir(base: string, candidates: string[]): string | null {
  for (const c of candidates) {
    const p = join(base, c);
    if (existsSync(p)) return p;
  }
  return null;
}

function getMigrationDirs(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

function timestamp(): string {
  return String(Math.floor(Date.now() / 1000));
}

// Prisma prints "-- This is an empty migration." (only comments, no DDL) when
// the datamodel already matches the migration history.
function isEmptyPrismaDiff(sql: string): boolean {
  return sql.replace(/^\s*--.*$/gm, "").trim() === "";
}

// Required by `prisma migrate diff --from-migrations`; also harmless for blank migrations.
function ensureMigrationLock(migrationsDir: string): void {
  const lockFile = join(migrationsDir, "migration_lock.toml");
  if (!existsSync(lockFile)) {
    writeFileSync(lockFile, `# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n`);
  }
}

function writeBlankMigration(migrationsDir: string, name: string): string[] {
  const dir = join(migrationsDir, `${timestamp()}_${name}`);
  mkdirSync(dir, { recursive: true });
  const migrationFile = join(dir, "migration.sql");
  const downFile = join(dir, "down.sql");
  writeFileSync(
    migrationFile,
    `-- Migration: ${name}\n-- Created: ${new Date().toISOString()}\n--\n-- Blank migration. Write your SQL below (data backfill, manual DDL, etc.).\n`,
  );
  writeFileSync(
    downFile,
    `-- Rollback for: ${name}\n--\n-- Write SQL that reverses migration.sql, or leave empty if irreversible.\n`,
  );
  return [migrationFile, downFile];
}

function runCmd(
  cmd: string,
  opts?: { env?: Record<string, string>; quiet?: boolean; input?: string },
): { exitCode: number; stdout: string; stderr: string } {
  try {
    const result = execSync(cmd, {
      encoding: "utf-8",
      env: { ...process.env, ...opts?.env } as Record<string, string>,
      stdio: opts?.quiet ? "pipe" : "inherit",
      input: opts?.input,
      maxBuffer: 10 * 1024 * 1024,
    }) as string;
    return { exitCode: 0, stdout: result, stderr: "" };
  } catch (e: any) {
    return {
      exitCode: e.status ?? 1,
      stdout: e.stdout?.toString() ?? "",
      stderr: e.stderr?.toString() ?? e.message ?? "",
    };
  }
}

// Derive the maintenance connection (for CREATE/DROP DATABASE) and the shadow
// connection from the working database URL, preserving credentials and params.
function deriveShadowUrls(dbUrl: string): { maintUrl: string; shadowUrl: string } {
  const maint = new URL(dbUrl);
  maint.pathname = "/postgres";
  const shadow = new URL(dbUrl);
  shadow.pathname = `/${SHADOW_DB_NAME}`;
  return { maintUrl: maint.toString(), shadowUrl: shadow.toString() };
}

function prismaDbExecute(url: string, sql: string): { exitCode: number; stderr: string } {
  const r = runCmd(`npx --yes prisma@6 db execute --url "${url}" --stdin`, {
    quiet: true,
    input: sql,
  });
  return { exitCode: r.exitCode, stderr: r.stderr || r.stdout };
}

function recreateShadowDb(maintUrl: string): void {
  prismaDbExecute(maintUrl, `DROP DATABASE IF EXISTS "${SHADOW_DB_NAME}" WITH (FORCE);`);
  const created = prismaDbExecute(maintUrl, `CREATE DATABASE "${SHADOW_DB_NAME}";`);
  if (created.exitCode !== 0) {
    throw new Error(
      `Failed to create shadow database "${SHADOW_DB_NAME}":\n${created.stderr}\n\n` +
        `Generating migrations needs a Postgres role with the CREATEDB privilege. ` +
        `Check your --db-url / DATABASE_URL.`,
    );
  }
}

function dropShadowDb(maintUrl: string): void {
  prismaDbExecute(maintUrl, `DROP DATABASE IF EXISTS "${SHADOW_DB_NAME}" WITH (FORCE);`);
}

// Replay the migration history into a fresh shadow DB and diff it against the
// Prisma datamodel. Deterministic: depends only on the committed migrations and
// schema.prisma, never on the state of any live database.
function diffMigrationsToDatamodel(
  direction: "up" | "down",
  migrationsDir: string,
  prismaSchema: string,
  dbUrl: string,
  shadowUrl: string,
  maintUrl: string,
): { exitCode: number; stdout: string; stderr: string } {
  recreateShadowDb(maintUrl);
  const fromTo =
    direction === "up"
      ? `--from-migrations "${migrationsDir}" --to-schema-datamodel "${prismaSchema}"`
      : `--from-schema-datamodel "${prismaSchema}" --to-migrations "${migrationsDir}"`;
  return runCmd(
    `npx --yes prisma@6 migrate diff ${fromTo} --shadow-database-url "${shadowUrl}" --script`,
    { env: { DATABASE_URL: dbUrl }, quiet: true },
  );
}

export async function generate(options: GenerateOptions): Promise<string[]> {
  const root = options.projectRoot;

  let migrationsDir = resolveDir(root, [
    "omnibase/db/migrations",
  ]);
  if (!migrationsDir) {
    migrationsDir = join(root, "omnibase", "db", "migrations");
    mkdirSync(migrationsDir, { recursive: true });
  }

  ensureMigrationLock(migrationsDir);

  // Blank migration: skip the Prisma diff + RLS generation entirely.
  if (options.blank) {
    return writeBlankMigration(migrationsDir, options.migrationName);
  }

  const dbUrl = options.dbUrl ?? process.env.DATABASE_URL ?? "postgresql://postgres:postgres@localhost:5432";

  const prismaSchema = resolveDir(root, [
    "omnibase/db/schema.prisma",
  ]);
  if (!prismaSchema) {
    throw new Error("No omnibase/db/schema.prisma found. Run `omnibase init` first.");
  }

  const outputFiles: string[] = [];

  // ── Step 1: Install infra SQL as migrations ─────────────────

  const infraDir = join(__dirname, "..", "..", "..", "docker", "db");
  const existingMigDirs = new Set(getMigrationDirs(migrationsDir));

  if (existsSync(infraDir)) {
    const infraFiles = readdirSync(infraDir)
      .filter((f) => f.endsWith(".up.sql"))
      .sort();

    for (const f of infraFiles) {
      // Skip files that create cluster-wide roles (already exist)
      if (f === "000000_users.up.sql") continue;

      // Convert "000002_rls.up.sql" → "000002_rls"
      const dirName = f.replace(/\.up\.sql$/, "");
      if (!existingMigDirs.has(dirName)) {
        const dir = join(migrationsDir, dirName);
        mkdirSync(dir, { recursive: true });
        const sql = readFileSync(join(infraDir, f), "utf-8");
        writeFileSync(join(dir, "migration.sql"), sql.trimEnd() + "\n");
        writeFileSync(join(dir, "down.sql"), `-- infra migration: ${f}\n`);
      }
    }
  }

  // ── Step 2: Generate Prisma client types ────────────────────

  const genResult = runCmd(
    `npx --yes prisma@6 generate --schema="${prismaSchema}"`,
    { env: { DATABASE_URL: dbUrl }, quiet: true },
  );

  if (genResult.exitCode !== 0) {
    console.warn("Warning: prisma generate failed — types may be out of date");
  }

  // ── Step 3: Generate migration SQL by diffing the datamodel ──
  //
  // The migration history (replayed into a shadow DB) is the source of truth,
  // NOT a live database. `--to-schema-datamodel` diffs against the Prisma models
  // (the previous code used `--to-schema-datasource`, which introspects the
  // datasource database and therefore always produced an empty migration).

  const { maintUrl, shadowUrl } = deriveShadowUrls(dbUrl);
  const before = new Set(getMigrationDirs(migrationsDir));

  let newMigrations: string[] = [];

  try {
    const upDiff = diffMigrationsToDatamodel(
      "up",
      migrationsDir,
      prismaSchema,
      dbUrl,
      shadowUrl,
      maintUrl,
    );
    if (upDiff.exitCode !== 0) {
      throw new Error(`Prisma diff failed:\n${upDiff.stderr || upDiff.stdout}`);
    }

    const upSQL = upDiff.stdout.trim();
    if (upSQL && !isEmptyPrismaDiff(upSQL)) {
      const downDiff = diffMigrationsToDatamodel(
        "down",
        migrationsDir,
        prismaSchema,
        dbUrl,
        shadowUrl,
        maintUrl,
      );
      const rawDown = downDiff.exitCode === 0 ? downDiff.stdout.trim() : "";
      const downSQL = isEmptyPrismaDiff(rawDown) ? "" : rawDown;

      const dirName = `${timestamp()}_${options.migrationName}`;
      const dir = join(migrationsDir, dirName);
      mkdirSync(dir, { recursive: true });
      writeFileSync(join(dir, "migration.sql"), upSQL + "\n");
      writeFileSync(join(dir, "down.sql"), downSQL ? downSQL + "\n" : "-- no down.sql generated\n");
    }
  } finally {
    dropShadowDb(maintUrl);
  }

  newMigrations = getMigrationDirs(migrationsDir).filter((d) => !before.has(d));

  // ── Step 4: Load policies and generate RLS ──────────────────

  clearRegistry();

  const policiesDir = join(root, "omnibase", "db", "policies");
  const policiesIndex = join(policiesDir, "index.ts");
  if (existsSync(policiesIndex)) {
    const files = readdirSync(policiesDir).filter(
      (f) => f.endsWith(".ts") && f !== "index.ts",
    );
    for (const f of files) {
      try {
        await import(join(policiesDir, f));
      } catch (e) {
        // Hard fail: a broken or invalid policy file must not silently drop RLS.
        throw new Error(
          `Failed to load policy file ${f}: ${e instanceof Error ? e.message : String(e)}`,
        );
      }
    }
  }

  const models = Array.from(getRegistry().keys());
  if (models.length > 0) {
    const target =
      newMigrations.length > 0
        ? newMigrations[0]
        : `${timestamp()}_rls_policies`;

    const { upSQL, downSQL } = generateRlsDiffFromMigrations(
      migrationsDir,
      models,
      target,
    );

    if (upSQL.trim()) {
      const dir = join(migrationsDir, target);
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
        writeFileSync(join(dir, "migration.sql"), "");
      }

      const mfile = join(dir, "migration.sql");
      const dfile = join(dir, "down.sql");
      const now = new Date().toISOString();

      writeFileSync(mfile, readFileSync(mfile, "utf-8") + `\n\n-- RLS policies from definePolicy — ${now}\n\n${upSQL}\n`);

      if (downSQL.trim()) {
        const downHeader = `\n\n-- RLS policy rollback — ${now}\n\n${downSQL}\n\n`;
        if (existsSync(dfile)) {
          writeFileSync(dfile, downHeader + readFileSync(dfile, "utf-8"));
        } else {
          writeFileSync(dfile, downHeader);
        }
      }

      if (!newMigrations.includes(target)) newMigrations.push(target);
    }
  }

  for (const m of newMigrations) {
    outputFiles.push(join(migrationsDir, m, "migration.sql"));
    const df = join(migrationsDir, m, "down.sql");
    if (existsSync(df) && readFileSync(df, "utf-8").trim()) {
      outputFiles.push(df);
    }
  }

  return outputFiles;
}
