import { spawn } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const SHADOW_DB_NAME = "omnibase_migrate_shadow";

export async function dropShadowDbAsync(
  maintUrl: string,
  suffix: string = "",
): Promise<void> {
  await prismaDbExecute(
    maintUrl,
    `DROP DATABASE IF EXISTS "${SHADOW_DB_NAME}${suffix}" WITH (FORCE);`,
  );
}

export async function prismaDbExecute(
  url: string,
  sql: string,
): Promise<{ exitCode: number; stderr: string }> {
  const r = await runCmdAsync(
    `npx --yes prisma@6 db execute --url "${url}" --stdin`,
    {
      quiet: true,
      input: sql,
    },
  );
  return { exitCode: r.exitCode, stderr: r.stderr || r.stdout };
}

export async function runCmdAsync(
  cmd: string,
  opts?: { env?: Record<string, string>; quiet?: boolean; input?: string },
): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const child = spawn(cmd, [], {
      shell: true,
      env: { ...process.env, ...opts?.env } as Record<string, string>,
      stdio: ["pipe", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (d: Buffer) => {
      stdout += d.toString();
    });
    child.stderr.on("data", (d: Buffer) => {
      stderr += d.toString();
    });

    if (opts?.input) {
      child.stdin.write(opts.input);
      child.stdin.end();
    }

    child.on("close", (code) =>
      resolve({ exitCode: code ?? 1, stdout, stderr }),
    );
    child.on("error", (err) =>
      resolve({ exitCode: 1, stdout, stderr: err.message }),
    );
  });
}

export function deriveShadowUrls(
  dbUrl: string,
  suffix?: string,
): { maintUrl: string; shadowUrl: string } {
  const maint = new URL(dbUrl);
  maint.pathname = "/postgres";
  const shadow = new URL(dbUrl);
  shadow.pathname = `/${SHADOW_DB_NAME}${suffix ?? ""}`;
  return { maintUrl: maint.toString(), shadowUrl: shadow.toString() };
}

export async function recreateShadowDbAsync(
  maintUrl: string,
  suffix: string = "",
): Promise<void> {
  const dbName = `${SHADOW_DB_NAME}${suffix}`;
  await prismaDbExecute(
    maintUrl,
    `DROP DATABASE IF EXISTS "${dbName}" WITH (FORCE);`,
  );
  const created = await prismaDbExecute(
    maintUrl,
    `CREATE DATABASE "${dbName}";`,
  );
  if (created.exitCode !== 0) {
    throw new Error(
      `Failed to create shadow database "${dbName}":\n${created.stderr}\n\n` +
      `Generating migrations needs a Postgres role with the CREATEDB privilege. ` +
      `Check your --db-url / DATABASE_URL.`,
    );
  }
}
export function ensureMigrationLock(migrationsDir: string): void {
  const lockFile = join(migrationsDir, "migration_lock.toml");
  if (!existsSync(lockFile)) {
    writeFileSync(
      lockFile,
      `# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n`,
    );
  }
}

