/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.
 *
 * The version of the OpenAPI document: local
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArchiveAllResponse
 */
export interface ArchiveAllResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ArchiveAllResponse
     */
    archiveErrors: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ArchiveAllResponse
     */
    archivedItems: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ArchiveAllResponse
     */
    message: string;
    /**
     * 
     * @type {number}
     * @memberof ArchiveAllResponse
     */
    totalArchived: number;
    /**
     * 
     * @type {number}
     * @memberof ArchiveAllResponse
     */
    totalErrors: number;
    /**
     * 
     * @type {string}
     * @memberof ArchiveAllResponse
     */
    warning?: string;
}

/**
 * Check if a given object implements the ArchiveAllResponse interface.
 */
export function instanceOfArchiveAllResponse(value: object): value is ArchiveAllResponse {
    if (!('archiveErrors' in value) || value['archiveErrors'] === undefined) return false;
    if (!('archivedItems' in value) || value['archivedItems'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('totalArchived' in value) || value['totalArchived'] === undefined) return false;
    if (!('totalErrors' in value) || value['totalErrors'] === undefined) return false;
    return true;
}

export function ArchiveAllResponseFromJSON(json: any): ArchiveAllResponse {
    return ArchiveAllResponseFromJSONTyped(json, false);
}

export function ArchiveAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArchiveAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'archiveErrors': json['archive_errors'] == null ? null : json['archive_errors'],
        'archivedItems': json['archived_items'] == null ? null : json['archived_items'],
        'message': json['message'],
        'totalArchived': json['total_archived'],
        'totalErrors': json['total_errors'],
        'warning': json['warning'] == null ? undefined : json['warning'],
    };
}

export function ArchiveAllResponseToJSON(json: any): ArchiveAllResponse {
    return ArchiveAllResponseToJSONTyped(json, false);
}

export function ArchiveAllResponseToJSONTyped(value?: ArchiveAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_errors': value['archiveErrors'],
        'archived_items': value['archivedItems'],
        'message': value['message'],
        'total_archived': value['totalArchived'],
        'total_errors': value['totalErrors'],
        'warning': value['warning'],
    };
}

