/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.18.0
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigHistoryItem } from './ConfigHistoryItem';
import {
    ConfigHistoryItemFromJSON,
    ConfigHistoryItemFromJSONTyped,
    ConfigHistoryItemToJSON,
    ConfigHistoryItemToJSONTyped,
} from './ConfigHistoryItem';
import type { ConfigHistoryPagination } from './ConfigHistoryPagination';
import {
    ConfigHistoryPaginationFromJSON,
    ConfigHistoryPaginationFromJSONTyped,
    ConfigHistoryPaginationToJSON,
    ConfigHistoryPaginationToJSONTyped,
} from './ConfigHistoryPagination';

/**
 * 
 * @export
 * @interface ConfigHistoryResponse
 */
export interface ConfigHistoryResponse {
    /**
     * List of configuration entries
     * @type {Array<ConfigHistoryItem>}
     * @memberof ConfigHistoryResponse
     */
    configs: Array<ConfigHistoryItem>;
    /**
     * 
     * @type {ConfigHistoryPagination}
     * @memberof ConfigHistoryResponse
     */
    pagination: ConfigHistoryPagination;
}

/**
 * Check if a given object implements the ConfigHistoryResponse interface.
 */
export function instanceOfConfigHistoryResponse(value: object): value is ConfigHistoryResponse {
    if (!('configs' in value) || value['configs'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ConfigHistoryResponseFromJSON(json: any): ConfigHistoryResponse {
    return ConfigHistoryResponseFromJSONTyped(json, false);
}

export function ConfigHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'configs': ((json['configs'] as Array<any>).map(ConfigHistoryItemFromJSON)),
        'pagination': ConfigHistoryPaginationFromJSON(json['pagination']),
    };
}

export function ConfigHistoryResponseToJSON(json: any): ConfigHistoryResponse {
    return ConfigHistoryResponseToJSONTyped(json, false);
}

export function ConfigHistoryResponseToJSONTyped(value?: ConfigHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configs': ((value['configs'] as Array<any>).map(ConfigHistoryItemToJSON)),
        'pagination': ConfigHistoryPaginationToJSON(value['pagination']),
    };
}

