/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserRequestName
 */
export interface CreateUserRequestName {
    /**
     * User's first name (letters, spaces, hyphens, dots, apostrophes only)
     * @type {string}
     * @memberof CreateUserRequestName
     */
    first: string;
    /**
     * User's last name (letters, spaces, hyphens, dots, apostrophes only)
     * @type {string}
     * @memberof CreateUserRequestName
     */
    last: string;
}

/**
 * Check if a given object implements the CreateUserRequestName interface.
 */
export function instanceOfCreateUserRequestName(value: object): value is CreateUserRequestName {
    if (!('first' in value) || value['first'] === undefined) return false;
    if (!('last' in value) || value['last'] === undefined) return false;
    return true;
}

export function CreateUserRequestNameFromJSON(json: any): CreateUserRequestName {
    return CreateUserRequestNameFromJSONTyped(json, false);
}

export function CreateUserRequestNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserRequestName {
    if (json == null) {
        return json;
    }
    return {
        
        'first': json['first'],
        'last': json['last'],
    };
}

export function CreateUserRequestNameToJSON(json: any): CreateUserRequestName {
    return CreateUserRequestNameToJSONTyped(json, false);
}

export function CreateUserRequestNameToJSONTyped(value?: CreateUserRequestName | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first': value['first'],
        'last': value['last'],
    };
}

