/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.9.18
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateRelationshipRequestWithSubjectId } from './CreateRelationshipRequestWithSubjectId';
import {
    instanceOfCreateRelationshipRequestWithSubjectId,
    CreateRelationshipRequestWithSubjectIdFromJSON,
    CreateRelationshipRequestWithSubjectIdFromJSONTyped,
    CreateRelationshipRequestWithSubjectIdToJSON,
} from './CreateRelationshipRequestWithSubjectId';
import type { CreateRelationshipRequestWithSubjectSet } from './CreateRelationshipRequestWithSubjectSet';
import {
    instanceOfCreateRelationshipRequestWithSubjectSet,
    CreateRelationshipRequestWithSubjectSetFromJSON,
    CreateRelationshipRequestWithSubjectSetFromJSONTyped,
    CreateRelationshipRequestWithSubjectSetToJSON,
} from './CreateRelationshipRequestWithSubjectSet';

/**
 * @type CreateRelationshipRequest
 * Create relationship request. Must provide exactly one of subject_id or subject_set.
 * @export
 */
export type CreateRelationshipRequest = CreateRelationshipRequestWithSubjectId | CreateRelationshipRequestWithSubjectSet;

export function CreateRelationshipRequestFromJSON(json: any): CreateRelationshipRequest {
    return CreateRelationshipRequestFromJSONTyped(json, false);
}

export function CreateRelationshipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRelationshipRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCreateRelationshipRequestWithSubjectId(json)) {
        return CreateRelationshipRequestWithSubjectIdFromJSONTyped(json, true);
    }
    if (instanceOfCreateRelationshipRequestWithSubjectSet(json)) {
        return CreateRelationshipRequestWithSubjectSetFromJSONTyped(json, true);
    }
    return {} as any;
}

export function CreateRelationshipRequestToJSON(json: any): any {
    return CreateRelationshipRequestToJSONTyped(json, false);
}

export function CreateRelationshipRequestToJSONTyped(value?: CreateRelationshipRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCreateRelationshipRequestWithSubjectId(value)) {
        return CreateRelationshipRequestWithSubjectIdToJSON(value as CreateRelationshipRequestWithSubjectId);
    }
    if (instanceOfCreateRelationshipRequestWithSubjectSet(value)) {
        return CreateRelationshipRequestWithSubjectSetToJSON(value as CreateRelationshipRequestWithSubjectSet);
    }
    return {};
}

