/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.18.1
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCheckoutResponse
 */
export interface CreateCheckoutResponse {
    /**
     * Stripe Checkout Session URL
     * @type {string}
     * @memberof CreateCheckoutResponse
     */
    url: string;
    /**
     * Stripe Checkout Session ID
     * @type {string}
     * @memberof CreateCheckoutResponse
     */
    sessionId: string;
}

/**
 * Check if a given object implements the CreateCheckoutResponse interface.
 */
export function instanceOfCreateCheckoutResponse(value: object): value is CreateCheckoutResponse {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    return true;
}

export function CreateCheckoutResponseFromJSON(json: any): CreateCheckoutResponse {
    return CreateCheckoutResponseFromJSONTyped(json, false);
}

export function CreateCheckoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCheckoutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'sessionId': json['session_id'],
    };
}

export function CreateCheckoutResponseToJSON(json: any): CreateCheckoutResponse {
    return CreateCheckoutResponseToJSONTyped(json, false);
}

export function CreateCheckoutResponseToJSONTyped(value?: CreateCheckoutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'session_id': value['sessionId'],
    };
}

