/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.19.0
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEmailTemplateRequest
 */
export interface CreateEmailTemplateRequest {
    /**
     * Template type identifier (e.g., "welcome", "password-reset")
     * @type {string}
     * @memberof CreateEmailTemplateRequest
     */
    type: string;
    /**
     * Email subject line
     * @type {string}
     * @memberof CreateEmailTemplateRequest
     */
    subject: string;
    /**
     * HTML email body content
     * @type {string}
     * @memberof CreateEmailTemplateRequest
     */
    htmlBody: string;
}

/**
 * Check if a given object implements the CreateEmailTemplateRequest interface.
 */
export function instanceOfCreateEmailTemplateRequest(value: object): value is CreateEmailTemplateRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('htmlBody' in value) || value['htmlBody'] === undefined) return false;
    return true;
}

export function CreateEmailTemplateRequestFromJSON(json: any): CreateEmailTemplateRequest {
    return CreateEmailTemplateRequestFromJSONTyped(json, false);
}

export function CreateEmailTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmailTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'subject': json['subject'],
        'htmlBody': json['html_body'],
    };
}

export function CreateEmailTemplateRequestToJSON(json: any): CreateEmailTemplateRequest {
    return CreateEmailTemplateRequestToJSONTyped(json, false);
}

export function CreateEmailTemplateRequestToJSONTyped(value?: CreateEmailTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'subject': value['subject'],
        'html_body': value['htmlBody'],
    };
}

