/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEmailTemplates200ResponseAllOfData } from './GetEmailTemplates200ResponseAllOfData';
import {
    GetEmailTemplates200ResponseAllOfDataFromJSON,
    GetEmailTemplates200ResponseAllOfDataFromJSONTyped,
    GetEmailTemplates200ResponseAllOfDataToJSON,
    GetEmailTemplates200ResponseAllOfDataToJSONTyped,
} from './GetEmailTemplates200ResponseAllOfData';

/**
 * 
 * @export
 * @interface GetEmailTemplates200Response
 */
export interface GetEmailTemplates200Response {
    /**
     * HTTP status code
     * @type {number}
     * @memberof GetEmailTemplates200Response
     */
    status: number;
    /**
     * 
     * @type {GetEmailTemplates200ResponseAllOfData}
     * @memberof GetEmailTemplates200Response
     */
    data?: GetEmailTemplates200ResponseAllOfData;
}

/**
 * Check if a given object implements the GetEmailTemplates200Response interface.
 */
export function instanceOfGetEmailTemplates200Response(value: object): value is GetEmailTemplates200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GetEmailTemplates200ResponseFromJSON(json: any): GetEmailTemplates200Response {
    return GetEmailTemplates200ResponseFromJSONTyped(json, false);
}

export function GetEmailTemplates200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailTemplates200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : GetEmailTemplates200ResponseAllOfDataFromJSON(json['data']),
    };
}

export function GetEmailTemplates200ResponseToJSON(json: any): GetEmailTemplates200Response {
    return GetEmailTemplates200ResponseToJSONTyped(json, false);
}

export function GetEmailTemplates200ResponseToJSONTyped(value?: GetEmailTemplates200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': GetEmailTemplates200ResponseAllOfDataToJSON(value['data']),
    };
}

