/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.12.5
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KratosIdentityCredentialsPassword
 */
export interface KratosIdentityCredentialsPassword {
    /**
     * 
     * @type {string}
     * @memberof KratosIdentityCredentialsPassword
     */
    type?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof KratosIdentityCredentialsPassword
     */
    identifiers?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof KratosIdentityCredentialsPassword
     */
    version?: number;
    /**
     * 
     * @type {Date}
     * @memberof KratosIdentityCredentialsPassword
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof KratosIdentityCredentialsPassword
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the KratosIdentityCredentialsPassword interface.
 */
export function instanceOfKratosIdentityCredentialsPassword(value: object): value is KratosIdentityCredentialsPassword {
    return true;
}

export function KratosIdentityCredentialsPasswordFromJSON(json: any): KratosIdentityCredentialsPassword {
    return KratosIdentityCredentialsPasswordFromJSONTyped(json, false);
}

export function KratosIdentityCredentialsPasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): KratosIdentityCredentialsPassword {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'identifiers': json['identifiers'] == null ? undefined : json['identifiers'],
        'version': json['version'] == null ? undefined : json['version'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function KratosIdentityCredentialsPasswordToJSON(json: any): KratosIdentityCredentialsPassword {
    return KratosIdentityCredentialsPasswordToJSONTyped(json, false);
}

export function KratosIdentityCredentialsPasswordToJSONTyped(value?: KratosIdentityCredentialsPassword | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'identifiers': value['identifiers'],
        'version': value['version'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

