/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.12.6
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KratosIdentityTraitsName
 */
export interface KratosIdentityTraitsName {
    /**
     * 
     * @type {string}
     * @memberof KratosIdentityTraitsName
     */
    first?: string;
    /**
     * 
     * @type {string}
     * @memberof KratosIdentityTraitsName
     */
    last?: string;
}

/**
 * Check if a given object implements the KratosIdentityTraitsName interface.
 */
export function instanceOfKratosIdentityTraitsName(value: object): value is KratosIdentityTraitsName {
    return true;
}

export function KratosIdentityTraitsNameFromJSON(json: any): KratosIdentityTraitsName {
    return KratosIdentityTraitsNameFromJSONTyped(json, false);
}

export function KratosIdentityTraitsNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): KratosIdentityTraitsName {
    if (json == null) {
        return json;
    }
    return {
        
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function KratosIdentityTraitsNameToJSON(json: any): KratosIdentityTraitsName {
    return KratosIdentityTraitsNameToJSONTyped(json, false);
}

export function KratosIdentityTraitsNameToJSONTyped(value?: KratosIdentityTraitsName | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first': value['first'],
        'last': value['last'],
    };
}

