/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.
 *
 * The version of the OpenAPI document: local
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListStripeWebhooksRow } from './ListStripeWebhooksRow';
import {
    ListStripeWebhooksRowFromJSON,
    ListStripeWebhooksRowFromJSONTyped,
    ListStripeWebhooksRowToJSON,
    ListStripeWebhooksRowToJSONTyped,
} from './ListStripeWebhooksRow';

/**
 * 
 * @export
 * @interface ListWebhooksResponse
 */
export interface ListWebhooksResponse {
    /**
     * 
     * @type {number}
     * @memberof ListWebhooksResponse
     */
    count: number;
    /**
     * 
     * @type {Array<ListStripeWebhooksRow>}
     * @memberof ListWebhooksResponse
     */
    webhooks: Array<ListStripeWebhooksRow> | null;
}

/**
 * Check if a given object implements the ListWebhooksResponse interface.
 */
export function instanceOfListWebhooksResponse(value: object): value is ListWebhooksResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('webhooks' in value) || value['webhooks'] === undefined) return false;
    return true;
}

export function ListWebhooksResponseFromJSON(json: any): ListWebhooksResponse {
    return ListWebhooksResponseFromJSONTyped(json, false);
}

export function ListWebhooksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWebhooksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'webhooks': (json['webhooks'] == null ? null : (json['webhooks'] as Array<any>).map(ListStripeWebhooksRowFromJSON)),
    };
}

export function ListWebhooksResponseToJSON(json: any): ListWebhooksResponse {
    return ListWebhooksResponseToJSONTyped(json, false);
}

export function ListWebhooksResponseToJSONTyped(value?: ListWebhooksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'webhooks': (value['webhooks'] == null ? null : (value['webhooks'] as Array<any>).map(ListStripeWebhooksRowToJSON)),
    };
}

