/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.16.0
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeterChange
 */
export interface MeterChange {
    /**
     * Meter config ID
     * @type {string}
     * @memberof MeterChange
     */
    meterId: string;
    /**
     * Meter display name
     * @type {string}
     * @memberof MeterChange
     */
    displayName: string;
    /**
     * Action performed on the meter
     * @type {string}
     * @memberof MeterChange
     */
    action: MeterChangeActionEnum;
    /**
     * Stripe meter ID
     * @type {string}
     * @memberof MeterChange
     */
    stripeId?: string;
}


/**
 * @export
 */
export const MeterChangeActionEnum = {
    Created: 'created',
    Updated: 'updated',
    Archived: 'archived',
    Linked: 'linked'
} as const;
export type MeterChangeActionEnum = typeof MeterChangeActionEnum[keyof typeof MeterChangeActionEnum];


/**
 * Check if a given object implements the MeterChange interface.
 */
export function instanceOfMeterChange(value: object): value is MeterChange {
    if (!('meterId' in value) || value['meterId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function MeterChangeFromJSON(json: any): MeterChange {
    return MeterChangeFromJSONTyped(json, false);
}

export function MeterChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeterChange {
    if (json == null) {
        return json;
    }
    return {
        
        'meterId': json['meter_id'],
        'displayName': json['display_name'],
        'action': json['action'],
        'stripeId': json['stripe_id'] == null ? undefined : json['stripe_id'],
    };
}

export function MeterChangeToJSON(json: any): MeterChange {
    return MeterChangeToJSONTyped(json, false);
}

export function MeterChangeToJSONTyped(value?: MeterChange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meter_id': value['meterId'],
        'display_name': value['displayName'],
        'action': value['action'],
        'stripe_id': value['stripeId'],
    };
}

