/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.9.16
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceUI } from './PriceUI';
import {
    PriceUIFromJSON,
    PriceUIFromJSONTyped,
    PriceUIToJSON,
    PriceUIToJSONTyped,
} from './PriceUI';

/**
 * 
 * @export
 * @interface PerUnitPrice
 */
export interface PerUnitPrice {
    /**
     * Price identifier (config ID)
     * @type {string}
     * @memberof PerUnitPrice
     */
    id: string;
    /**
     * Whether price is visible in public API (null/true = public, false = enterprise only)
     * @type {boolean}
     * @memberof PerUnitPrice
     */
    _public?: boolean;
    /**
     * Whether tax is included in the price (null/false = exclusive)
     * @type {boolean}
     * @memberof PerUnitPrice
     */
    taxIncludedInPrice?: boolean;
    /**
     * Price amount in smallest currency unit (e.g., cents) - minimum $0.01 per Stripe requirements
     * @type {number}
     * @memberof PerUnitPrice
     */
    amount: number;
    /**
     * Three-letter ISO currency code (lowercase)
     * @type {string}
     * @memberof PerUnitPrice
     */
    currency: PerUnitPriceCurrencyEnum;
    /**
     * Billing interval for recurring prices (required when usage_type is metered)
     * @type {string}
     * @memberof PerUnitPrice
     */
    interval?: PerUnitPriceIntervalEnum;
    /**
     * Number of intervals between billings (default 1)
     * @type {number}
     * @memberof PerUnitPrice
     */
    intervalCount?: number;
    /**
     * Usage type for recurring prices (when set to metered, interval and meter are required)
     * @type {string}
     * @memberof PerUnitPrice
     */
    usageType?: PerUnitPriceUsageTypeEnum;
    /**
     * Meter ID for metered pricing (required when usage_type is metered, must reference a meter defined in the meters array)
     * @type {string}
     * @memberof PerUnitPrice
     */
    meter?: string;
    /**
     * Billing scheme type
     * @type {string}
     * @memberof PerUnitPrice
     */
    billingScheme?: PerUnitPriceBillingSchemeEnum;
    /**
     * Mark as default price for the product
     * @type {boolean}
     * @memberof PerUnitPrice
     */
    _default?: boolean;
    /**
     * 
     * @type {PriceUI}
     * @memberof PerUnitPrice
     */
    ui?: PriceUI;
}

/**
 * Check if a given object implements the PerUnitPrice interface.
 */
export function instanceOfPerUnitPrice(value: object): value is PerUnitPrice {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function PerUnitPriceFromJSON(json: any): PerUnitPrice {
    return PerUnitPriceFromJSONTyped(json, false);
}

export function PerUnitPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerUnitPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        '_public': json['public'] == null ? undefined : json['public'],
        'taxIncludedInPrice': json['tax_included_in_price'] == null ? undefined : json['tax_included_in_price'],
        'amount': json['amount'],
        'currency': json['currency'],
        'interval': json['interval'] == null ? undefined : json['interval'],
        'intervalCount': json['interval_count'] == null ? undefined : json['interval_count'],
        'usageType': json['usage_type'] == null ? undefined : json['usage_type'],
        'meter': json['meter'] == null ? undefined : json['meter'],
        'billingScheme': json['billing_scheme'] == null ? undefined : json['billing_scheme'],
        '_default': json['default'] == null ? undefined : json['default'],
        'ui': json['ui'] == null ? undefined : PriceUIFromJSON(json['ui']),
    };
}

export function PerUnitPriceToJSON(json: any): PerUnitPrice {
    return PerUnitPriceToJSONTyped(json, false);
}

export function PerUnitPriceToJSONTyped(value?: PerUnitPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'public': value['_public'],
        'tax_included_in_price': value['taxIncludedInPrice'],
        'amount': value['amount'],
        'currency': value['currency'],
        'interval': value['interval'],
        'interval_count': value['intervalCount'],
        'usage_type': value['usageType'],
        'meter': value['meter'],
        'billing_scheme': value['billingScheme'],
        'default': value['_default'],
        'ui': PriceUIToJSON(value['ui']),
    };
}

