/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.16.0
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceLimit
 */
export interface PriceLimit {
    /**
     * Limit description
     * @type {string}
     * @memberof PriceLimit
     */
    text: string;
    /**
     * Numeric limit value
     * @type {number}
     * @memberof PriceLimit
     */
    value?: number;
    /**
     * Unit of measurement
     * @type {string}
     * @memberof PriceLimit
     */
    unit?: string;
}

/**
 * Check if a given object implements the PriceLimit interface.
 */
export function instanceOfPriceLimit(value: object): value is PriceLimit {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function PriceLimitFromJSON(json: any): PriceLimit {
    return PriceLimitFromJSONTyped(json, false);
}

export function PriceLimitFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceLimit {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'value': json['value'] == null ? undefined : json['value'],
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function PriceLimitToJSON(json: any): PriceLimit {
    return PriceLimitToJSONTyped(json, false);
}

export function PriceLimitToJSONTyped(value?: PriceLimit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'value': value['value'],
        'unit': value['unit'],
    };
}

