/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.17.0
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PerUnitPrice } from './PerUnitPrice';
import {
    instanceOfPerUnitPrice,
    PerUnitPriceFromJSON,
    PerUnitPriceFromJSONTyped,
    PerUnitPriceToJSON,
} from './PerUnitPrice';
import type { TieredPrice } from './TieredPrice';
import {
    instanceOfTieredPrice,
    TieredPriceFromJSON,
    TieredPriceFromJSONTyped,
    TieredPriceToJSON,
} from './TieredPrice';

/**
 * @type Price
 * 
 * @export
 */
export type Price = PerUnitPrice | TieredPrice;

export function PriceFromJSON(json: any): Price {
    return PriceFromJSONTyped(json, false);
}

export function PriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Price {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfPerUnitPrice(json)) {
        return PerUnitPriceFromJSONTyped(json, true);
    }
    if (instanceOfTieredPrice(json)) {
        return TieredPriceFromJSONTyped(json, true);
    }
    return {} as any;
}

export function PriceToJSON(json: any): any {
    return PriceToJSONTyped(json, false);
}

export function PriceToJSONTyped(value?: Price | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfPerUnitPrice(value)) {
        return PerUnitPriceToJSON(value as PerUnitPrice);
    }
    if (instanceOfTieredPrice(value)) {
        return TieredPriceToJSON(value as TieredPrice);
    }
    return {};
}

