/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.19.1
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceChange
 */
export interface PriceChange {
    /**
     * Price config ID
     * @type {string}
     * @memberof PriceChange
     */
    priceId: string;
    /**
     * Parent product config ID
     * @type {string}
     * @memberof PriceChange
     */
    productId: string;
    /**
     * Action performed on the price
     * @type {string}
     * @memberof PriceChange
     */
    action: PriceChangeActionEnum;
    /**
     * Stripe price ID (if applicable)
     * @type {string}
     * @memberof PriceChange
     */
    stripeId?: string;
}


/**
 * @export
 */
export const PriceChangeActionEnum = {
    Created: 'created',
    Updated: 'updated',
    Archived: 'archived',
    Linked: 'linked'
} as const;
export type PriceChangeActionEnum = typeof PriceChangeActionEnum[keyof typeof PriceChangeActionEnum];


/**
 * Check if a given object implements the PriceChange interface.
 */
export function instanceOfPriceChange(value: object): value is PriceChange {
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function PriceChangeFromJSON(json: any): PriceChange {
    return PriceChangeFromJSONTyped(json, false);
}

export function PriceChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceChange {
    if (json == null) {
        return json;
    }
    return {
        
        'priceId': json['price_id'],
        'productId': json['product_id'],
        'action': json['action'],
        'stripeId': json['stripe_id'] == null ? undefined : json['stripe_id'],
    };
}

export function PriceChangeToJSON(json: any): PriceChange {
    return PriceChangeToJSONTyped(json, false);
}

export function PriceChangeToJSONTyped(value?: PriceChange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'price_id': value['priceId'],
        'product_id': value['productId'],
        'action': value['action'],
        'stripe_id': value['stripeId'],
    };
}

