/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.9.16
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceLimit } from './PriceLimit';
import {
    PriceLimitFromJSON,
    PriceLimitFromJSONTyped,
    PriceLimitToJSON,
    PriceLimitToJSONTyped,
} from './PriceLimit';
import type { PriceDisplay } from './PriceDisplay';
import {
    PriceDisplayFromJSON,
    PriceDisplayFromJSONTyped,
    PriceDisplayToJSON,
    PriceDisplayToJSONTyped,
} from './PriceDisplay';

/**
 * 
 * @export
 * @interface PriceUI
 */
export interface PriceUI {
    /**
     * Display name for this price tier
     * @type {string}
     * @memberof PriceUI
     */
    displayName?: string;
    /**
     * 
     * @type {PriceDisplay}
     * @memberof PriceUI
     */
    priceDisplay?: PriceDisplay;
    /**
     * Human-readable billing period
     * @type {string}
     * @memberof PriceUI
     */
    billingPeriod?: string;
    /**
     * Features specific to this price
     * @type {Array<string>}
     * @memberof PriceUI
     */
    features?: Array<string>;
    /**
     * Usage limits for this price
     * @type {Array<PriceLimit>}
     * @memberof PriceUI
     */
    limits?: Array<PriceLimit>;
}

/**
 * Check if a given object implements the PriceUI interface.
 */
export function instanceOfPriceUI(value: object): value is PriceUI {
    return true;
}

export function PriceUIFromJSON(json: any): PriceUI {
    return PriceUIFromJSONTyped(json, false);
}

export function PriceUIFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceUI {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'priceDisplay': json['price_display'] == null ? undefined : PriceDisplayFromJSON(json['price_display']),
        'billingPeriod': json['billing_period'] == null ? undefined : json['billing_period'],
        'features': json['features'] == null ? undefined : json['features'],
        'limits': json['limits'] == null ? undefined : ((json['limits'] as Array<any>).map(PriceLimitFromJSON)),
    };
}

export function PriceUIToJSON(json: any): PriceUI {
    return PriceUIToJSONTyped(json, false);
}

export function PriceUIToJSONTyped(value?: PriceUI | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
        'price_display': PriceDisplayToJSON(value['priceDisplay']),
        'billing_period': value['billingPeriod'],
        'features': value['features'],
        'limits': value['limits'] == null ? undefined : ((value['limits'] as Array<any>).map(PriceLimitToJSON)),
    };
}

