/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.15.0
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductUI } from './ProductUI';
import {
    ProductUIFromJSON,
    ProductUIFromJSONTyped,
    ProductUIToJSON,
    ProductUIToJSONTyped,
} from './ProductUI';
import type { PriceWithStripeID } from './PriceWithStripeID';
import {
    PriceWithStripeIDFromJSON,
    PriceWithStripeIDFromJSONTyped,
    PriceWithStripeIDToJSON,
    PriceWithStripeIDToJSONTyped,
} from './PriceWithStripeID';

/**
 * 
 * @export
 * @interface ProductWithStripeIDs
 */
export interface ProductWithStripeIDs {
    /**
     * Product identifier (config ID)
     * @type {string}
     * @memberof ProductWithStripeIDs
     */
    id: string;
    /**
     * Product name
     * @type {string}
     * @memberof ProductWithStripeIDs
     */
    name: string;
    /**
     * Product description
     * @type {string}
     * @memberof ProductWithStripeIDs
     */
    description?: string;
    /**
     * Product type
     * @type {string}
     * @memberof ProductWithStripeIDs
     */
    type?: ProductWithStripeIDsTypeEnum;
    /**
     * List of prices with Stripe IDs
     * @type {Array<PriceWithStripeID>}
     * @memberof ProductWithStripeIDs
     */
    prices: Array<PriceWithStripeID>;
    /**
     * 
     * @type {ProductUI}
     * @memberof ProductWithStripeIDs
     */
    ui?: ProductUI;
    /**
     * Actual Stripe product ID (null for free products)
     * @type {string}
     * @memberof ProductWithStripeIDs
     */
    stripeId?: string;
}


/**
 * @export
 */
export const ProductWithStripeIDsTypeEnum = {
    Service: 'service',
    Good: 'good'
} as const;
export type ProductWithStripeIDsTypeEnum = typeof ProductWithStripeIDsTypeEnum[keyof typeof ProductWithStripeIDsTypeEnum];


/**
 * Check if a given object implements the ProductWithStripeIDs interface.
 */
export function instanceOfProductWithStripeIDs(value: object): value is ProductWithStripeIDs {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('prices' in value) || value['prices'] === undefined) return false;
    return true;
}

export function ProductWithStripeIDsFromJSON(json: any): ProductWithStripeIDs {
    return ProductWithStripeIDsFromJSONTyped(json, false);
}

export function ProductWithStripeIDsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductWithStripeIDs {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'prices': ((json['prices'] as Array<any>).map(PriceWithStripeIDFromJSON)),
        'ui': json['ui'] == null ? undefined : ProductUIFromJSON(json['ui']),
        'stripeId': json['stripe_id'] == null ? undefined : json['stripe_id'],
    };
}

export function ProductWithStripeIDsToJSON(json: any): ProductWithStripeIDs {
    return ProductWithStripeIDsToJSONTyped(json, false);
}

export function ProductWithStripeIDsToJSONTyped(value?: ProductWithStripeIDs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'prices': ((value['prices'] as Array<any>).map(PriceWithStripeIDToJSON)),
        'ui': ProductUIToJSON(value['ui']),
        'stripe_id': value['stripeId'],
    };
}

