/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.
 *
 * The version of the OpenAPI document: local
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordUsageRequest
 */
export interface RecordUsageRequest {
    /**
     * 
     * @type {string}
     * @memberof RecordUsageRequest
     */
    meterEventName: string;
    /**
     * 
     * @type {string}
     * @memberof RecordUsageRequest
     */
    value: string;
}

/**
 * Check if a given object implements the RecordUsageRequest interface.
 */
export function instanceOfRecordUsageRequest(value: object): value is RecordUsageRequest {
    if (!('meterEventName' in value) || value['meterEventName'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function RecordUsageRequestFromJSON(json: any): RecordUsageRequest {
    return RecordUsageRequestFromJSONTyped(json, false);
}

export function RecordUsageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordUsageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'meterEventName': json['meter_event_name'],
        'value': json['value'],
    };
}

export function RecordUsageRequestToJSON(json: any): RecordUsageRequest {
    return RecordUsageRequestToJSONTyped(json, false);
}

export function RecordUsageRequestToJSONTyped(value?: RecordUsageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meter_event_name': value['meterEventName'],
        'value': value['value'],
    };
}

