/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.13.0
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubjectSet } from './SubjectSet';
import {
    SubjectSetFromJSON,
    SubjectSetFromJSONTyped,
    SubjectSetToJSON,
    SubjectSetToJSONTyped,
} from './SubjectSet';

/**
 * Keto relationship tuple representing a permission relationship
 * @export
 * @interface Relationship
 */
export interface Relationship {
    /**
     * Namespace of the relation tuple
     * @type {string}
     * @memberof Relationship
     */
    namespace?: string;
    /**
     * Object of the relation tuple
     * @type {string}
     * @memberof Relationship
     */
    object?: string;
    /**
     * Relation of the relation tuple
     * @type {string}
     * @memberof Relationship
     */
    relation?: string;
    /**
     * Subject ID of the relation tuple (optional, mutually exclusive with subject_set)
     * @type {string}
     * @memberof Relationship
     */
    subjectId?: string;
    /**
     * 
     * @type {SubjectSet}
     * @memberof Relationship
     */
    subjectSet?: SubjectSet;
}

/**
 * Check if a given object implements the Relationship interface.
 */
export function instanceOfRelationship(value: object): value is Relationship {
    return true;
}

export function RelationshipFromJSON(json: any): Relationship {
    return RelationshipFromJSONTyped(json, false);
}

export function RelationshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): Relationship {
    if (json == null) {
        return json;
    }
    return {
        
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
        'object': json['object'] == null ? undefined : json['object'],
        'relation': json['relation'] == null ? undefined : json['relation'],
        'subjectId': json['subject_id'] == null ? undefined : json['subject_id'],
        'subjectSet': json['subject_set'] == null ? undefined : SubjectSetFromJSON(json['subject_set']),
    };
}

export function RelationshipToJSON(json: any): Relationship {
    return RelationshipToJSONTyped(json, false);
}

export function RelationshipToJSONTyped(value?: Relationship | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'namespace': value['namespace'],
        'object': value['object'],
        'relation': value['relation'],
        'subject_id': value['subjectId'],
        'subject_set': SubjectSetToJSON(value['subjectSet']),
    };
}

