/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.9.16
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response after switching active tenant
 * @export
 * @interface SwitchTenantResponse
 */
export interface SwitchTenantResponse {
    /**
     * Success message
     * @type {string}
     * @memberof SwitchTenantResponse
     */
    message: string;
    /**
     * New JWT token with updated tenant context
     * @type {string}
     * @memberof SwitchTenantResponse
     */
    token: string;
}

/**
 * Check if a given object implements the SwitchTenantResponse interface.
 */
export function instanceOfSwitchTenantResponse(value: object): value is SwitchTenantResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function SwitchTenantResponseFromJSON(json: any): SwitchTenantResponse {
    return SwitchTenantResponseFromJSONTyped(json, false);
}

export function SwitchTenantResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwitchTenantResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'token': json['token'],
    };
}

export function SwitchTenantResponseToJSON(json: any): SwitchTenantResponse {
    return SwitchTenantResponseToJSONTyped(json, false);
}

export function SwitchTenantResponseToJSONTyped(value?: SwitchTenantResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'token': value['token'],
    };
}

