/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.
 *
 * The version of the OpenAPI document: 0.20.0
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WhoAmIBody
 */
export interface WhoAmIBody {
    /**
     * 
     * @type {boolean}
     * @memberof WhoAmIBody
     */
    authenticated: boolean;
    /**
     * 
     * @type {string}
     * @memberof WhoAmIBody
     */
    userId: string;
}

/**
 * Check if a given object implements the WhoAmIBody interface.
 */
export function instanceOfWhoAmIBody(value: object): value is WhoAmIBody {
    if (!('authenticated' in value) || value['authenticated'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function WhoAmIBodyFromJSON(json: any): WhoAmIBody {
    return WhoAmIBodyFromJSONTyped(json, false);
}

export function WhoAmIBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WhoAmIBody {
    if (json == null) {
        return json;
    }
    return {
        
        'authenticated': json['authenticated'],
        'userId': json['user_id'],
    };
}

export function WhoAmIBodyToJSON(json: any): WhoAmIBody {
    return WhoAmIBodyToJSONTyped(json, false);
}

export function WhoAmIBodyToJSONTyped(value?: WhoAmIBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authenticated': value['authenticated'],
        'user_id': value['userId'],
    };
}

