/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.9.18
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AcceptInvite200Response,
  AcceptInviteRequest,
  AddSubscription200Response,
  AddSubscriptionRequest,
  BadRequestResponse,
  CreateInvite200Response,
  CreateRole200Response,
  CreateRoleRequest,
  CreateTenant200Response,
  CreateTenantRequest,
  CreateTenantUserInviteRequest,
  DeleteRole200Response,
  DeleteTenant200Response,
  DeleteTenantUserRequest,
  ErrorResponse,
  ForbiddenResponse,
  GetRoleDefinitions200Response,
  GetTenantBillingStatus200Response,
  GetTenantJWT200Response,
  ListRoles200Response,
  ListTenantSubscriptions200Response,
  ListTenantUsers200Response,
  RemoveSubscription200Response,
  RemoveSubscriptionRequest,
  SchemasConflictResponse,
  SuccessResponse,
  SwitchActiveTenant200Response,
  SwitchTenantRequest,
  UpdateRoleRequest,
  UpdateTenantUserRole200Response,
  UpdateTenantUserRoleRequest,
} from '../models/index';
import {
    AcceptInvite200ResponseFromJSON,
    AcceptInvite200ResponseToJSON,
    AcceptInviteRequestFromJSON,
    AcceptInviteRequestToJSON,
    AddSubscription200ResponseFromJSON,
    AddSubscription200ResponseToJSON,
    AddSubscriptionRequestFromJSON,
    AddSubscriptionRequestToJSON,
    BadRequestResponseFromJSON,
    BadRequestResponseToJSON,
    CreateInvite200ResponseFromJSON,
    CreateInvite200ResponseToJSON,
    CreateRole200ResponseFromJSON,
    CreateRole200ResponseToJSON,
    CreateRoleRequestFromJSON,
    CreateRoleRequestToJSON,
    CreateTenant200ResponseFromJSON,
    CreateTenant200ResponseToJSON,
    CreateTenantRequestFromJSON,
    CreateTenantRequestToJSON,
    CreateTenantUserInviteRequestFromJSON,
    CreateTenantUserInviteRequestToJSON,
    DeleteRole200ResponseFromJSON,
    DeleteRole200ResponseToJSON,
    DeleteTenant200ResponseFromJSON,
    DeleteTenant200ResponseToJSON,
    DeleteTenantUserRequestFromJSON,
    DeleteTenantUserRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ForbiddenResponseFromJSON,
    ForbiddenResponseToJSON,
    GetRoleDefinitions200ResponseFromJSON,
    GetRoleDefinitions200ResponseToJSON,
    GetTenantBillingStatus200ResponseFromJSON,
    GetTenantBillingStatus200ResponseToJSON,
    GetTenantJWT200ResponseFromJSON,
    GetTenantJWT200ResponseToJSON,
    ListRoles200ResponseFromJSON,
    ListRoles200ResponseToJSON,
    ListTenantSubscriptions200ResponseFromJSON,
    ListTenantSubscriptions200ResponseToJSON,
    ListTenantUsers200ResponseFromJSON,
    ListTenantUsers200ResponseToJSON,
    RemoveSubscription200ResponseFromJSON,
    RemoveSubscription200ResponseToJSON,
    RemoveSubscriptionRequestFromJSON,
    RemoveSubscriptionRequestToJSON,
    SchemasConflictResponseFromJSON,
    SchemasConflictResponseToJSON,
    SuccessResponseFromJSON,
    SuccessResponseToJSON,
    SwitchActiveTenant200ResponseFromJSON,
    SwitchActiveTenant200ResponseToJSON,
    SwitchTenantRequestFromJSON,
    SwitchTenantRequestToJSON,
    UpdateRoleRequestFromJSON,
    UpdateRoleRequestToJSON,
    UpdateTenantUserRole200ResponseFromJSON,
    UpdateTenantUserRole200ResponseToJSON,
    UpdateTenantUserRoleRequestFromJSON,
    UpdateTenantUserRoleRequestToJSON,
} from '../models/index';

export interface AcceptInviteOperationRequest {
    acceptInviteRequest: AcceptInviteRequest;
    xUserId?: string;
}

export interface AddSubscriptionOperationRequest {
    addSubscriptionRequest: AddSubscriptionRequest;
}

export interface CreateInviteRequest {
    createTenantUserInviteRequest: CreateTenantUserInviteRequest;
    xUserId?: string;
    xTenantId?: string;
}

export interface CreateRoleOperationRequest {
    createRoleRequest: CreateRoleRequest;
    xUserId?: string;
    xTenantId?: string;
}

export interface CreateTenantOperationRequest {
    createTenantRequest: CreateTenantRequest;
    xUserId?: string;
}

export interface DeleteRoleRequest {
    roleId: string;
    xUserId?: string;
    xTenantId?: string;
}

export interface DeleteTenantRequest {
    xUserId?: string;
    xTenantId?: string;
}

export interface GetRoleDefinitionsRequest {
    subject?: string;
}

export interface GetTenantJWTRequest {
    xUserId?: string;
    xTenantId?: string;
}

export interface ListRolesRequest {
    xTenantId?: string;
}

export interface ListTenantUsersRequest {
    xUserId?: string;
    xTenantId?: string;
}

export interface RemoveSubscriptionOperationRequest {
    removeSubscriptionRequest: RemoveSubscriptionRequest;
}

export interface RemoveTenantUserRequest {
    deleteTenantUserRequest: DeleteTenantUserRequest;
}

export interface SwitchActiveTenantRequest {
    switchTenantRequest: SwitchTenantRequest;
    xUserId?: string;
}

export interface UpdateRoleOperationRequest {
    roleId: string;
    updateRoleRequest: UpdateRoleRequest;
    xUserId?: string;
    xTenantId?: string;
}

export interface UpdateTenantUserRoleOperationRequest {
    updateTenantUserRoleRequest: UpdateTenantUserRoleRequest;
    xUserId?: string;
    xTenantId?: string;
}

/**
 * 
 */
export class V1TenantsApi extends runtime.BaseAPI {

    /**
     * Accepts a tenant invitation using the token from the invite email and adds the user to the organization.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session - User\'s email must match the invite email - **Service Key Auth**: Requires X-Service-Key + X-User-ID header  ## Process 1. Validates invite token and expiry 2. Verifies user\'s email matches invite email 3. Marks invite as used 4. Adds user to tenant 5. Assigns role with permissions 6. Sets as active tenant and returns JWT token 
     * Accept tenant invite
     */
    async acceptInviteRaw(requestParameters: AcceptInviteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptInvite200Response>> {
        if (requestParameters['acceptInviteRequest'] == null) {
            throw new runtime.RequiredError(
                'acceptInviteRequest',
                'Required parameter "acceptInviteRequest" was null or undefined when calling acceptInvite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xUserId'] != null) {
            headerParameters['X-User-Id'] = String(requestParameters['xUserId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/invites/accept`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AcceptInviteRequestToJSON(requestParameters['acceptInviteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AcceptInvite200ResponseFromJSON(jsonValue));
    }

    /**
     * Accepts a tenant invitation using the token from the invite email and adds the user to the organization.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session - User\'s email must match the invite email - **Service Key Auth**: Requires X-Service-Key + X-User-ID header  ## Process 1. Validates invite token and expiry 2. Verifies user\'s email matches invite email 3. Marks invite as used 4. Adds user to tenant 5. Assigns role with permissions 6. Sets as active tenant and returns JWT token 
     * Accept tenant invite
     */
    async acceptInvite(requestParameters: AcceptInviteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptInvite200Response> {
        const response = await this.acceptInviteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Adds a Stripe subscription for the authenticated tenant using the provided plan ID.  ## Authentication Requires JWT token with tenant context.  ## Request Parameters - **plan_id** (required): The configuration item ID (e.g., \"neon_compute_starter\") that maps to a Stripe price - **stripe_customer_id** (optional): Override tenant\'s Stripe customer ID if needed  ## Process Flow 1. Validates the plan_id and maps it to a Stripe price_id via the stripe_id_mappings table 2. Resolves the Stripe customer ID from the authenticated tenant (or uses provided stripe_customer_id) 3. Checks if subscription already exists for this plan to prevent duplicates 4. Creates the subscription in Stripe with the specified price 5. Returns the subscription ID and status  ## Notes - If a subscription for this plan already exists, returns a 400 error - The subscription is created immediately and begins billing  ## Use Cases - Subscribe tenant to metered pricing plans (compute, storage, workers) - Enable usage-based billing for resources - Add additional services to tenant\'s billing 
     * Add subscription
     */
    async addSubscriptionRaw(requestParameters: AddSubscriptionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddSubscription200Response>> {
        if (requestParameters['addSubscriptionRequest'] == null) {
            throw new runtime.RequiredError(
                'addSubscriptionRequest',
                'Required parameter "addSubscriptionRequest" was null or undefined when calling addSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/subscriptions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddSubscriptionRequestToJSON(requestParameters['addSubscriptionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddSubscription200ResponseFromJSON(jsonValue));
    }

    /**
     * Adds a Stripe subscription for the authenticated tenant using the provided plan ID.  ## Authentication Requires JWT token with tenant context.  ## Request Parameters - **plan_id** (required): The configuration item ID (e.g., \"neon_compute_starter\") that maps to a Stripe price - **stripe_customer_id** (optional): Override tenant\'s Stripe customer ID if needed  ## Process Flow 1. Validates the plan_id and maps it to a Stripe price_id via the stripe_id_mappings table 2. Resolves the Stripe customer ID from the authenticated tenant (or uses provided stripe_customer_id) 3. Checks if subscription already exists for this plan to prevent duplicates 4. Creates the subscription in Stripe with the specified price 5. Returns the subscription ID and status  ## Notes - If a subscription for this plan already exists, returns a 400 error - The subscription is created immediately and begins billing  ## Use Cases - Subscribe tenant to metered pricing plans (compute, storage, workers) - Enable usage-based billing for resources - Add additional services to tenant\'s billing 
     * Add subscription
     */
    async addSubscription(requestParameters: AddSubscriptionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddSubscription200Response> {
        const response = await this.addSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a tenant invitation with a 7-day expiry token and sends an email to the invited user.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with `invite_user` permission - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with `invite_user` permission  ## Process 1. Verifies user has invite permission 2. Creates invite with unique token (7-day expiry) 3. Sends invitation email asynchronously  ## Use Cases - Add team members to organization - Invite collaborators with specific roles 
     * Create tenant invite
     */
    async createInviteRaw(requestParameters: CreateInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateInvite200Response>> {
        if (requestParameters['createTenantUserInviteRequest'] == null) {
            throw new runtime.RequiredError(
                'createTenantUserInviteRequest',
                'Required parameter "createTenantUserInviteRequest" was null or undefined when calling createInvite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xUserId'] != null) {
            headerParameters['X-User-Id'] = String(requestParameters['xUserId']);
        }

        if (requestParameters['xTenantId'] != null) {
            headerParameters['X-Tenant-Id'] = String(requestParameters['xTenantId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/invites`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTenantUserInviteRequestToJSON(requestParameters['createTenantUserInviteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateInvite200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a tenant invitation with a 7-day expiry token and sends an email to the invited user.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with `invite_user` permission - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with `invite_user` permission  ## Process 1. Verifies user has invite permission 2. Creates invite with unique token (7-day expiry) 3. Sends invitation email asynchronously  ## Use Cases - Add team members to organization - Invite collaborators with specific roles 
     * Create tenant invite
     */
    async createInvite(requestParameters: CreateInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateInvite200Response> {
        const response = await this.createInviteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new custom role for the tenant with specified permissions.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with tenant context and appropriate permissions - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with appropriate permissions  ## Permission Format Permissions should be in the format: `namespace:resource#relation` - Tenant-wide: `tenant#relation` - Resource-specific: `project:uuid#relation`  ## Use Cases - Create custom roles for specific workflows - Define project-specific permissions - Build granular access control 
     * Create role
     */
    async createRoleRaw(requestParameters: CreateRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateRole200Response>> {
        if (requestParameters['createRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'createRoleRequest',
                'Required parameter "createRoleRequest" was null or undefined when calling createRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xUserId'] != null) {
            headerParameters['X-User-Id'] = String(requestParameters['xUserId']);
        }

        if (requestParameters['xTenantId'] != null) {
            headerParameters['X-Tenant-Id'] = String(requestParameters['xTenantId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/roles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRoleRequestToJSON(requestParameters['createRoleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateRole200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new custom role for the tenant with specified permissions.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with tenant context and appropriate permissions - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with appropriate permissions  ## Permission Format Permissions should be in the format: `namespace:resource#relation` - Tenant-wide: `tenant#relation` - Resource-specific: `project:uuid#relation`  ## Use Cases - Create custom roles for specific workflows - Define project-specific permissions - Build granular access control 
     * Create role
     */
    async createRole(requestParameters: CreateRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateRole200Response> {
        const response = await this.createRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new tenant organization with Stripe customer, sets up owner role, and makes it the active tenant for the creator.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session (user_id extracted from session) - **Service Key Auth**: Requires X-Service-Key + X-User-ID headers  ## Service Key Usage When using service key authentication, provide the user_id via the X-User-ID header. The user_id must be a valid UUID matching an existing Kratos identity.  ## Process 1. Creates Stripe customer (if billing_email provided) 2. Creates tenant in database 3. Sets up default tenant settings 4. Adds creator as owner 5. Assigns owner role with all permissions 6. Sets as active tenant and returns JWT token 
     * Create tenant
     */
    async createTenantRaw(requestParameters: CreateTenantOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateTenant200Response>> {
        if (requestParameters['createTenantRequest'] == null) {
            throw new runtime.RequiredError(
                'createTenantRequest',
                'Required parameter "createTenantRequest" was null or undefined when calling createTenant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xUserId'] != null) {
            headerParameters['X-User-Id'] = String(requestParameters['xUserId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTenantRequestToJSON(requestParameters['createTenantRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateTenant200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new tenant organization with Stripe customer, sets up owner role, and makes it the active tenant for the creator.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session (user_id extracted from session) - **Service Key Auth**: Requires X-Service-Key + X-User-ID headers  ## Service Key Usage When using service key authentication, provide the user_id via the X-User-ID header. The user_id must be a valid UUID matching an existing Kratos identity.  ## Process 1. Creates Stripe customer (if billing_email provided) 2. Creates tenant in database 3. Sets up default tenant settings 4. Adds creator as owner 5. Assigns owner role with all permissions 6. Sets as active tenant and returns JWT token 
     * Create tenant
     */
    async createTenant(requestParameters: CreateTenantOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateTenant200Response> {
        const response = await this.createTenantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a role and removes all associated Keto relationships for users who had this role assigned.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with tenant context and appropriate permissions - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with appropriate permissions  ## Use Cases - Remove obsolete roles - Clean up role definitions - Revoke all permissions from role users 
     * Delete role
     */
    async deleteRoleRaw(requestParameters: DeleteRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteRole200Response>> {
        if (requestParameters['roleId'] == null) {
            throw new runtime.RequiredError(
                'roleId',
                'Required parameter "roleId" was null or undefined when calling deleteRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xUserId'] != null) {
            headerParameters['X-User-Id'] = String(requestParameters['xUserId']);
        }

        if (requestParameters['xTenantId'] != null) {
            headerParameters['X-Tenant-Id'] = String(requestParameters['xTenantId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/roles/{role_id}`;
        urlPath = urlPath.replace(`{${"role_id"}}`, encodeURIComponent(String(requestParameters['roleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteRole200ResponseFromJSON(jsonValue));
    }

    /**
     * Deletes a role and removes all associated Keto relationships for users who had this role assigned.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with tenant context and appropriate permissions - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with appropriate permissions  ## Use Cases - Remove obsolete roles - Clean up role definitions - Revoke all permissions from role users 
     * Delete role
     */
    async deleteRole(requestParameters: DeleteRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteRole200Response> {
        const response = await this.deleteRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a tenant organization and performs cleanup of Stripe customer, Keto permissions, and user associations.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with `delete_tenant` permission - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with `delete_tenant` permission  ## Process 1. Verifies user has delete permission 2. Archives Stripe customer 3. Deletes tenant (cascades to users, settings, invites) 4. Cleans up all affected users\' tenant state 
     * Delete tenant
     */
    async deleteTenantRaw(requestParameters: DeleteTenantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteTenant200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xUserId'] != null) {
            headerParameters['X-User-Id'] = String(requestParameters['xUserId']);
        }

        if (requestParameters['xTenantId'] != null) {
            headerParameters['X-Tenant-Id'] = String(requestParameters['xTenantId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteTenant200ResponseFromJSON(jsonValue));
    }

    /**
     * Deletes a tenant organization and performs cleanup of Stripe customer, Keto permissions, and user associations.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with `delete_tenant` permission - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with `delete_tenant` permission  ## Process 1. Verifies user has delete permission 2. Archives Stripe customer 3. Deletes tenant (cascades to users, settings, invites) 4. Cleans up all affected users\' tenant state 
     * Delete tenant
     */
    async deleteTenant(requestParameters: DeleteTenantRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteTenant200Response> {
        const response = await this.deleteTenantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all available permission namespaces and their relations from the database.  ## Authentication Requires JWT token with appropriate permissions.  ## Use Cases - Discover available permission namespaces - List relations for each namespace - Build dynamic permission UIs - Filter by subject type for API key creation 
     * Get namespace definitions
     */
    async getRoleDefinitionsRaw(requestParameters: GetRoleDefinitionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetRoleDefinitions200Response>> {
        const queryParameters: any = {};

        if (requestParameters['subject'] != null) {
            queryParameters['subject'] = requestParameters['subject'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/roles/definitions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetRoleDefinitions200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns all available permission namespaces and their relations from the database.  ## Authentication Requires JWT token with appropriate permissions.  ## Use Cases - Discover available permission namespaces - List relations for each namespace - Build dynamic permission UIs - Filter by subject type for API key creation 
     * Get namespace definitions
     */
    async getRoleDefinitions(requestParameters: GetRoleDefinitionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetRoleDefinitions200Response> {
        const response = await this.getRoleDefinitionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Checks whether the tenant has billing information configured in Stripe and if it\'s active.  ## Authentication Requires JWT token with tenant context.  ## Use Cases - Check if billing setup is required - Conditional feature access - Payment method verification 
     * Get billing status
     */
    async getTenantBillingStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTenantBillingStatus200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/billing-status`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTenantBillingStatus200ResponseFromJSON(jsonValue));
    }

    /**
     * Checks whether the tenant has billing information configured in Stripe and if it\'s active.  ## Authentication Requires JWT token with tenant context.  ## Use Cases - Check if billing setup is required - Conditional feature access - Payment method verification 
     * Get billing status
     */
    async getTenantBillingStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTenantBillingStatus200Response> {
        const response = await this.getTenantBillingStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Generates a JWT token for direct PostgREST database access with the user\'s active tenant context.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session and active tenant - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers  ## Use Cases - Client-side database queries - Real-time subscriptions - Direct PostgREST API access 
     * Get PostgREST JWT token
     */
    async getTenantJWTRaw(requestParameters: GetTenantJWTRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTenantJWT200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xUserId'] != null) {
            headerParameters['X-User-Id'] = String(requestParameters['xUserId']);
        }

        if (requestParameters['xTenantId'] != null) {
            headerParameters['X-Tenant-Id'] = String(requestParameters['xTenantId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/jwt`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTenantJWT200ResponseFromJSON(jsonValue));
    }

    /**
     * Generates a JWT token for direct PostgREST database access with the user\'s active tenant context.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session and active tenant - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers  ## Use Cases - Client-side database queries - Real-time subscriptions - Direct PostgREST API access 
     * Get PostgREST JWT token
     */
    async getTenantJWT(requestParameters: GetTenantJWTRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTenantJWT200Response> {
        const response = await this.getTenantJWTRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all roles for the authenticated tenant, including both system roles and custom tenant-specific roles.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with tenant context - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID header  ## Use Cases - Display available roles to assign - Role management UI - Permission auditing 
     * List roles
     */
    async listRolesRaw(requestParameters: ListRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRoles200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xTenantId'] != null) {
            headerParameters['X-Tenant-Id'] = String(requestParameters['xTenantId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/roles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListRoles200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns all roles for the authenticated tenant, including both system roles and custom tenant-specific roles.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with tenant context - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID header  ## Use Cases - Display available roles to assign - Role management UI - Permission auditing 
     * List roles
     */
    async listRoles(requestParameters: ListRolesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRoles200Response> {
        const response = await this.listRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all active Stripe subscriptions associated with the tenant\'s Stripe customer.  ## Authentication Requires JWT token with tenant context.  ## Use Cases - Display current subscriptions - Billing overview - Subscription management UI 
     * Get tenant subscriptions
     */
    async listTenantSubscriptionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTenantSubscriptions200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/subscriptions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTenantSubscriptions200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns all active Stripe subscriptions associated with the tenant\'s Stripe customer.  ## Authentication Requires JWT token with tenant context.  ## Use Cases - Display current subscriptions - Billing overview - Subscription management UI 
     * Get tenant subscriptions
     */
    async listTenantSubscriptions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTenantSubscriptions200Response> {
        const response = await this.listTenantSubscriptionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns all users who are members of the tenant with their profile information and roles.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with `view_users` permission - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with `view_users` permission  ## Use Cases - Display team members list - User management UI - Member directory 
     * Get tenant users
     */
    async listTenantUsersRaw(requestParameters: ListTenantUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTenantUsers200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xUserId'] != null) {
            headerParameters['X-User-Id'] = String(requestParameters['xUserId']);
        }

        if (requestParameters['xTenantId'] != null) {
            headerParameters['X-Tenant-Id'] = String(requestParameters['xTenantId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTenantUsers200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns all users who are members of the tenant with their profile information and roles.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with `view_users` permission - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with `view_users` permission  ## Use Cases - Display team members list - User management UI - Member directory 
     * Get tenant users
     */
    async listTenantUsers(requestParameters: ListTenantUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTenantUsers200Response> {
        const response = await this.listTenantUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Cancels a Stripe subscription immediately for the authenticated tenant based on the plan ID.  ## Authentication Requires JWT token with tenant context.  ## Request Parameters - **plan_id** (required): The configuration item ID (e.g., \"neon_compute_starter\") to identify which subscription to cancel - **stripe_customer_id** (optional): Override tenant\'s Stripe customer ID if needed  ## Process Flow 1. Validates the plan_id and maps it to a Stripe price_id via the stripe_id_mappings table 2. Resolves the Stripe customer ID from the authenticated tenant (or uses provided stripe_customer_id) 3. Finds the active subscription matching the price_id for the customer 4. Cancels the subscription immediately in Stripe 5. Returns the cancellation confirmation  ## Notes - The subscription is canceled immediately, not at the end of the billing period - If no matching subscription is found, returns a 404 error - Only active, trialing, or past_due subscriptions can be canceled  ## Use Cases - Remove specific service subscriptions from tenant - Downgrade by removing premium features - Stop billing for unused resources 
     * Remove subscription
     */
    async removeSubscriptionRaw(requestParameters: RemoveSubscriptionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemoveSubscription200Response>> {
        if (requestParameters['removeSubscriptionRequest'] == null) {
            throw new runtime.RequiredError(
                'removeSubscriptionRequest',
                'Required parameter "removeSubscriptionRequest" was null or undefined when calling removeSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/subscriptions`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: RemoveSubscriptionRequestToJSON(requestParameters['removeSubscriptionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RemoveSubscription200ResponseFromJSON(jsonValue));
    }

    /**
     * Cancels a Stripe subscription immediately for the authenticated tenant based on the plan ID.  ## Authentication Requires JWT token with tenant context.  ## Request Parameters - **plan_id** (required): The configuration item ID (e.g., \"neon_compute_starter\") to identify which subscription to cancel - **stripe_customer_id** (optional): Override tenant\'s Stripe customer ID if needed  ## Process Flow 1. Validates the plan_id and maps it to a Stripe price_id via the stripe_id_mappings table 2. Resolves the Stripe customer ID from the authenticated tenant (or uses provided stripe_customer_id) 3. Finds the active subscription matching the price_id for the customer 4. Cancels the subscription immediately in Stripe 5. Returns the cancellation confirmation  ## Notes - The subscription is canceled immediately, not at the end of the billing period - If no matching subscription is found, returns a 404 error - Only active, trialing, or past_due subscriptions can be canceled  ## Use Cases - Remove specific service subscriptions from tenant - Downgrade by removing premium features - Stop billing for unused resources 
     * Remove subscription
     */
    async removeSubscription(requestParameters: RemoveSubscriptionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemoveSubscription200Response> {
        const response = await this.removeSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes a user from the tenant and cleans up all associated permissions and Keto relationships.  ## Authentication Requires JWT token with `remove_user` permission.  ## Restrictions - Cannot remove the last owner (must have at least one owner) - Removing an owner requires `remove_owner_role` permission  ## Process 1. Verifies permissions 2. Removes from role\'s user list 3. Deletes all Keto relationships 4. Removes from database 5. Cleans up user\'s tenant state 
     * Remove tenant user
     */
    async removeTenantUserRaw(requestParameters: RemoveTenantUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessResponse>> {
        if (requestParameters['deleteTenantUserRequest'] == null) {
            throw new runtime.RequiredError(
                'deleteTenantUserRequest',
                'Required parameter "deleteTenantUserRequest" was null or undefined when calling removeTenantUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/users`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteTenantUserRequestToJSON(requestParameters['deleteTenantUserRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessResponseFromJSON(jsonValue));
    }

    /**
     * Removes a user from the tenant and cleans up all associated permissions and Keto relationships.  ## Authentication Requires JWT token with `remove_user` permission.  ## Restrictions - Cannot remove the last owner (must have at least one owner) - Removing an owner requires `remove_owner_role` permission  ## Process 1. Verifies permissions 2. Removes from role\'s user list 3. Deletes all Keto relationships 4. Removes from database 5. Cleans up user\'s tenant state 
     * Remove tenant user
     */
    async removeTenantUser(requestParameters: RemoveTenantUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessResponse> {
        const response = await this.removeTenantUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the user\'s active tenant in Kratos identity and returns a new JWT token with updated tenant context.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session - **Service Key Auth**: Requires X-Service-Key + X-User-ID header  ## Use Cases - Switch between organizations - Change context for multi-tenant users 
     * Switch active tenant
     */
    async switchActiveTenantRaw(requestParameters: SwitchActiveTenantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SwitchActiveTenant200Response>> {
        if (requestParameters['switchTenantRequest'] == null) {
            throw new runtime.RequiredError(
                'switchTenantRequest',
                'Required parameter "switchTenantRequest" was null or undefined when calling switchActiveTenant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xUserId'] != null) {
            headerParameters['X-User-Id'] = String(requestParameters['xUserId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/switch-active`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SwitchTenantRequestToJSON(requestParameters['switchTenantRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SwitchActiveTenant200ResponseFromJSON(jsonValue));
    }

    /**
     * Updates the user\'s active tenant in Kratos identity and returns a new JWT token with updated tenant context.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session - **Service Key Auth**: Requires X-Service-Key + X-User-ID header  ## Use Cases - Switch between organizations - Change context for multi-tenant users 
     * Switch active tenant
     */
    async switchActiveTenant(requestParameters: SwitchActiveTenantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SwitchActiveTenant200Response> {
        const response = await this.switchActiveTenantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the permissions for an existing role. This will update Keto relationships for all users assigned to this role.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with tenant context and appropriate permissions - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with appropriate permissions  ## Permission Format Permissions should be in the format: `namespace:resource#relation`  ## Use Cases - Modify role permissions - Grant or revoke access - Update role capabilities 
     * Update role
     */
    async updateRoleRaw(requestParameters: UpdateRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateRole200Response>> {
        if (requestParameters['roleId'] == null) {
            throw new runtime.RequiredError(
                'roleId',
                'Required parameter "roleId" was null or undefined when calling updateRole().'
            );
        }

        if (requestParameters['updateRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'updateRoleRequest',
                'Required parameter "updateRoleRequest" was null or undefined when calling updateRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xUserId'] != null) {
            headerParameters['X-User-Id'] = String(requestParameters['xUserId']);
        }

        if (requestParameters['xTenantId'] != null) {
            headerParameters['X-Tenant-Id'] = String(requestParameters['xTenantId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/roles/{role_id}`;
        urlPath = urlPath.replace(`{${"role_id"}}`, encodeURIComponent(String(requestParameters['roleId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRoleRequestToJSON(requestParameters['updateRoleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateRole200ResponseFromJSON(jsonValue));
    }

    /**
     * Updates the permissions for an existing role. This will update Keto relationships for all users assigned to this role.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with tenant context and appropriate permissions - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with appropriate permissions  ## Permission Format Permissions should be in the format: `namespace:resource#relation`  ## Use Cases - Modify role permissions - Grant or revoke access - Update role capabilities 
     * Update role
     */
    async updateRole(requestParameters: UpdateRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateRole200Response> {
        const response = await this.updateRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates a user\'s role in the tenant and updates all associated Keto permissions.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with `update_user_role` permission - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with `update_user_role` permission  ## Restrictions - Promoting to owner requires `update_user_role_to_owner` permission - Demoting from owner requires `remove_owner_role` permission - Cannot demote the last owner (must have at least one owner)  ## Process 1. Verifies permissions 2. Removes old role permissions 3. Updates database 4. Assigns new role permissions 
     * Update user role
     */
    async updateTenantUserRoleRaw(requestParameters: UpdateTenantUserRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateTenantUserRole200Response>> {
        if (requestParameters['updateTenantUserRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'updateTenantUserRoleRequest',
                'Required parameter "updateTenantUserRoleRequest" was null or undefined when calling updateTenantUserRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xUserId'] != null) {
            headerParameters['X-User-Id'] = String(requestParameters['xUserId']);
        }

        if (requestParameters['xTenantId'] != null) {
            headerParameters['X-Tenant-Id'] = String(requestParameters['xTenantId']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // SessionTokenAuth authentication
        }


        let urlPath = `/api/v1/tenants/users`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTenantUserRoleRequestToJSON(requestParameters['updateTenantUserRoleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateTenantUserRole200ResponseFromJSON(jsonValue));
    }

    /**
     * Updates a user\'s role in the tenant and updates all associated Keto permissions.  ## Authentication - **Session Auth**: Requires JWT token / Cookie Session with `update_user_role` permission - **Service Key Auth**: Requires X-Service-Key + X-Tenant-ID + X-User-ID headers with `update_user_role` permission  ## Restrictions - Promoting to owner requires `update_user_role_to_owner` permission - Demoting from owner requires `remove_owner_role` permission - Cannot demote the last owner (must have at least one owner)  ## Process 1. Verifies permissions 2. Removes old role permissions 3. Updates database 4. Assigns new role permissions 
     * Update user role
     */
    async updateTenantUserRole(requestParameters: UpdateTenantUserRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateTenantUserRole200Response> {
        const response = await this.updateTenantUserRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
