/* tslint:disable */
/* eslint-disable */
/**
 * Omnibase REST API
 * Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 
 *
 * The version of the OpenAPI document: 0.12.5
 * Contact: support@omnibase.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequest,
  ConfigureWebhooks200Response,
  ConflictResponse,
  GetWebhookSecret200Response,
  InternalServerError,
  NotFound,
  Unauthorized,
  WebhooksConfigRequest,
} from '../models/index';
import {
    BadRequestFromJSON,
    BadRequestToJSON,
    ConfigureWebhooks200ResponseFromJSON,
    ConfigureWebhooks200ResponseToJSON,
    ConflictResponseFromJSON,
    ConflictResponseToJSON,
    GetWebhookSecret200ResponseFromJSON,
    GetWebhookSecret200ResponseToJSON,
    InternalServerErrorFromJSON,
    InternalServerErrorToJSON,
    NotFoundFromJSON,
    NotFoundToJSON,
    UnauthorizedFromJSON,
    UnauthorizedToJSON,
    WebhooksConfigRequestFromJSON,
    WebhooksConfigRequestToJSON,
} from '../models/index';

export interface ConfigureWebhooksRequest {
    webhooksConfigRequest: WebhooksConfigRequest;
}

/**
 * 
 */
export class V1WebhooksApi extends runtime.BaseAPI {

    /**
     * Creates, updates, or removes multiple webhook endpoints to match the desired configuration. Webhooks not in the request will be deleted.  ## Authentication Requires service key authentication.  ## Connect Webhooks Each webhook can have `connect: true` to listen to events from connected accounts.  ## URL Interpolation URLs support `${VAR}` environment variable interpolation when using the CLI. The CLI resolves these before sending to the API.  ## Use Cases - Configure multiple webhooks for different environments - Set up both account and Connect webhooks - Declarative webhook configuration management 
     * Configure multiple webhook endpoints
     */
    async configureWebhooksRaw(requestParameters: ConfigureWebhooksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigureWebhooks200Response>> {
        if (requestParameters['webhooksConfigRequest'] == null) {
            throw new runtime.RequiredError(
                'webhooksConfigRequest',
                'Required parameter "webhooksConfigRequest" was null or undefined when calling configureWebhooks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }


        let urlPath = `/api/v1/stripe/config/webhooks`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebhooksConfigRequestToJSON(requestParameters['webhooksConfigRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigureWebhooks200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates, updates, or removes multiple webhook endpoints to match the desired configuration. Webhooks not in the request will be deleted.  ## Authentication Requires service key authentication.  ## Connect Webhooks Each webhook can have `connect: true` to listen to events from connected accounts.  ## URL Interpolation URLs support `${VAR}` environment variable interpolation when using the CLI. The CLI resolves these before sending to the API.  ## Use Cases - Configure multiple webhooks for different environments - Set up both account and Connect webhooks - Declarative webhook configuration management 
     * Configure multiple webhook endpoints
     */
    async configureWebhooks(requestParameters: ConfigureWebhooksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigureWebhooks200Response> {
        const response = await this.configureWebhooksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the webhook signing secret for the most recent webhook configuration.  ## Authentication Requires service key authentication.  ## Use Cases - Retrieve signing secret for webhook signature verification - Debug webhook configuration 
     * Get webhook secret
     */
    async getWebhookSecretRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetWebhookSecret200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Service-Key"] = await this.configuration.apiKey("X-Service-Key"); // ServiceKeyAuth authentication
        }


        let urlPath = `/api/v1/stripe/config/webhook`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetWebhookSecret200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the webhook signing secret for the most recent webhook configuration.  ## Authentication Requires service key authentication.  ## Use Cases - Retrieve signing secret for webhook signature verification - Debug webhook configuration 
     * Get webhook secret
     */
    async getWebhookSecret(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetWebhookSecret200Response> {
        const response = await this.getWebhookSecretRaw(initOverrides);
        return await response.value();
    }

}
