/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.

API version: 0.20.0
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCheckoutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCheckoutRequest{}

// CreateCheckoutRequest struct for CreateCheckoutRequest
type CreateCheckoutRequest struct {
	AllowPromotionCodes *bool `json:"allow_promotion_codes,omitempty"`
	CancelUrl string `json:"cancel_url"`
	PriceId string `json:"price_id"`
	PromotionCode *string `json:"promotion_code,omitempty"`
	SuccessUrl string `json:"success_url"`
	TrialPeriodDays *int64 `json:"trial_period_days,omitempty"`
}

type _CreateCheckoutRequest CreateCheckoutRequest

// NewCreateCheckoutRequest instantiates a new CreateCheckoutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCheckoutRequest(cancelUrl string, priceId string, successUrl string) *CreateCheckoutRequest {
	this := CreateCheckoutRequest{}
	this.CancelUrl = cancelUrl
	this.PriceId = priceId
	this.SuccessUrl = successUrl
	return &this
}

// NewCreateCheckoutRequestWithDefaults instantiates a new CreateCheckoutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCheckoutRequestWithDefaults() *CreateCheckoutRequest {
	this := CreateCheckoutRequest{}
	return &this
}

// GetAllowPromotionCodes returns the AllowPromotionCodes field value if set, zero value otherwise.
func (o *CreateCheckoutRequest) GetAllowPromotionCodes() bool {
	if o == nil || IsNil(o.AllowPromotionCodes) {
		var ret bool
		return ret
	}
	return *o.AllowPromotionCodes
}

// GetAllowPromotionCodesOk returns a tuple with the AllowPromotionCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutRequest) GetAllowPromotionCodesOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowPromotionCodes) {
		return nil, false
	}
	return o.AllowPromotionCodes, true
}

// HasAllowPromotionCodes returns a boolean if a field has been set.
func (o *CreateCheckoutRequest) HasAllowPromotionCodes() bool {
	if o != nil && !IsNil(o.AllowPromotionCodes) {
		return true
	}

	return false
}

// SetAllowPromotionCodes gets a reference to the given bool and assigns it to the AllowPromotionCodes field.
func (o *CreateCheckoutRequest) SetAllowPromotionCodes(v bool) {
	o.AllowPromotionCodes = &v
}

// GetCancelUrl returns the CancelUrl field value
func (o *CreateCheckoutRequest) GetCancelUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CancelUrl
}

// GetCancelUrlOk returns a tuple with the CancelUrl field value
// and a boolean to check if the value has been set.
func (o *CreateCheckoutRequest) GetCancelUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CancelUrl, true
}

// SetCancelUrl sets field value
func (o *CreateCheckoutRequest) SetCancelUrl(v string) {
	o.CancelUrl = v
}

// GetPriceId returns the PriceId field value
func (o *CreateCheckoutRequest) GetPriceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PriceId
}

// GetPriceIdOk returns a tuple with the PriceId field value
// and a boolean to check if the value has been set.
func (o *CreateCheckoutRequest) GetPriceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceId, true
}

// SetPriceId sets field value
func (o *CreateCheckoutRequest) SetPriceId(v string) {
	o.PriceId = v
}

// GetPromotionCode returns the PromotionCode field value if set, zero value otherwise.
func (o *CreateCheckoutRequest) GetPromotionCode() string {
	if o == nil || IsNil(o.PromotionCode) {
		var ret string
		return ret
	}
	return *o.PromotionCode
}

// GetPromotionCodeOk returns a tuple with the PromotionCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutRequest) GetPromotionCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PromotionCode) {
		return nil, false
	}
	return o.PromotionCode, true
}

// HasPromotionCode returns a boolean if a field has been set.
func (o *CreateCheckoutRequest) HasPromotionCode() bool {
	if o != nil && !IsNil(o.PromotionCode) {
		return true
	}

	return false
}

// SetPromotionCode gets a reference to the given string and assigns it to the PromotionCode field.
func (o *CreateCheckoutRequest) SetPromotionCode(v string) {
	o.PromotionCode = &v
}

// GetSuccessUrl returns the SuccessUrl field value
func (o *CreateCheckoutRequest) GetSuccessUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SuccessUrl
}

// GetSuccessUrlOk returns a tuple with the SuccessUrl field value
// and a boolean to check if the value has been set.
func (o *CreateCheckoutRequest) GetSuccessUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessUrl, true
}

// SetSuccessUrl sets field value
func (o *CreateCheckoutRequest) SetSuccessUrl(v string) {
	o.SuccessUrl = v
}

// GetTrialPeriodDays returns the TrialPeriodDays field value if set, zero value otherwise.
func (o *CreateCheckoutRequest) GetTrialPeriodDays() int64 {
	if o == nil || IsNil(o.TrialPeriodDays) {
		var ret int64
		return ret
	}
	return *o.TrialPeriodDays
}

// GetTrialPeriodDaysOk returns a tuple with the TrialPeriodDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCheckoutRequest) GetTrialPeriodDaysOk() (*int64, bool) {
	if o == nil || IsNil(o.TrialPeriodDays) {
		return nil, false
	}
	return o.TrialPeriodDays, true
}

// HasTrialPeriodDays returns a boolean if a field has been set.
func (o *CreateCheckoutRequest) HasTrialPeriodDays() bool {
	if o != nil && !IsNil(o.TrialPeriodDays) {
		return true
	}

	return false
}

// SetTrialPeriodDays gets a reference to the given int64 and assigns it to the TrialPeriodDays field.
func (o *CreateCheckoutRequest) SetTrialPeriodDays(v int64) {
	o.TrialPeriodDays = &v
}

func (o CreateCheckoutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCheckoutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllowPromotionCodes) {
		toSerialize["allow_promotion_codes"] = o.AllowPromotionCodes
	}
	toSerialize["cancel_url"] = o.CancelUrl
	toSerialize["price_id"] = o.PriceId
	if !IsNil(o.PromotionCode) {
		toSerialize["promotion_code"] = o.PromotionCode
	}
	toSerialize["success_url"] = o.SuccessUrl
	if !IsNil(o.TrialPeriodDays) {
		toSerialize["trial_period_days"] = o.TrialPeriodDays
	}
	return toSerialize, nil
}

func (o *CreateCheckoutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cancel_url",
		"price_id",
		"success_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCheckoutRequest := _CreateCheckoutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCheckoutRequest)

	if err != nil {
		return err
	}

	*o = CreateCheckoutRequest(varCreateCheckoutRequest)

	return err
}

type NullableCreateCheckoutRequest struct {
	value *CreateCheckoutRequest
	isSet bool
}

func (v NullableCreateCheckoutRequest) Get() *CreateCheckoutRequest {
	return v.value
}

func (v *NullableCreateCheckoutRequest) Set(val *CreateCheckoutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCheckoutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCheckoutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCheckoutRequest(val *CreateCheckoutRequest) *NullableCreateCheckoutRequest {
	return &NullableCreateCheckoutRequest{value: val, isSet: true}
}

func (v NullableCreateCheckoutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCheckoutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


