/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.9.17
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateUser200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateUser200Response{}

// CreateUser200Response struct for CreateUser200Response
type CreateUser200Response struct {
	// HTTP status code
	Status int32 `json:"status"`
	Data *KratosIdentity `json:"data,omitempty"`
}

type _CreateUser200Response CreateUser200Response

// NewCreateUser200Response instantiates a new CreateUser200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateUser200Response(status int32) *CreateUser200Response {
	this := CreateUser200Response{}
	this.Status = status
	return &this
}

// NewCreateUser200ResponseWithDefaults instantiates a new CreateUser200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateUser200ResponseWithDefaults() *CreateUser200Response {
	this := CreateUser200Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *CreateUser200Response) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateUser200Response) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateUser200Response) SetStatus(v int32) {
	o.Status = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateUser200Response) GetData() KratosIdentity {
	if o == nil || IsNil(o.Data) {
		var ret KratosIdentity
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateUser200Response) GetDataOk() (*KratosIdentity, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateUser200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given KratosIdentity and assigns it to the Data field.
func (o *CreateUser200Response) SetData(v KratosIdentity) {
	o.Data = &v
}

func (o CreateUser200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateUser200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

func (o *CreateUser200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateUser200Response := _CreateUser200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateUser200Response)

	if err != nil {
		return err
	}

	*o = CreateUser200Response(varCreateUser200Response)

	return err
}

type NullableCreateUser200Response struct {
	value *CreateUser200Response
	isSet bool
}

func (v NullableCreateUser200Response) Get() *CreateUser200Response {
	return v.value
}

func (v *NullableCreateUser200Response) Set(val *CreateUser200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateUser200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateUser200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateUser200Response(val *CreateUser200Response) *NullableCreateUser200Response {
	return &NullableCreateUser200Response{value: val, isSet: true}
}

func (v NullableCreateUser200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateUser200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


