/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.12.6
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhooksConfigResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhooksConfigResponse{}

// WebhooksConfigResponse struct for WebhooksConfigResponse
type WebhooksConfigResponse struct {
	// List of configured webhook endpoints with results
	Webhooks []WebhookResult `json:"webhooks"`
}

type _WebhooksConfigResponse WebhooksConfigResponse

// NewWebhooksConfigResponse instantiates a new WebhooksConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhooksConfigResponse(webhooks []WebhookResult) *WebhooksConfigResponse {
	this := WebhooksConfigResponse{}
	this.Webhooks = webhooks
	return &this
}

// NewWebhooksConfigResponseWithDefaults instantiates a new WebhooksConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhooksConfigResponseWithDefaults() *WebhooksConfigResponse {
	this := WebhooksConfigResponse{}
	return &this
}

// GetWebhooks returns the Webhooks field value
func (o *WebhooksConfigResponse) GetWebhooks() []WebhookResult {
	if o == nil {
		var ret []WebhookResult
		return ret
	}

	return o.Webhooks
}

// GetWebhooksOk returns a tuple with the Webhooks field value
// and a boolean to check if the value has been set.
func (o *WebhooksConfigResponse) GetWebhooksOk() ([]WebhookResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.Webhooks, true
}

// SetWebhooks sets field value
func (o *WebhooksConfigResponse) SetWebhooks(v []WebhookResult) {
	o.Webhooks = v
}

func (o WebhooksConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhooksConfigResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["webhooks"] = o.Webhooks
	return toSerialize, nil
}

func (o *WebhooksConfigResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"webhooks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhooksConfigResponse := _WebhooksConfigResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhooksConfigResponse)

	if err != nil {
		return err
	}

	*o = WebhooksConfigResponse(varWebhooksConfigResponse)

	return err
}

type NullableWebhooksConfigResponse struct {
	value *WebhooksConfigResponse
	isSet bool
}

func (v NullableWebhooksConfigResponse) Get() *WebhooksConfigResponse {
	return v.value
}

func (v *NullableWebhooksConfigResponse) Set(val *WebhooksConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhooksConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhooksConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhooksConfigResponse(val *WebhooksConfigResponse) *NullableWebhooksConfigResponse {
	return &NullableWebhooksConfigResponse{value: val, isSet: true}
}

func (v NullableWebhooksConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhooksConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


