/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.9.16
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRelationshipRequestOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRelationshipRequestOneOf1{}

// CreateRelationshipRequestOneOf1 struct for CreateRelationshipRequestOneOf1
type CreateRelationshipRequestOneOf1 struct {
	// The namespace for the relationship
	Namespace string `json:"namespace"`
	// The object in the relationship
	Object string `json:"object"`
	// The relation type
	Relation string `json:"relation"`
	SubjectSet SubjectSetRequest `json:"subject_set"`
}

type _CreateRelationshipRequestOneOf1 CreateRelationshipRequestOneOf1

// NewCreateRelationshipRequestOneOf1 instantiates a new CreateRelationshipRequestOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRelationshipRequestOneOf1(namespace string, object string, relation string, subjectSet SubjectSetRequest) *CreateRelationshipRequestOneOf1 {
	this := CreateRelationshipRequestOneOf1{}
	this.Namespace = namespace
	this.Object = object
	this.Relation = relation
	this.SubjectSet = subjectSet
	return &this
}

// NewCreateRelationshipRequestOneOf1WithDefaults instantiates a new CreateRelationshipRequestOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRelationshipRequestOneOf1WithDefaults() *CreateRelationshipRequestOneOf1 {
	this := CreateRelationshipRequestOneOf1{}
	return &this
}

// GetNamespace returns the Namespace field value
func (o *CreateRelationshipRequestOneOf1) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *CreateRelationshipRequestOneOf1) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *CreateRelationshipRequestOneOf1) SetNamespace(v string) {
	o.Namespace = v
}

// GetObject returns the Object field value
func (o *CreateRelationshipRequestOneOf1) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *CreateRelationshipRequestOneOf1) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *CreateRelationshipRequestOneOf1) SetObject(v string) {
	o.Object = v
}

// GetRelation returns the Relation field value
func (o *CreateRelationshipRequestOneOf1) GetRelation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Relation
}

// GetRelationOk returns a tuple with the Relation field value
// and a boolean to check if the value has been set.
func (o *CreateRelationshipRequestOneOf1) GetRelationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relation, true
}

// SetRelation sets field value
func (o *CreateRelationshipRequestOneOf1) SetRelation(v string) {
	o.Relation = v
}

// GetSubjectSet returns the SubjectSet field value
func (o *CreateRelationshipRequestOneOf1) GetSubjectSet() SubjectSetRequest {
	if o == nil {
		var ret SubjectSetRequest
		return ret
	}

	return o.SubjectSet
}

// GetSubjectSetOk returns a tuple with the SubjectSet field value
// and a boolean to check if the value has been set.
func (o *CreateRelationshipRequestOneOf1) GetSubjectSetOk() (*SubjectSetRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubjectSet, true
}

// SetSubjectSet sets field value
func (o *CreateRelationshipRequestOneOf1) SetSubjectSet(v SubjectSetRequest) {
	o.SubjectSet = v
}

func (o CreateRelationshipRequestOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRelationshipRequestOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["namespace"] = o.Namespace
	toSerialize["object"] = o.Object
	toSerialize["relation"] = o.Relation
	toSerialize["subject_set"] = o.SubjectSet
	return toSerialize, nil
}

func (o *CreateRelationshipRequestOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"namespace",
		"object",
		"relation",
		"subject_set",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRelationshipRequestOneOf1 := _CreateRelationshipRequestOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRelationshipRequestOneOf1)

	if err != nil {
		return err
	}

	*o = CreateRelationshipRequestOneOf1(varCreateRelationshipRequestOneOf1)

	return err
}

type NullableCreateRelationshipRequestOneOf1 struct {
	value *CreateRelationshipRequestOneOf1
	isSet bool
}

func (v NullableCreateRelationshipRequestOneOf1) Get() *CreateRelationshipRequestOneOf1 {
	return v.value
}

func (v *NullableCreateRelationshipRequestOneOf1) Set(val *CreateRelationshipRequestOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRelationshipRequestOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRelationshipRequestOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRelationshipRequestOneOf1(val *CreateRelationshipRequestOneOf1) *NullableCreateRelationshipRequestOneOf1 {
	return &NullableCreateRelationshipRequestOneOf1{value: val, isSet: true}
}

func (v NullableCreateRelationshipRequestOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRelationshipRequestOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


