/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.

API version: local
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"fmt"
)

// checks if the UploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadRequest{}

// UploadRequest struct for UploadRequest
type UploadRequest struct {
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Path string `json:"path"`
	AdditionalProperties map[string]interface{}
}

type _UploadRequest UploadRequest

// NewUploadRequest instantiates a new UploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadRequest(path string) *UploadRequest {
	this := UploadRequest{}
	this.Path = path
	return &this
}

// NewUploadRequestWithDefaults instantiates a new UploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadRequestWithDefaults() *UploadRequest {
	this := UploadRequest{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *UploadRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *UploadRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *UploadRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetPath returns the Path field value
func (o *UploadRequest) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *UploadRequest) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *UploadRequest) SetPath(v string) {
	o.Path = v
}

func (o UploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["path"] = o.Path

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UploadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadRequest := _UploadRequest{}

	err = json.Unmarshal(data, &varUploadRequest)

	if err != nil {
		return err
	}

	*o = UploadRequest(varUploadRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "path")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUploadRequest struct {
	value *UploadRequest
	isSet bool
}

func (v NullableUploadRequest) Get() *UploadRequest {
	return v.value
}

func (v *NullableUploadRequest) Set(val *UploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadRequest(val *UploadRequest) *NullableUploadRequest {
	return &NullableUploadRequest{value: val, isSet: true}
}

func (v NullableUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


