/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements.

API version: 0.9.2
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
)

// checks if the TenantsNamespaceDefinitionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantsNamespaceDefinitionsResponse{}

// TenantsNamespaceDefinitionsResponse struct for TenantsNamespaceDefinitionsResponse
type TenantsNamespaceDefinitionsResponse struct {
	// List of namespace definitions
	Definitions []ModelsNamespaceDefinition `json:"definitions,omitempty"`
}

// NewTenantsNamespaceDefinitionsResponse instantiates a new TenantsNamespaceDefinitionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantsNamespaceDefinitionsResponse() *TenantsNamespaceDefinitionsResponse {
	this := TenantsNamespaceDefinitionsResponse{}
	return &this
}

// NewTenantsNamespaceDefinitionsResponseWithDefaults instantiates a new TenantsNamespaceDefinitionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantsNamespaceDefinitionsResponseWithDefaults() *TenantsNamespaceDefinitionsResponse {
	this := TenantsNamespaceDefinitionsResponse{}
	return &this
}

// GetDefinitions returns the Definitions field value if set, zero value otherwise.
func (o *TenantsNamespaceDefinitionsResponse) GetDefinitions() []ModelsNamespaceDefinition {
	if o == nil || IsNil(o.Definitions) {
		var ret []ModelsNamespaceDefinition
		return ret
	}
	return o.Definitions
}

// GetDefinitionsOk returns a tuple with the Definitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantsNamespaceDefinitionsResponse) GetDefinitionsOk() ([]ModelsNamespaceDefinition, bool) {
	if o == nil || IsNil(o.Definitions) {
		return nil, false
	}
	return o.Definitions, true
}

// HasDefinitions returns a boolean if a field has been set.
func (o *TenantsNamespaceDefinitionsResponse) HasDefinitions() bool {
	if o != nil && !IsNil(o.Definitions) {
		return true
	}

	return false
}

// SetDefinitions gets a reference to the given []ModelsNamespaceDefinition and assigns it to the Definitions field.
func (o *TenantsNamespaceDefinitionsResponse) SetDefinitions(v []ModelsNamespaceDefinition) {
	o.Definitions = v
}

func (o TenantsNamespaceDefinitionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantsNamespaceDefinitionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Definitions) {
		toSerialize["definitions"] = o.Definitions
	}
	return toSerialize, nil
}

type NullableTenantsNamespaceDefinitionsResponse struct {
	value *TenantsNamespaceDefinitionsResponse
	isSet bool
}

func (v NullableTenantsNamespaceDefinitionsResponse) Get() *TenantsNamespaceDefinitionsResponse {
	return v.value
}

func (v *NullableTenantsNamespaceDefinitionsResponse) Set(val *TenantsNamespaceDefinitionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantsNamespaceDefinitionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantsNamespaceDefinitionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantsNamespaceDefinitionsResponse(val *TenantsNamespaceDefinitionsResponse) *NullableTenantsNamespaceDefinitionsResponse {
	return &NullableTenantsNamespaceDefinitionsResponse{value: val, isSet: true}
}

func (v NullableTenantsNamespaceDefinitionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantsNamespaceDefinitionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


