/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.19.1
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplyEnterpriseCustomRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplyEnterpriseCustomRequest{}

// ApplyEnterpriseCustomRequest struct for ApplyEnterpriseCustomRequest
type ApplyEnterpriseCustomRequest struct {
	// Tenant ID to apply enterprise pricing to
	TenantId string `json:"tenant_id"`
	// Enterprise pricing group ID (e.g., acme_corp, bigtech_inc)
	EnterpriseId string `json:"enterprise_id"`
}

type _ApplyEnterpriseCustomRequest ApplyEnterpriseCustomRequest

// NewApplyEnterpriseCustomRequest instantiates a new ApplyEnterpriseCustomRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplyEnterpriseCustomRequest(tenantId string, enterpriseId string) *ApplyEnterpriseCustomRequest {
	this := ApplyEnterpriseCustomRequest{}
	this.TenantId = tenantId
	this.EnterpriseId = enterpriseId
	return &this
}

// NewApplyEnterpriseCustomRequestWithDefaults instantiates a new ApplyEnterpriseCustomRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplyEnterpriseCustomRequestWithDefaults() *ApplyEnterpriseCustomRequest {
	this := ApplyEnterpriseCustomRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *ApplyEnterpriseCustomRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *ApplyEnterpriseCustomRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *ApplyEnterpriseCustomRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetEnterpriseId returns the EnterpriseId field value
func (o *ApplyEnterpriseCustomRequest) GetEnterpriseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnterpriseId
}

// GetEnterpriseIdOk returns a tuple with the EnterpriseId field value
// and a boolean to check if the value has been set.
func (o *ApplyEnterpriseCustomRequest) GetEnterpriseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnterpriseId, true
}

// SetEnterpriseId sets field value
func (o *ApplyEnterpriseCustomRequest) SetEnterpriseId(v string) {
	o.EnterpriseId = v
}

func (o ApplyEnterpriseCustomRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplyEnterpriseCustomRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["enterprise_id"] = o.EnterpriseId
	return toSerialize, nil
}

func (o *ApplyEnterpriseCustomRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenant_id",
		"enterprise_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplyEnterpriseCustomRequest := _ApplyEnterpriseCustomRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplyEnterpriseCustomRequest)

	if err != nil {
		return err
	}

	*o = ApplyEnterpriseCustomRequest(varApplyEnterpriseCustomRequest)

	return err
}

type NullableApplyEnterpriseCustomRequest struct {
	value *ApplyEnterpriseCustomRequest
	isSet bool
}

func (v NullableApplyEnterpriseCustomRequest) Get() *ApplyEnterpriseCustomRequest {
	return v.value
}

func (v *NullableApplyEnterpriseCustomRequest) Set(val *ApplyEnterpriseCustomRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplyEnterpriseCustomRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplyEnterpriseCustomRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplyEnterpriseCustomRequest(val *ApplyEnterpriseCustomRequest) *NullableApplyEnterpriseCustomRequest {
	return &NullableApplyEnterpriseCustomRequest{value: val, isSet: true}
}

func (v NullableApplyEnterpriseCustomRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplyEnterpriseCustomRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


