/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements.

API version: 0.9.3
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TenantsAssignRoleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantsAssignRoleResponse{}

// TenantsAssignRoleResponse struct for TenantsAssignRoleResponse
type TenantsAssignRoleResponse struct {
	// Success message
	Message string `json:"message"`
}

type _TenantsAssignRoleResponse TenantsAssignRoleResponse

// NewTenantsAssignRoleResponse instantiates a new TenantsAssignRoleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantsAssignRoleResponse(message string) *TenantsAssignRoleResponse {
	this := TenantsAssignRoleResponse{}
	this.Message = message
	return &this
}

// NewTenantsAssignRoleResponseWithDefaults instantiates a new TenantsAssignRoleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantsAssignRoleResponseWithDefaults() *TenantsAssignRoleResponse {
	this := TenantsAssignRoleResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *TenantsAssignRoleResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *TenantsAssignRoleResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *TenantsAssignRoleResponse) SetMessage(v string) {
	o.Message = v
}

func (o TenantsAssignRoleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantsAssignRoleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *TenantsAssignRoleResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantsAssignRoleResponse := _TenantsAssignRoleResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenantsAssignRoleResponse)

	if err != nil {
		return err
	}

	*o = TenantsAssignRoleResponse(varTenantsAssignRoleResponse)

	return err
}

type NullableTenantsAssignRoleResponse struct {
	value *TenantsAssignRoleResponse
	isSet bool
}

func (v NullableTenantsAssignRoleResponse) Get() *TenantsAssignRoleResponse {
	return v.value
}

func (v *NullableTenantsAssignRoleResponse) Set(val *TenantsAssignRoleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantsAssignRoleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantsAssignRoleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantsAssignRoleResponse(val *TenantsAssignRoleResponse) *NullableTenantsAssignRoleResponse {
	return &NullableTenantsAssignRoleResponse{value: val, isSet: true}
}

func (v NullableTenantsAssignRoleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantsAssignRoleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


