/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.

API version: 0.0.0-dev
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnterprisePricesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnterprisePricesResponse{}

// EnterprisePricesResponse struct for EnterprisePricesResponse
type EnterprisePricesResponse struct {
	Count int64 `json:"count"`
	Prices []PriceWithStripeID `json:"prices"`
}

type _EnterprisePricesResponse EnterprisePricesResponse

// NewEnterprisePricesResponse instantiates a new EnterprisePricesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnterprisePricesResponse(count int64, prices []PriceWithStripeID) *EnterprisePricesResponse {
	this := EnterprisePricesResponse{}
	this.Count = count
	this.Prices = prices
	return &this
}

// NewEnterprisePricesResponseWithDefaults instantiates a new EnterprisePricesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnterprisePricesResponseWithDefaults() *EnterprisePricesResponse {
	this := EnterprisePricesResponse{}
	return &this
}

// GetCount returns the Count field value
func (o *EnterprisePricesResponse) GetCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *EnterprisePricesResponse) GetCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *EnterprisePricesResponse) SetCount(v int64) {
	o.Count = v
}

// GetPrices returns the Prices field value
// If the value is explicit nil, the zero value for []PriceWithStripeID will be returned
func (o *EnterprisePricesResponse) GetPrices() []PriceWithStripeID {
	if o == nil {
		var ret []PriceWithStripeID
		return ret
	}

	return o.Prices
}

// GetPricesOk returns a tuple with the Prices field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnterprisePricesResponse) GetPricesOk() ([]PriceWithStripeID, bool) {
	if o == nil || IsNil(o.Prices) {
		return nil, false
	}
	return o.Prices, true
}

// SetPrices sets field value
func (o *EnterprisePricesResponse) SetPrices(v []PriceWithStripeID) {
	o.Prices = v
}

func (o EnterprisePricesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnterprisePricesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	if o.Prices != nil {
		toSerialize["prices"] = o.Prices
	}
	return toSerialize, nil
}

func (o *EnterprisePricesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"prices",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnterprisePricesResponse := _EnterprisePricesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnterprisePricesResponse)

	if err != nil {
		return err
	}

	*o = EnterprisePricesResponse(varEnterprisePricesResponse)

	return err
}

type NullableEnterprisePricesResponse struct {
	value *EnterprisePricesResponse
	isSet bool
}

func (v NullableEnterprisePricesResponse) Get() *EnterprisePricesResponse {
	return v.value
}

func (v *NullableEnterprisePricesResponse) Set(val *EnterprisePricesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEnterprisePricesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEnterprisePricesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnterprisePricesResponse(val *EnterprisePricesResponse) *NullableEnterprisePricesResponse {
	return &NullableEnterprisePricesResponse{value: val, isSet: true}
}

func (v NullableEnterprisePricesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnterprisePricesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


