/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.19.1
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
)

// checks if the ProductChanges type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductChanges{}

// ProductChanges Summary of product changes made during configuration update
type ProductChanges struct {
	// Products that were created in Stripe
	Created []ProductChange `json:"created,omitempty"`
	// Products that were updated in Stripe
	Updated []ProductChange `json:"updated,omitempty"`
	// Products that were archived in Stripe
	Archived []ProductChange `json:"archived,omitempty"`
}

// NewProductChanges instantiates a new ProductChanges object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductChanges() *ProductChanges {
	this := ProductChanges{}
	return &this
}

// NewProductChangesWithDefaults instantiates a new ProductChanges object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductChangesWithDefaults() *ProductChanges {
	this := ProductChanges{}
	return &this
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ProductChanges) GetCreated() []ProductChange {
	if o == nil || IsNil(o.Created) {
		var ret []ProductChange
		return ret
	}
	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductChanges) GetCreatedOk() ([]ProductChange, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ProductChanges) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given []ProductChange and assigns it to the Created field.
func (o *ProductChanges) SetCreated(v []ProductChange) {
	o.Created = v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *ProductChanges) GetUpdated() []ProductChange {
	if o == nil || IsNil(o.Updated) {
		var ret []ProductChange
		return ret
	}
	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductChanges) GetUpdatedOk() ([]ProductChange, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *ProductChanges) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given []ProductChange and assigns it to the Updated field.
func (o *ProductChanges) SetUpdated(v []ProductChange) {
	o.Updated = v
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *ProductChanges) GetArchived() []ProductChange {
	if o == nil || IsNil(o.Archived) {
		var ret []ProductChange
		return ret
	}
	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductChanges) GetArchivedOk() ([]ProductChange, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *ProductChanges) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given []ProductChange and assigns it to the Archived field.
func (o *ProductChanges) SetArchived(v []ProductChange) {
	o.Archived = v
}

func (o ProductChanges) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductChanges) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	return toSerialize, nil
}

type NullableProductChanges struct {
	value *ProductChanges
	isSet bool
}

func (v NullableProductChanges) Get() *ProductChanges {
	return v.value
}

func (v *NullableProductChanges) Set(val *ProductChanges) {
	v.value = val
	v.isSet = true
}

func (v NullableProductChanges) IsSet() bool {
	return v.isSet
}

func (v *NullableProductChanges) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductChanges(val *ProductChanges) *NullableProductChanges {
	return &NullableProductChanges{value: val, isSet: true}
}

func (v NullableProductChanges) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductChanges) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


