/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.

API version: local
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StripeConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StripeConfiguration{}

// StripeConfiguration struct for StripeConfiguration
type StripeConfiguration struct {
	Coupons []Coupon `json:"coupons,omitempty"`
	Meters []Meter `json:"meters,omitempty"`
	Products []Product `json:"products"`
	PromotionCodes []PromotionCode `json:"promotion_codes,omitempty"`
	Version string `json:"version"`
	Webhooks []WebhookEndpointConfig `json:"webhooks,omitempty"`
}

type _StripeConfiguration StripeConfiguration

// NewStripeConfiguration instantiates a new StripeConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStripeConfiguration(products []Product, version string) *StripeConfiguration {
	this := StripeConfiguration{}
	this.Products = products
	this.Version = version
	return &this
}

// NewStripeConfigurationWithDefaults instantiates a new StripeConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStripeConfigurationWithDefaults() *StripeConfiguration {
	this := StripeConfiguration{}
	return &this
}

// GetCoupons returns the Coupons field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StripeConfiguration) GetCoupons() []Coupon {
	if o == nil {
		var ret []Coupon
		return ret
	}
	return o.Coupons
}

// GetCouponsOk returns a tuple with the Coupons field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StripeConfiguration) GetCouponsOk() ([]Coupon, bool) {
	if o == nil || IsNil(o.Coupons) {
		return nil, false
	}
	return o.Coupons, true
}

// HasCoupons returns a boolean if a field has been set.
func (o *StripeConfiguration) HasCoupons() bool {
	if o != nil && !IsNil(o.Coupons) {
		return true
	}

	return false
}

// SetCoupons gets a reference to the given []Coupon and assigns it to the Coupons field.
func (o *StripeConfiguration) SetCoupons(v []Coupon) {
	o.Coupons = v
}

// GetMeters returns the Meters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StripeConfiguration) GetMeters() []Meter {
	if o == nil {
		var ret []Meter
		return ret
	}
	return o.Meters
}

// GetMetersOk returns a tuple with the Meters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StripeConfiguration) GetMetersOk() ([]Meter, bool) {
	if o == nil || IsNil(o.Meters) {
		return nil, false
	}
	return o.Meters, true
}

// HasMeters returns a boolean if a field has been set.
func (o *StripeConfiguration) HasMeters() bool {
	if o != nil && !IsNil(o.Meters) {
		return true
	}

	return false
}

// SetMeters gets a reference to the given []Meter and assigns it to the Meters field.
func (o *StripeConfiguration) SetMeters(v []Meter) {
	o.Meters = v
}

// GetProducts returns the Products field value
// If the value is explicit nil, the zero value for []Product will be returned
func (o *StripeConfiguration) GetProducts() []Product {
	if o == nil {
		var ret []Product
		return ret
	}

	return o.Products
}

// GetProductsOk returns a tuple with the Products field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StripeConfiguration) GetProductsOk() ([]Product, bool) {
	if o == nil || IsNil(o.Products) {
		return nil, false
	}
	return o.Products, true
}

// SetProducts sets field value
func (o *StripeConfiguration) SetProducts(v []Product) {
	o.Products = v
}

// GetPromotionCodes returns the PromotionCodes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StripeConfiguration) GetPromotionCodes() []PromotionCode {
	if o == nil {
		var ret []PromotionCode
		return ret
	}
	return o.PromotionCodes
}

// GetPromotionCodesOk returns a tuple with the PromotionCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StripeConfiguration) GetPromotionCodesOk() ([]PromotionCode, bool) {
	if o == nil || IsNil(o.PromotionCodes) {
		return nil, false
	}
	return o.PromotionCodes, true
}

// HasPromotionCodes returns a boolean if a field has been set.
func (o *StripeConfiguration) HasPromotionCodes() bool {
	if o != nil && !IsNil(o.PromotionCodes) {
		return true
	}

	return false
}

// SetPromotionCodes gets a reference to the given []PromotionCode and assigns it to the PromotionCodes field.
func (o *StripeConfiguration) SetPromotionCodes(v []PromotionCode) {
	o.PromotionCodes = v
}

// GetVersion returns the Version field value
func (o *StripeConfiguration) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *StripeConfiguration) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *StripeConfiguration) SetVersion(v string) {
	o.Version = v
}

// GetWebhooks returns the Webhooks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StripeConfiguration) GetWebhooks() []WebhookEndpointConfig {
	if o == nil {
		var ret []WebhookEndpointConfig
		return ret
	}
	return o.Webhooks
}

// GetWebhooksOk returns a tuple with the Webhooks field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StripeConfiguration) GetWebhooksOk() ([]WebhookEndpointConfig, bool) {
	if o == nil || IsNil(o.Webhooks) {
		return nil, false
	}
	return o.Webhooks, true
}

// HasWebhooks returns a boolean if a field has been set.
func (o *StripeConfiguration) HasWebhooks() bool {
	if o != nil && !IsNil(o.Webhooks) {
		return true
	}

	return false
}

// SetWebhooks gets a reference to the given []WebhookEndpointConfig and assigns it to the Webhooks field.
func (o *StripeConfiguration) SetWebhooks(v []WebhookEndpointConfig) {
	o.Webhooks = v
}

func (o StripeConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StripeConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Coupons != nil {
		toSerialize["coupons"] = o.Coupons
	}
	if o.Meters != nil {
		toSerialize["meters"] = o.Meters
	}
	if o.Products != nil {
		toSerialize["products"] = o.Products
	}
	if o.PromotionCodes != nil {
		toSerialize["promotion_codes"] = o.PromotionCodes
	}
	toSerialize["version"] = o.Version
	if o.Webhooks != nil {
		toSerialize["webhooks"] = o.Webhooks
	}
	return toSerialize, nil
}

func (o *StripeConfiguration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"products",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStripeConfiguration := _StripeConfiguration{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStripeConfiguration)

	if err != nil {
		return err
	}

	*o = StripeConfiguration(varStripeConfiguration)

	return err
}

type NullableStripeConfiguration struct {
	value *StripeConfiguration
	isSet bool
}

func (v NullableStripeConfiguration) Get() *StripeConfiguration {
	return v.value
}

func (v *NullableStripeConfiguration) Set(val *StripeConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableStripeConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableStripeConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStripeConfiguration(val *StripeConfiguration) *NullableStripeConfiguration {
	return &NullableStripeConfiguration{value: val, isSet: true}
}

func (v NullableStripeConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStripeConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


