/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.10.2
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DownloadFile200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DownloadFile200Response{}

// DownloadFile200Response struct for DownloadFile200Response
type DownloadFile200Response struct {
	// HTTP status code
	Status int32 `json:"status"`
	Data *DownloadResponse `json:"data,omitempty"`
}

type _DownloadFile200Response DownloadFile200Response

// NewDownloadFile200Response instantiates a new DownloadFile200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDownloadFile200Response(status int32) *DownloadFile200Response {
	this := DownloadFile200Response{}
	this.Status = status
	return &this
}

// NewDownloadFile200ResponseWithDefaults instantiates a new DownloadFile200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDownloadFile200ResponseWithDefaults() *DownloadFile200Response {
	this := DownloadFile200Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *DownloadFile200Response) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DownloadFile200Response) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DownloadFile200Response) SetStatus(v int32) {
	o.Status = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DownloadFile200Response) GetData() DownloadResponse {
	if o == nil || IsNil(o.Data) {
		var ret DownloadResponse
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadFile200Response) GetDataOk() (*DownloadResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DownloadFile200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given DownloadResponse and assigns it to the Data field.
func (o *DownloadFile200Response) SetData(v DownloadResponse) {
	o.Data = &v
}

func (o DownloadFile200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DownloadFile200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

func (o *DownloadFile200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDownloadFile200Response := _DownloadFile200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDownloadFile200Response)

	if err != nil {
		return err
	}

	*o = DownloadFile200Response(varDownloadFile200Response)

	return err
}

type NullableDownloadFile200Response struct {
	value *DownloadFile200Response
	isSet bool
}

func (v NullableDownloadFile200Response) Get() *DownloadFile200Response {
	return v.value
}

func (v *NullableDownloadFile200Response) Set(val *DownloadFile200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDownloadFile200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDownloadFile200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDownloadFile200Response(val *DownloadFile200Response) *NullableDownloadFile200Response {
	return &NullableDownloadFile200Response{value: val, isSet: true}
}

func (v NullableDownloadFile200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDownloadFile200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


