/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements.

API version: 0.9.15
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TenantsCreateSubscriptionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantsCreateSubscriptionRequest{}

// TenantsCreateSubscriptionRequest struct for TenantsCreateSubscriptionRequest
type TenantsCreateSubscriptionRequest struct {
	// The plan ID from your Stripe configuration (config item ID)
	PlanId string `json:"plan_id"`
	// Optional Stripe customer ID to use directly (provide either tenant_id OR stripe_customer_id)
	StripeCustomerId *string `json:"stripe_customer_id,omitempty"`
}

type _TenantsCreateSubscriptionRequest TenantsCreateSubscriptionRequest

// NewTenantsCreateSubscriptionRequest instantiates a new TenantsCreateSubscriptionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantsCreateSubscriptionRequest(planId string) *TenantsCreateSubscriptionRequest {
	this := TenantsCreateSubscriptionRequest{}
	this.PlanId = planId
	return &this
}

// NewTenantsCreateSubscriptionRequestWithDefaults instantiates a new TenantsCreateSubscriptionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantsCreateSubscriptionRequestWithDefaults() *TenantsCreateSubscriptionRequest {
	this := TenantsCreateSubscriptionRequest{}
	return &this
}

// GetPlanId returns the PlanId field value
func (o *TenantsCreateSubscriptionRequest) GetPlanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *TenantsCreateSubscriptionRequest) GetPlanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *TenantsCreateSubscriptionRequest) SetPlanId(v string) {
	o.PlanId = v
}

// GetStripeCustomerId returns the StripeCustomerId field value if set, zero value otherwise.
func (o *TenantsCreateSubscriptionRequest) GetStripeCustomerId() string {
	if o == nil || IsNil(o.StripeCustomerId) {
		var ret string
		return ret
	}
	return *o.StripeCustomerId
}

// GetStripeCustomerIdOk returns a tuple with the StripeCustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantsCreateSubscriptionRequest) GetStripeCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.StripeCustomerId) {
		return nil, false
	}
	return o.StripeCustomerId, true
}

// HasStripeCustomerId returns a boolean if a field has been set.
func (o *TenantsCreateSubscriptionRequest) HasStripeCustomerId() bool {
	if o != nil && !IsNil(o.StripeCustomerId) {
		return true
	}

	return false
}

// SetStripeCustomerId gets a reference to the given string and assigns it to the StripeCustomerId field.
func (o *TenantsCreateSubscriptionRequest) SetStripeCustomerId(v string) {
	o.StripeCustomerId = &v
}

func (o TenantsCreateSubscriptionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantsCreateSubscriptionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plan_id"] = o.PlanId
	if !IsNil(o.StripeCustomerId) {
		toSerialize["stripe_customer_id"] = o.StripeCustomerId
	}
	return toSerialize, nil
}

func (o *TenantsCreateSubscriptionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantsCreateSubscriptionRequest := _TenantsCreateSubscriptionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenantsCreateSubscriptionRequest)

	if err != nil {
		return err
	}

	*o = TenantsCreateSubscriptionRequest(varTenantsCreateSubscriptionRequest)

	return err
}

type NullableTenantsCreateSubscriptionRequest struct {
	value *TenantsCreateSubscriptionRequest
	isSet bool
}

func (v NullableTenantsCreateSubscriptionRequest) Get() *TenantsCreateSubscriptionRequest {
	return v.value
}

func (v *NullableTenantsCreateSubscriptionRequest) Set(val *TenantsCreateSubscriptionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantsCreateSubscriptionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantsCreateSubscriptionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantsCreateSubscriptionRequest(val *TenantsCreateSubscriptionRequest) *NullableTenantsCreateSubscriptionRequest {
	return &NullableTenantsCreateSubscriptionRequest{value: val, isSet: true}
}

func (v NullableTenantsCreateSubscriptionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantsCreateSubscriptionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


