/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.

API version: local
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecordUsageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordUsageRequest{}

// RecordUsageRequest struct for RecordUsageRequest
type RecordUsageRequest struct {
	MeterEventName string `json:"meter_event_name"`
	Value string `json:"value"`
}

type _RecordUsageRequest RecordUsageRequest

// NewRecordUsageRequest instantiates a new RecordUsageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordUsageRequest(meterEventName string, value string) *RecordUsageRequest {
	this := RecordUsageRequest{}
	this.MeterEventName = meterEventName
	this.Value = value
	return &this
}

// NewRecordUsageRequestWithDefaults instantiates a new RecordUsageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordUsageRequestWithDefaults() *RecordUsageRequest {
	this := RecordUsageRequest{}
	return &this
}

// GetMeterEventName returns the MeterEventName field value
func (o *RecordUsageRequest) GetMeterEventName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MeterEventName
}

// GetMeterEventNameOk returns a tuple with the MeterEventName field value
// and a boolean to check if the value has been set.
func (o *RecordUsageRequest) GetMeterEventNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MeterEventName, true
}

// SetMeterEventName sets field value
func (o *RecordUsageRequest) SetMeterEventName(v string) {
	o.MeterEventName = v
}

// GetValue returns the Value field value
func (o *RecordUsageRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *RecordUsageRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *RecordUsageRequest) SetValue(v string) {
	o.Value = v
}

func (o RecordUsageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordUsageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meter_event_name"] = o.MeterEventName
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *RecordUsageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"meter_event_name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecordUsageRequest := _RecordUsageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecordUsageRequest)

	if err != nil {
		return err
	}

	*o = RecordUsageRequest(varRecordUsageRequest)

	return err
}

type NullableRecordUsageRequest struct {
	value *RecordUsageRequest
	isSet bool
}

func (v NullableRecordUsageRequest) Get() *RecordUsageRequest {
	return v.value
}

func (v *NullableRecordUsageRequest) Set(val *RecordUsageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordUsageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordUsageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordUsageRequest(val *RecordUsageRequest) *NullableRecordUsageRequest {
	return &NullableRecordUsageRequest{value: val, isSet: true}
}

func (v NullableRecordUsageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordUsageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


