/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements.

API version: 0.9.5
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
)

// checks if the DeleteTenant200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteTenant200Response{}

// DeleteTenant200Response struct for DeleteTenant200Response
type DeleteTenant200Response struct {
	Data *TenantsDeleteTenantResponse `json:"data,omitempty"`
	// HTTP status code
	Status *int32 `json:"status,omitempty"`
}

// NewDeleteTenant200Response instantiates a new DeleteTenant200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteTenant200Response() *DeleteTenant200Response {
	this := DeleteTenant200Response{}
	return &this
}

// NewDeleteTenant200ResponseWithDefaults instantiates a new DeleteTenant200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteTenant200ResponseWithDefaults() *DeleteTenant200Response {
	this := DeleteTenant200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DeleteTenant200Response) GetData() TenantsDeleteTenantResponse {
	if o == nil || IsNil(o.Data) {
		var ret TenantsDeleteTenantResponse
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteTenant200Response) GetDataOk() (*TenantsDeleteTenantResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DeleteTenant200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given TenantsDeleteTenantResponse and assigns it to the Data field.
func (o *DeleteTenant200Response) SetData(v TenantsDeleteTenantResponse) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeleteTenant200Response) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteTenant200Response) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeleteTenant200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *DeleteTenant200Response) SetStatus(v int32) {
	o.Status = &v
}

func (o DeleteTenant200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteTenant200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableDeleteTenant200Response struct {
	value *DeleteTenant200Response
	isSet bool
}

func (v NullableDeleteTenant200Response) Get() *DeleteTenant200Response {
	return v.value
}

func (v *NullableDeleteTenant200Response) Set(val *DeleteTenant200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteTenant200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteTenant200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteTenant200Response(val *DeleteTenant200Response) *NullableDeleteTenant200Response {
	return &NullableDeleteTenant200Response{value: val, isSet: true}
}

func (v NullableDeleteTenant200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteTenant200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


