/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements.

API version: 0.9.9
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TenantsDeleteRoleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantsDeleteRoleResponse{}

// TenantsDeleteRoleResponse struct for TenantsDeleteRoleResponse
type TenantsDeleteRoleResponse struct {
	// Success message
	Message string `json:"message"`
}

type _TenantsDeleteRoleResponse TenantsDeleteRoleResponse

// NewTenantsDeleteRoleResponse instantiates a new TenantsDeleteRoleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantsDeleteRoleResponse(message string) *TenantsDeleteRoleResponse {
	this := TenantsDeleteRoleResponse{}
	this.Message = message
	return &this
}

// NewTenantsDeleteRoleResponseWithDefaults instantiates a new TenantsDeleteRoleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantsDeleteRoleResponseWithDefaults() *TenantsDeleteRoleResponse {
	this := TenantsDeleteRoleResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *TenantsDeleteRoleResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *TenantsDeleteRoleResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *TenantsDeleteRoleResponse) SetMessage(v string) {
	o.Message = v
}

func (o TenantsDeleteRoleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantsDeleteRoleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *TenantsDeleteRoleResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantsDeleteRoleResponse := _TenantsDeleteRoleResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenantsDeleteRoleResponse)

	if err != nil {
		return err
	}

	*o = TenantsDeleteRoleResponse(varTenantsDeleteRoleResponse)

	return err
}

type NullableTenantsDeleteRoleResponse struct {
	value *TenantsDeleteRoleResponse
	isSet bool
}

func (v NullableTenantsDeleteRoleResponse) Get() *TenantsDeleteRoleResponse {
	return v.value
}

func (v *NullableTenantsDeleteRoleResponse) Set(val *TenantsDeleteRoleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantsDeleteRoleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantsDeleteRoleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantsDeleteRoleResponse(val *TenantsDeleteRoleResponse) *NullableTenantsDeleteRoleResponse {
	return &NullableTenantsDeleteRoleResponse{value: val, isSet: true}
}

func (v NullableTenantsDeleteRoleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantsDeleteRoleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


