/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.

API version: 0.20.0
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateResponse{}

// CreateResponse struct for CreateResponse
type CreateResponse struct {
	Invite AuthTenantInvite `json:"invite"`
	Message string `json:"message"`
}

type _CreateResponse CreateResponse

// NewCreateResponse instantiates a new CreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateResponse(invite AuthTenantInvite, message string) *CreateResponse {
	this := CreateResponse{}
	this.Invite = invite
	this.Message = message
	return &this
}

// NewCreateResponseWithDefaults instantiates a new CreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateResponseWithDefaults() *CreateResponse {
	this := CreateResponse{}
	return &this
}

// GetInvite returns the Invite field value
func (o *CreateResponse) GetInvite() AuthTenantInvite {
	if o == nil {
		var ret AuthTenantInvite
		return ret
	}

	return o.Invite
}

// GetInviteOk returns a tuple with the Invite field value
// and a boolean to check if the value has been set.
func (o *CreateResponse) GetInviteOk() (*AuthTenantInvite, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Invite, true
}

// SetInvite sets field value
func (o *CreateResponse) SetInvite(v AuthTenantInvite) {
	o.Invite = v
}

// GetMessage returns the Message field value
func (o *CreateResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CreateResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CreateResponse) SetMessage(v string) {
	o.Message = v
}

func (o CreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invite"] = o.Invite
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *CreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invite",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateResponse := _CreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateResponse)

	if err != nil {
		return err
	}

	*o = CreateResponse(varCreateResponse)

	return err
}

type NullableCreateResponse struct {
	value *CreateResponse
	isSet bool
}

func (v NullableCreateResponse) Get() *CreateResponse {
	return v.value
}

func (v *NullableCreateResponse) Set(val *CreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateResponse(val *CreateResponse) *NullableCreateResponse {
	return &NullableCreateResponse{value: val, isSet: true}
}

func (v NullableCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


