/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.19.1
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
)

// checks if the KratosIdentityCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KratosIdentityCredentials{}

// KratosIdentityCredentials Authentication credentials information
type KratosIdentityCredentials struct {
	Password *KratosIdentityCredentialsPassword `json:"password,omitempty"`
}

// NewKratosIdentityCredentials instantiates a new KratosIdentityCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKratosIdentityCredentials() *KratosIdentityCredentials {
	this := KratosIdentityCredentials{}
	return &this
}

// NewKratosIdentityCredentialsWithDefaults instantiates a new KratosIdentityCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKratosIdentityCredentialsWithDefaults() *KratosIdentityCredentials {
	this := KratosIdentityCredentials{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *KratosIdentityCredentials) GetPassword() KratosIdentityCredentialsPassword {
	if o == nil || IsNil(o.Password) {
		var ret KratosIdentityCredentialsPassword
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KratosIdentityCredentials) GetPasswordOk() (*KratosIdentityCredentialsPassword, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *KratosIdentityCredentials) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given KratosIdentityCredentialsPassword and assigns it to the Password field.
func (o *KratosIdentityCredentials) SetPassword(v KratosIdentityCredentialsPassword) {
	o.Password = &v
}

func (o KratosIdentityCredentials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KratosIdentityCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableKratosIdentityCredentials struct {
	value *KratosIdentityCredentials
	isSet bool
}

func (v NullableKratosIdentityCredentials) Get() *KratosIdentityCredentials {
	return v.value
}

func (v *NullableKratosIdentityCredentials) Set(val *KratosIdentityCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableKratosIdentityCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableKratosIdentityCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKratosIdentityCredentials(val *KratosIdentityCredentials) *NullableKratosIdentityCredentials {
	return &NullableKratosIdentityCredentials{value: val, isSet: true}
}

func (v NullableKratosIdentityCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKratosIdentityCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


