/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements.

API version: 0.9.11
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
)

// checks if the ModelsActiveTenantResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsActiveTenantResponse{}

// ModelsActiveTenantResponse struct for ModelsActiveTenantResponse
type ModelsActiveTenantResponse struct {
	Tenant *ModelsTenant `json:"tenant,omitempty"`
}

// NewModelsActiveTenantResponse instantiates a new ModelsActiveTenantResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsActiveTenantResponse() *ModelsActiveTenantResponse {
	this := ModelsActiveTenantResponse{}
	return &this
}

// NewModelsActiveTenantResponseWithDefaults instantiates a new ModelsActiveTenantResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsActiveTenantResponseWithDefaults() *ModelsActiveTenantResponse {
	this := ModelsActiveTenantResponse{}
	return &this
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *ModelsActiveTenantResponse) GetTenant() ModelsTenant {
	if o == nil || IsNil(o.Tenant) {
		var ret ModelsTenant
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsActiveTenantResponse) GetTenantOk() (*ModelsTenant, bool) {
	if o == nil || IsNil(o.Tenant) {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *ModelsActiveTenantResponse) HasTenant() bool {
	if o != nil && !IsNil(o.Tenant) {
		return true
	}

	return false
}

// SetTenant gets a reference to the given ModelsTenant and assigns it to the Tenant field.
func (o *ModelsActiveTenantResponse) SetTenant(v ModelsTenant) {
	o.Tenant = &v
}

func (o ModelsActiveTenantResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsActiveTenantResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tenant) {
		toSerialize["tenant"] = o.Tenant
	}
	return toSerialize, nil
}

type NullableModelsActiveTenantResponse struct {
	value *ModelsActiveTenantResponse
	isSet bool
}

func (v NullableModelsActiveTenantResponse) Get() *ModelsActiveTenantResponse {
	return v.value
}

func (v *NullableModelsActiveTenantResponse) Set(val *ModelsActiveTenantResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsActiveTenantResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsActiveTenantResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsActiveTenantResponse(val *ModelsActiveTenantResponse) *NullableModelsActiveTenantResponse {
	return &NullableModelsActiveTenantResponse{value: val, isSet: true}
}

func (v NullableModelsActiveTenantResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsActiveTenantResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


