/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.

API version: local
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplyEnterpriseTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplyEnterpriseTemplateRequest{}

// ApplyEnterpriseTemplateRequest struct for ApplyEnterpriseTemplateRequest
type ApplyEnterpriseTemplateRequest struct {
	EnterpriseTemplate string `json:"enterprise_template"`
	TenantId string `json:"tenant_id"`
}

type _ApplyEnterpriseTemplateRequest ApplyEnterpriseTemplateRequest

// NewApplyEnterpriseTemplateRequest instantiates a new ApplyEnterpriseTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplyEnterpriseTemplateRequest(enterpriseTemplate string, tenantId string) *ApplyEnterpriseTemplateRequest {
	this := ApplyEnterpriseTemplateRequest{}
	this.EnterpriseTemplate = enterpriseTemplate
	this.TenantId = tenantId
	return &this
}

// NewApplyEnterpriseTemplateRequestWithDefaults instantiates a new ApplyEnterpriseTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplyEnterpriseTemplateRequestWithDefaults() *ApplyEnterpriseTemplateRequest {
	this := ApplyEnterpriseTemplateRequest{}
	return &this
}

// GetEnterpriseTemplate returns the EnterpriseTemplate field value
func (o *ApplyEnterpriseTemplateRequest) GetEnterpriseTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnterpriseTemplate
}

// GetEnterpriseTemplateOk returns a tuple with the EnterpriseTemplate field value
// and a boolean to check if the value has been set.
func (o *ApplyEnterpriseTemplateRequest) GetEnterpriseTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnterpriseTemplate, true
}

// SetEnterpriseTemplate sets field value
func (o *ApplyEnterpriseTemplateRequest) SetEnterpriseTemplate(v string) {
	o.EnterpriseTemplate = v
}

// GetTenantId returns the TenantId field value
func (o *ApplyEnterpriseTemplateRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *ApplyEnterpriseTemplateRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *ApplyEnterpriseTemplateRequest) SetTenantId(v string) {
	o.TenantId = v
}

func (o ApplyEnterpriseTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplyEnterpriseTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enterprise_template"] = o.EnterpriseTemplate
	toSerialize["tenant_id"] = o.TenantId
	return toSerialize, nil
}

func (o *ApplyEnterpriseTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enterprise_template",
		"tenant_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplyEnterpriseTemplateRequest := _ApplyEnterpriseTemplateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplyEnterpriseTemplateRequest)

	if err != nil {
		return err
	}

	*o = ApplyEnterpriseTemplateRequest(varApplyEnterpriseTemplateRequest)

	return err
}

type NullableApplyEnterpriseTemplateRequest struct {
	value *ApplyEnterpriseTemplateRequest
	isSet bool
}

func (v NullableApplyEnterpriseTemplateRequest) Get() *ApplyEnterpriseTemplateRequest {
	return v.value
}

func (v *NullableApplyEnterpriseTemplateRequest) Set(val *ApplyEnterpriseTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplyEnterpriseTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplyEnterpriseTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplyEnterpriseTemplateRequest(val *ApplyEnterpriseTemplateRequest) *NullableApplyEnterpriseTemplateRequest {
	return &NullableApplyEnterpriseTemplateRequest{value: val, isSet: true}
}

func (v NullableApplyEnterpriseTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplyEnterpriseTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


