/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.10.2
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RolesListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RolesListResponse{}

// RolesListResponse List of roles in a tenant
type RolesListResponse struct {
	// List of roles (including system roles)
	Roles []Role `json:"roles"`
}

type _RolesListResponse RolesListResponse

// NewRolesListResponse instantiates a new RolesListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRolesListResponse(roles []Role) *RolesListResponse {
	this := RolesListResponse{}
	this.Roles = roles
	return &this
}

// NewRolesListResponseWithDefaults instantiates a new RolesListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRolesListResponseWithDefaults() *RolesListResponse {
	this := RolesListResponse{}
	return &this
}

// GetRoles returns the Roles field value
func (o *RolesListResponse) GetRoles() []Role {
	if o == nil {
		var ret []Role
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *RolesListResponse) GetRolesOk() ([]Role, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles, true
}

// SetRoles sets field value
func (o *RolesListResponse) SetRoles(v []Role) {
	o.Roles = v
}

func (o RolesListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RolesListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["roles"] = o.Roles
	return toSerialize, nil
}

func (o *RolesListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"roles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRolesListResponse := _RolesListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRolesListResponse)

	if err != nil {
		return err
	}

	*o = RolesListResponse(varRolesListResponse)

	return err
}

type NullableRolesListResponse struct {
	value *RolesListResponse
	isSet bool
}

func (v NullableRolesListResponse) Get() *RolesListResponse {
	return v.value
}

func (v *NullableRolesListResponse) Set(val *RolesListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRolesListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRolesListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRolesListResponse(val *RolesListResponse) *NullableRolesListResponse {
	return &NullableRolesListResponse{value: val, isSet: true}
}

func (v NullableRolesListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRolesListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


