/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements.

API version: 0.9.0
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
)

// checks if the V1ConfigHistoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ConfigHistoryResponse{}

// V1ConfigHistoryResponse struct for V1ConfigHistoryResponse
type V1ConfigHistoryResponse struct {
	// List of configuration entries
	Configs []V1ConfigHistoryItem `json:"configs,omitempty"`
	// Pagination information
	Pagination *V1ConfigHistoryPagination `json:"pagination,omitempty"`
}

// NewV1ConfigHistoryResponse instantiates a new V1ConfigHistoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ConfigHistoryResponse() *V1ConfigHistoryResponse {
	this := V1ConfigHistoryResponse{}
	return &this
}

// NewV1ConfigHistoryResponseWithDefaults instantiates a new V1ConfigHistoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ConfigHistoryResponseWithDefaults() *V1ConfigHistoryResponse {
	this := V1ConfigHistoryResponse{}
	return &this
}

// GetConfigs returns the Configs field value if set, zero value otherwise.
func (o *V1ConfigHistoryResponse) GetConfigs() []V1ConfigHistoryItem {
	if o == nil || IsNil(o.Configs) {
		var ret []V1ConfigHistoryItem
		return ret
	}
	return o.Configs
}

// GetConfigsOk returns a tuple with the Configs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ConfigHistoryResponse) GetConfigsOk() ([]V1ConfigHistoryItem, bool) {
	if o == nil || IsNil(o.Configs) {
		return nil, false
	}
	return o.Configs, true
}

// HasConfigs returns a boolean if a field has been set.
func (o *V1ConfigHistoryResponse) HasConfigs() bool {
	if o != nil && !IsNil(o.Configs) {
		return true
	}

	return false
}

// SetConfigs gets a reference to the given []V1ConfigHistoryItem and assigns it to the Configs field.
func (o *V1ConfigHistoryResponse) SetConfigs(v []V1ConfigHistoryItem) {
	o.Configs = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *V1ConfigHistoryResponse) GetPagination() V1ConfigHistoryPagination {
	if o == nil || IsNil(o.Pagination) {
		var ret V1ConfigHistoryPagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ConfigHistoryResponse) GetPaginationOk() (*V1ConfigHistoryPagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *V1ConfigHistoryResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given V1ConfigHistoryPagination and assigns it to the Pagination field.
func (o *V1ConfigHistoryResponse) SetPagination(v V1ConfigHistoryPagination) {
	o.Pagination = &v
}

func (o V1ConfigHistoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ConfigHistoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Configs) {
		toSerialize["configs"] = o.Configs
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableV1ConfigHistoryResponse struct {
	value *V1ConfigHistoryResponse
	isSet bool
}

func (v NullableV1ConfigHistoryResponse) Get() *V1ConfigHistoryResponse {
	return v.value
}

func (v *NullableV1ConfigHistoryResponse) Set(val *V1ConfigHistoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ConfigHistoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ConfigHistoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ConfigHistoryResponse(val *V1ConfigHistoryResponse) *NullableV1ConfigHistoryResponse {
	return &NullableV1ConfigHistoryResponse{value: val, isSet: true}
}

func (v NullableV1ConfigHistoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ConfigHistoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


