/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.14.0
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TenantSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantSettings{}

// TenantSettings Tenant configuration settings
type TenantSettings struct {
	// Tenant ID these settings belong to
	TenantId string `json:"tenant_id"`
	// Whether non-admin users can invite others
	AllowUserInvites bool `json:"allow_user_invites"`
	// Maximum number of users allowed
	MaxMembers int32 `json:"max_members"`
}

type _TenantSettings TenantSettings

// NewTenantSettings instantiates a new TenantSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantSettings(tenantId string, allowUserInvites bool, maxMembers int32) *TenantSettings {
	this := TenantSettings{}
	this.TenantId = tenantId
	this.AllowUserInvites = allowUserInvites
	this.MaxMembers = maxMembers
	return &this
}

// NewTenantSettingsWithDefaults instantiates a new TenantSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantSettingsWithDefaults() *TenantSettings {
	this := TenantSettings{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *TenantSettings) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *TenantSettings) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *TenantSettings) SetTenantId(v string) {
	o.TenantId = v
}

// GetAllowUserInvites returns the AllowUserInvites field value
func (o *TenantSettings) GetAllowUserInvites() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AllowUserInvites
}

// GetAllowUserInvitesOk returns a tuple with the AllowUserInvites field value
// and a boolean to check if the value has been set.
func (o *TenantSettings) GetAllowUserInvitesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllowUserInvites, true
}

// SetAllowUserInvites sets field value
func (o *TenantSettings) SetAllowUserInvites(v bool) {
	o.AllowUserInvites = v
}

// GetMaxMembers returns the MaxMembers field value
func (o *TenantSettings) GetMaxMembers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxMembers
}

// GetMaxMembersOk returns a tuple with the MaxMembers field value
// and a boolean to check if the value has been set.
func (o *TenantSettings) GetMaxMembersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxMembers, true
}

// SetMaxMembers sets field value
func (o *TenantSettings) SetMaxMembers(v int32) {
	o.MaxMembers = v
}

func (o TenantSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["allow_user_invites"] = o.AllowUserInvites
	toSerialize["max_members"] = o.MaxMembers
	return toSerialize, nil
}

func (o *TenantSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenant_id",
		"allow_user_invites",
		"max_members",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantSettings := _TenantSettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenantSettings)

	if err != nil {
		return err
	}

	*o = TenantSettings(varTenantSettings)

	return err
}

type NullableTenantSettings struct {
	value *TenantSettings
	isSet bool
}

func (v NullableTenantSettings) Get() *TenantSettings {
	return v.value
}

func (v *NullableTenantSettings) Set(val *TenantSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantSettings(val *TenantSettings) *NullableTenantSettings {
	return &NullableTenantSettings{value: val, isSet: true}
}

func (v NullableTenantSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


