/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.

API version: 0.0.0-dev
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MakePublicResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MakePublicResponse{}

// MakePublicResponse struct for MakePublicResponse
type MakePublicResponse struct {
	Message string `json:"message"`
	Path string `json:"path"`
}

type _MakePublicResponse MakePublicResponse

// NewMakePublicResponse instantiates a new MakePublicResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMakePublicResponse(message string, path string) *MakePublicResponse {
	this := MakePublicResponse{}
	this.Message = message
	this.Path = path
	return &this
}

// NewMakePublicResponseWithDefaults instantiates a new MakePublicResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMakePublicResponseWithDefaults() *MakePublicResponse {
	this := MakePublicResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *MakePublicResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *MakePublicResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *MakePublicResponse) SetMessage(v string) {
	o.Message = v
}

// GetPath returns the Path field value
func (o *MakePublicResponse) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *MakePublicResponse) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *MakePublicResponse) SetPath(v string) {
	o.Path = v
}

func (o MakePublicResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MakePublicResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["path"] = o.Path
	return toSerialize, nil
}

func (o *MakePublicResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMakePublicResponse := _MakePublicResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMakePublicResponse)

	if err != nil {
		return err
	}

	*o = MakePublicResponse(varMakePublicResponse)

	return err
}

type NullableMakePublicResponse struct {
	value *MakePublicResponse
	isSet bool
}

func (v NullableMakePublicResponse) Get() *MakePublicResponse {
	return v.value
}

func (v *NullableMakePublicResponse) Set(val *MakePublicResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMakePublicResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMakePublicResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMakePublicResponse(val *MakePublicResponse) *NullableMakePublicResponse {
	return &NullableMakePublicResponse{value: val, isSet: true}
}

func (v NullableMakePublicResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMakePublicResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


