/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.9.16
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CreateRelationshipRequest - Create relationship request. Must provide exactly one of subject_id or subject_set.
type CreateRelationshipRequest struct {
	CreateRelationshipRequestOneOf *CreateRelationshipRequestOneOf
	CreateRelationshipRequestOneOf1 *CreateRelationshipRequestOneOf1
}

// CreateRelationshipRequestOneOfAsCreateRelationshipRequest is a convenience function that returns CreateRelationshipRequestOneOf wrapped in CreateRelationshipRequest
func CreateRelationshipRequestOneOfAsCreateRelationshipRequest(v *CreateRelationshipRequestOneOf) CreateRelationshipRequest {
	return CreateRelationshipRequest{
		CreateRelationshipRequestOneOf: v,
	}
}

// CreateRelationshipRequestOneOf1AsCreateRelationshipRequest is a convenience function that returns CreateRelationshipRequestOneOf1 wrapped in CreateRelationshipRequest
func CreateRelationshipRequestOneOf1AsCreateRelationshipRequest(v *CreateRelationshipRequestOneOf1) CreateRelationshipRequest {
	return CreateRelationshipRequest{
		CreateRelationshipRequestOneOf1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateRelationshipRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateRelationshipRequestOneOf
	err = newStrictDecoder(data).Decode(&dst.CreateRelationshipRequestOneOf)
	if err == nil {
		jsonCreateRelationshipRequestOneOf, _ := json.Marshal(dst.CreateRelationshipRequestOneOf)
		if string(jsonCreateRelationshipRequestOneOf) == "{}" { // empty struct
			dst.CreateRelationshipRequestOneOf = nil
		} else {
			if err = validator.Validate(dst.CreateRelationshipRequestOneOf); err != nil {
				dst.CreateRelationshipRequestOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateRelationshipRequestOneOf = nil
	}

	// try to unmarshal data into CreateRelationshipRequestOneOf1
	err = newStrictDecoder(data).Decode(&dst.CreateRelationshipRequestOneOf1)
	if err == nil {
		jsonCreateRelationshipRequestOneOf1, _ := json.Marshal(dst.CreateRelationshipRequestOneOf1)
		if string(jsonCreateRelationshipRequestOneOf1) == "{}" { // empty struct
			dst.CreateRelationshipRequestOneOf1 = nil
		} else {
			if err = validator.Validate(dst.CreateRelationshipRequestOneOf1); err != nil {
				dst.CreateRelationshipRequestOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateRelationshipRequestOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateRelationshipRequestOneOf = nil
		dst.CreateRelationshipRequestOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CreateRelationshipRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CreateRelationshipRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateRelationshipRequest) MarshalJSON() ([]byte, error) {
	if src.CreateRelationshipRequestOneOf != nil {
		return json.Marshal(&src.CreateRelationshipRequestOneOf)
	}

	if src.CreateRelationshipRequestOneOf1 != nil {
		return json.Marshal(&src.CreateRelationshipRequestOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateRelationshipRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CreateRelationshipRequestOneOf != nil {
		return obj.CreateRelationshipRequestOneOf
	}

	if obj.CreateRelationshipRequestOneOf1 != nil {
		return obj.CreateRelationshipRequestOneOf1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CreateRelationshipRequest) GetActualInstanceValue() (interface{}) {
	if obj.CreateRelationshipRequestOneOf != nil {
		return *obj.CreateRelationshipRequestOneOf
	}

	if obj.CreateRelationshipRequestOneOf1 != nil {
		return *obj.CreateRelationshipRequestOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableCreateRelationshipRequest struct {
	value *CreateRelationshipRequest
	isSet bool
}

func (v NullableCreateRelationshipRequest) Get() *CreateRelationshipRequest {
	return v.value
}

func (v *NullableCreateRelationshipRequest) Set(val *CreateRelationshipRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRelationshipRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRelationshipRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRelationshipRequest(val *CreateRelationshipRequest) *NullableCreateRelationshipRequest {
	return &NullableCreateRelationshipRequest{value: val, isSet: true}
}

func (v NullableCreateRelationshipRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRelationshipRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


