/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements.

API version: 0.9.0
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
)

// checks if the ModelsNamespaceDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsNamespaceDefinition{}

// ModelsNamespaceDefinition struct for ModelsNamespaceDefinition
type ModelsNamespaceDefinition struct {
	Id *string `json:"id,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	Relations []string `json:"relations,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// NewModelsNamespaceDefinition instantiates a new ModelsNamespaceDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsNamespaceDefinition() *ModelsNamespaceDefinition {
	this := ModelsNamespaceDefinition{}
	return &this
}

// NewModelsNamespaceDefinitionWithDefaults instantiates a new ModelsNamespaceDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsNamespaceDefinitionWithDefaults() *ModelsNamespaceDefinition {
	this := ModelsNamespaceDefinition{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsNamespaceDefinition) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsNamespaceDefinition) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsNamespaceDefinition) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelsNamespaceDefinition) SetId(v string) {
	o.Id = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *ModelsNamespaceDefinition) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsNamespaceDefinition) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *ModelsNamespaceDefinition) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *ModelsNamespaceDefinition) SetNamespace(v string) {
	o.Namespace = &v
}

// GetRelations returns the Relations field value if set, zero value otherwise.
func (o *ModelsNamespaceDefinition) GetRelations() []string {
	if o == nil || IsNil(o.Relations) {
		var ret []string
		return ret
	}
	return o.Relations
}

// GetRelationsOk returns a tuple with the Relations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsNamespaceDefinition) GetRelationsOk() ([]string, bool) {
	if o == nil || IsNil(o.Relations) {
		return nil, false
	}
	return o.Relations, true
}

// HasRelations returns a boolean if a field has been set.
func (o *ModelsNamespaceDefinition) HasRelations() bool {
	if o != nil && !IsNil(o.Relations) {
		return true
	}

	return false
}

// SetRelations gets a reference to the given []string and assigns it to the Relations field.
func (o *ModelsNamespaceDefinition) SetRelations(v []string) {
	o.Relations = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ModelsNamespaceDefinition) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsNamespaceDefinition) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ModelsNamespaceDefinition) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ModelsNamespaceDefinition) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o ModelsNamespaceDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsNamespaceDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.Relations) {
		toSerialize["relations"] = o.Relations
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableModelsNamespaceDefinition struct {
	value *ModelsNamespaceDefinition
	isSet bool
}

func (v NullableModelsNamespaceDefinition) Get() *ModelsNamespaceDefinition {
	return v.value
}

func (v *NullableModelsNamespaceDefinition) Set(val *ModelsNamespaceDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsNamespaceDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsNamespaceDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsNamespaceDefinition(val *ModelsNamespaceDefinition) *NullableModelsNamespaceDefinition {
	return &NullableModelsNamespaceDefinition{value: val, isSet: true}
}

func (v NullableModelsNamespaceDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsNamespaceDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


