/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.

API version: 0.20.0
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ListStripeWebhooksRow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListStripeWebhooksRow{}

// ListStripeWebhooksRow struct for ListStripeWebhooksRow
type ListStripeWebhooksRow struct {
	ConfigId string `json:"config_id"`
	Connect bool `json:"connect"`
	CreatedAt time.Time `json:"created_at"`
	Events []string `json:"events"`
	Id string `json:"id"`
	Secret string `json:"secret"`
	StripeId string `json:"stripe_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Url string `json:"url"`
}

type _ListStripeWebhooksRow ListStripeWebhooksRow

// NewListStripeWebhooksRow instantiates a new ListStripeWebhooksRow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListStripeWebhooksRow(configId string, connect bool, createdAt time.Time, events []string, id string, secret string, stripeId string, updatedAt time.Time, url string) *ListStripeWebhooksRow {
	this := ListStripeWebhooksRow{}
	this.ConfigId = configId
	this.Connect = connect
	this.CreatedAt = createdAt
	this.Events = events
	this.Id = id
	this.Secret = secret
	this.StripeId = stripeId
	this.UpdatedAt = updatedAt
	this.Url = url
	return &this
}

// NewListStripeWebhooksRowWithDefaults instantiates a new ListStripeWebhooksRow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListStripeWebhooksRowWithDefaults() *ListStripeWebhooksRow {
	this := ListStripeWebhooksRow{}
	return &this
}

// GetConfigId returns the ConfigId field value
func (o *ListStripeWebhooksRow) GetConfigId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConfigId
}

// GetConfigIdOk returns a tuple with the ConfigId field value
// and a boolean to check if the value has been set.
func (o *ListStripeWebhooksRow) GetConfigIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfigId, true
}

// SetConfigId sets field value
func (o *ListStripeWebhooksRow) SetConfigId(v string) {
	o.ConfigId = v
}

// GetConnect returns the Connect field value
func (o *ListStripeWebhooksRow) GetConnect() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Connect
}

// GetConnectOk returns a tuple with the Connect field value
// and a boolean to check if the value has been set.
func (o *ListStripeWebhooksRow) GetConnectOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connect, true
}

// SetConnect sets field value
func (o *ListStripeWebhooksRow) SetConnect(v bool) {
	o.Connect = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ListStripeWebhooksRow) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ListStripeWebhooksRow) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ListStripeWebhooksRow) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetEvents returns the Events field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ListStripeWebhooksRow) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListStripeWebhooksRow) GetEventsOk() ([]string, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *ListStripeWebhooksRow) SetEvents(v []string) {
	o.Events = v
}

// GetId returns the Id field value
func (o *ListStripeWebhooksRow) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListStripeWebhooksRow) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListStripeWebhooksRow) SetId(v string) {
	o.Id = v
}

// GetSecret returns the Secret field value
func (o *ListStripeWebhooksRow) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *ListStripeWebhooksRow) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *ListStripeWebhooksRow) SetSecret(v string) {
	o.Secret = v
}

// GetStripeId returns the StripeId field value
func (o *ListStripeWebhooksRow) GetStripeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StripeId
}

// GetStripeIdOk returns a tuple with the StripeId field value
// and a boolean to check if the value has been set.
func (o *ListStripeWebhooksRow) GetStripeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StripeId, true
}

// SetStripeId sets field value
func (o *ListStripeWebhooksRow) SetStripeId(v string) {
	o.StripeId = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ListStripeWebhooksRow) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ListStripeWebhooksRow) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ListStripeWebhooksRow) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetUrl returns the Url field value
func (o *ListStripeWebhooksRow) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ListStripeWebhooksRow) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ListStripeWebhooksRow) SetUrl(v string) {
	o.Url = v
}

func (o ListStripeWebhooksRow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListStripeWebhooksRow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["config_id"] = o.ConfigId
	toSerialize["connect"] = o.Connect
	toSerialize["created_at"] = o.CreatedAt
	if o.Events != nil {
		toSerialize["events"] = o.Events
	}
	toSerialize["id"] = o.Id
	toSerialize["secret"] = o.Secret
	toSerialize["stripe_id"] = o.StripeId
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ListStripeWebhooksRow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"config_id",
		"connect",
		"created_at",
		"events",
		"id",
		"secret",
		"stripe_id",
		"updated_at",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListStripeWebhooksRow := _ListStripeWebhooksRow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListStripeWebhooksRow)

	if err != nil {
		return err
	}

	*o = ListStripeWebhooksRow(varListStripeWebhooksRow)

	return err
}

type NullableListStripeWebhooksRow struct {
	value *ListStripeWebhooksRow
	isSet bool
}

func (v NullableListStripeWebhooksRow) Get() *ListStripeWebhooksRow {
	return v.value
}

func (v *NullableListStripeWebhooksRow) Set(val *ListStripeWebhooksRow) {
	v.value = val
	v.isSet = true
}

func (v NullableListStripeWebhooksRow) IsSet() bool {
	return v.isSet
}

func (v *NullableListStripeWebhooksRow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListStripeWebhooksRow(val *ListStripeWebhooksRow) *NullableListStripeWebhooksRow {
	return &NullableListStripeWebhooksRow{value: val, isSet: true}
}

func (v NullableListStripeWebhooksRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListStripeWebhooksRow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


