/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements.

API version: 0.9.4
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
)

// checks if the ModelsDownloadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsDownloadResponse{}

// ModelsDownloadResponse struct for ModelsDownloadResponse
type ModelsDownloadResponse struct {
	// Presigned URL for downloading the file (valid for 15 minutes)
	DownloadUrl *string `json:"download_url,omitempty"`
}

// NewModelsDownloadResponse instantiates a new ModelsDownloadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsDownloadResponse() *ModelsDownloadResponse {
	this := ModelsDownloadResponse{}
	return &this
}

// NewModelsDownloadResponseWithDefaults instantiates a new ModelsDownloadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsDownloadResponseWithDefaults() *ModelsDownloadResponse {
	this := ModelsDownloadResponse{}
	return &this
}

// GetDownloadUrl returns the DownloadUrl field value if set, zero value otherwise.
func (o *ModelsDownloadResponse) GetDownloadUrl() string {
	if o == nil || IsNil(o.DownloadUrl) {
		var ret string
		return ret
	}
	return *o.DownloadUrl
}

// GetDownloadUrlOk returns a tuple with the DownloadUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsDownloadResponse) GetDownloadUrlOk() (*string, bool) {
	if o == nil || IsNil(o.DownloadUrl) {
		return nil, false
	}
	return o.DownloadUrl, true
}

// HasDownloadUrl returns a boolean if a field has been set.
func (o *ModelsDownloadResponse) HasDownloadUrl() bool {
	if o != nil && !IsNil(o.DownloadUrl) {
		return true
	}

	return false
}

// SetDownloadUrl gets a reference to the given string and assigns it to the DownloadUrl field.
func (o *ModelsDownloadResponse) SetDownloadUrl(v string) {
	o.DownloadUrl = &v
}

func (o ModelsDownloadResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsDownloadResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DownloadUrl) {
		toSerialize["download_url"] = o.DownloadUrl
	}
	return toSerialize, nil
}

type NullableModelsDownloadResponse struct {
	value *ModelsDownloadResponse
	isSet bool
}

func (v NullableModelsDownloadResponse) Get() *ModelsDownloadResponse {
	return v.value
}

func (v *NullableModelsDownloadResponse) Set(val *ModelsDownloadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsDownloadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsDownloadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsDownloadResponse(val *ModelsDownloadResponse) *NullableModelsDownloadResponse {
	return &NullableModelsDownloadResponse{value: val, isSet: true}
}

func (v NullableModelsDownloadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsDownloadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


