/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.9.16
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CheckPermissionRequest - Check permission request. Must provide exactly one of subject_id or subject_set.
type CheckPermissionRequest struct {
	CheckPermissionRequestOneOf *CheckPermissionRequestOneOf
	CheckPermissionRequestOneOf1 *CheckPermissionRequestOneOf1
}

// CheckPermissionRequestOneOfAsCheckPermissionRequest is a convenience function that returns CheckPermissionRequestOneOf wrapped in CheckPermissionRequest
func CheckPermissionRequestOneOfAsCheckPermissionRequest(v *CheckPermissionRequestOneOf) CheckPermissionRequest {
	return CheckPermissionRequest{
		CheckPermissionRequestOneOf: v,
	}
}

// CheckPermissionRequestOneOf1AsCheckPermissionRequest is a convenience function that returns CheckPermissionRequestOneOf1 wrapped in CheckPermissionRequest
func CheckPermissionRequestOneOf1AsCheckPermissionRequest(v *CheckPermissionRequestOneOf1) CheckPermissionRequest {
	return CheckPermissionRequest{
		CheckPermissionRequestOneOf1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CheckPermissionRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CheckPermissionRequestOneOf
	err = newStrictDecoder(data).Decode(&dst.CheckPermissionRequestOneOf)
	if err == nil {
		jsonCheckPermissionRequestOneOf, _ := json.Marshal(dst.CheckPermissionRequestOneOf)
		if string(jsonCheckPermissionRequestOneOf) == "{}" { // empty struct
			dst.CheckPermissionRequestOneOf = nil
		} else {
			if err = validator.Validate(dst.CheckPermissionRequestOneOf); err != nil {
				dst.CheckPermissionRequestOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.CheckPermissionRequestOneOf = nil
	}

	// try to unmarshal data into CheckPermissionRequestOneOf1
	err = newStrictDecoder(data).Decode(&dst.CheckPermissionRequestOneOf1)
	if err == nil {
		jsonCheckPermissionRequestOneOf1, _ := json.Marshal(dst.CheckPermissionRequestOneOf1)
		if string(jsonCheckPermissionRequestOneOf1) == "{}" { // empty struct
			dst.CheckPermissionRequestOneOf1 = nil
		} else {
			if err = validator.Validate(dst.CheckPermissionRequestOneOf1); err != nil {
				dst.CheckPermissionRequestOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CheckPermissionRequestOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CheckPermissionRequestOneOf = nil
		dst.CheckPermissionRequestOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CheckPermissionRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CheckPermissionRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CheckPermissionRequest) MarshalJSON() ([]byte, error) {
	if src.CheckPermissionRequestOneOf != nil {
		return json.Marshal(&src.CheckPermissionRequestOneOf)
	}

	if src.CheckPermissionRequestOneOf1 != nil {
		return json.Marshal(&src.CheckPermissionRequestOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CheckPermissionRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CheckPermissionRequestOneOf != nil {
		return obj.CheckPermissionRequestOneOf
	}

	if obj.CheckPermissionRequestOneOf1 != nil {
		return obj.CheckPermissionRequestOneOf1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CheckPermissionRequest) GetActualInstanceValue() (interface{}) {
	if obj.CheckPermissionRequestOneOf != nil {
		return *obj.CheckPermissionRequestOneOf
	}

	if obj.CheckPermissionRequestOneOf1 != nil {
		return *obj.CheckPermissionRequestOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableCheckPermissionRequest struct {
	value *CheckPermissionRequest
	isSet bool
}

func (v NullableCheckPermissionRequest) Get() *CheckPermissionRequest {
	return v.value
}

func (v *NullableCheckPermissionRequest) Set(val *CheckPermissionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckPermissionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckPermissionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckPermissionRequest(val *CheckPermissionRequest) *NullableCheckPermissionRequest {
	return &NullableCheckPermissionRequest{value: val, isSet: true}
}

func (v NullableCheckPermissionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckPermissionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


