/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.

API version: 0.20.0
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GetTenantByIDRow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTenantByIDRow{}

// GetTenantByIDRow struct for GetTenantByIDRow
type GetTenantByIDRow struct {
	CreatedAt time.Time `json:"created_at"`
	EnterpriseId NullableString `json:"enterprise_id"`
	EnterpriseTemplate NullableString `json:"enterprise_template"`
	Id string `json:"id"`
	Name string `json:"name"`
	StripeCustomerId NullableString `json:"stripe_customer_id"`
	Type string `json:"type"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _GetTenantByIDRow GetTenantByIDRow

// NewGetTenantByIDRow instantiates a new GetTenantByIDRow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTenantByIDRow(createdAt time.Time, enterpriseId NullableString, enterpriseTemplate NullableString, id string, name string, stripeCustomerId NullableString, type_ string, updatedAt time.Time) *GetTenantByIDRow {
	this := GetTenantByIDRow{}
	this.CreatedAt = createdAt
	this.EnterpriseId = enterpriseId
	this.EnterpriseTemplate = enterpriseTemplate
	this.Id = id
	this.Name = name
	this.StripeCustomerId = stripeCustomerId
	this.Type = type_
	this.UpdatedAt = updatedAt
	return &this
}

// NewGetTenantByIDRowWithDefaults instantiates a new GetTenantByIDRow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTenantByIDRowWithDefaults() *GetTenantByIDRow {
	this := GetTenantByIDRow{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetTenantByIDRow) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetTenantByIDRow) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetTenantByIDRow) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetEnterpriseId returns the EnterpriseId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetTenantByIDRow) GetEnterpriseId() string {
	if o == nil || o.EnterpriseId.Get() == nil {
		var ret string
		return ret
	}

	return *o.EnterpriseId.Get()
}

// GetEnterpriseIdOk returns a tuple with the EnterpriseId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetTenantByIDRow) GetEnterpriseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnterpriseId.Get(), o.EnterpriseId.IsSet()
}

// SetEnterpriseId sets field value
func (o *GetTenantByIDRow) SetEnterpriseId(v string) {
	o.EnterpriseId.Set(&v)
}

// GetEnterpriseTemplate returns the EnterpriseTemplate field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetTenantByIDRow) GetEnterpriseTemplate() string {
	if o == nil || o.EnterpriseTemplate.Get() == nil {
		var ret string
		return ret
	}

	return *o.EnterpriseTemplate.Get()
}

// GetEnterpriseTemplateOk returns a tuple with the EnterpriseTemplate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetTenantByIDRow) GetEnterpriseTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnterpriseTemplate.Get(), o.EnterpriseTemplate.IsSet()
}

// SetEnterpriseTemplate sets field value
func (o *GetTenantByIDRow) SetEnterpriseTemplate(v string) {
	o.EnterpriseTemplate.Set(&v)
}

// GetId returns the Id field value
func (o *GetTenantByIDRow) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetTenantByIDRow) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetTenantByIDRow) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GetTenantByIDRow) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetTenantByIDRow) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetTenantByIDRow) SetName(v string) {
	o.Name = v
}

// GetStripeCustomerId returns the StripeCustomerId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *GetTenantByIDRow) GetStripeCustomerId() string {
	if o == nil || o.StripeCustomerId.Get() == nil {
		var ret string
		return ret
	}

	return *o.StripeCustomerId.Get()
}

// GetStripeCustomerIdOk returns a tuple with the StripeCustomerId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetTenantByIDRow) GetStripeCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StripeCustomerId.Get(), o.StripeCustomerId.IsSet()
}

// SetStripeCustomerId sets field value
func (o *GetTenantByIDRow) SetStripeCustomerId(v string) {
	o.StripeCustomerId.Set(&v)
}

// GetType returns the Type field value
func (o *GetTenantByIDRow) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetTenantByIDRow) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetTenantByIDRow) SetType(v string) {
	o.Type = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetTenantByIDRow) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetTenantByIDRow) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetTenantByIDRow) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o GetTenantByIDRow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTenantByIDRow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["enterprise_id"] = o.EnterpriseId.Get()
	toSerialize["enterprise_template"] = o.EnterpriseTemplate.Get()
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["stripe_customer_id"] = o.StripeCustomerId.Get()
	toSerialize["type"] = o.Type
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *GetTenantByIDRow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"enterprise_id",
		"enterprise_template",
		"id",
		"name",
		"stripe_customer_id",
		"type",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetTenantByIDRow := _GetTenantByIDRow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetTenantByIDRow)

	if err != nil {
		return err
	}

	*o = GetTenantByIDRow(varGetTenantByIDRow)

	return err
}

type NullableGetTenantByIDRow struct {
	value *GetTenantByIDRow
	isSet bool
}

func (v NullableGetTenantByIDRow) Get() *GetTenantByIDRow {
	return v.value
}

func (v *NullableGetTenantByIDRow) Set(val *GetTenantByIDRow) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTenantByIDRow) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTenantByIDRow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTenantByIDRow(val *GetTenantByIDRow) *NullableGetTenantByIDRow {
	return &NullableGetTenantByIDRow{value: val, isSet: true}
}

func (v NullableGetTenantByIDRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTenantByIDRow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


