/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements.

API version: 0.9.13
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelsDeleteObjectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsDeleteObjectRequest{}

// ModelsDeleteObjectRequest struct for ModelsDeleteObjectRequest
type ModelsDeleteObjectRequest struct {
	// Path of the file to delete
	Path string `json:"path"`
}

type _ModelsDeleteObjectRequest ModelsDeleteObjectRequest

// NewModelsDeleteObjectRequest instantiates a new ModelsDeleteObjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsDeleteObjectRequest(path string) *ModelsDeleteObjectRequest {
	this := ModelsDeleteObjectRequest{}
	this.Path = path
	return &this
}

// NewModelsDeleteObjectRequestWithDefaults instantiates a new ModelsDeleteObjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsDeleteObjectRequestWithDefaults() *ModelsDeleteObjectRequest {
	this := ModelsDeleteObjectRequest{}
	return &this
}

// GetPath returns the Path field value
func (o *ModelsDeleteObjectRequest) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ModelsDeleteObjectRequest) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ModelsDeleteObjectRequest) SetPath(v string) {
	o.Path = v
}

func (o ModelsDeleteObjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsDeleteObjectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	return toSerialize, nil
}

func (o *ModelsDeleteObjectRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelsDeleteObjectRequest := _ModelsDeleteObjectRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelsDeleteObjectRequest)

	if err != nil {
		return err
	}

	*o = ModelsDeleteObjectRequest(varModelsDeleteObjectRequest)

	return err
}

type NullableModelsDeleteObjectRequest struct {
	value *ModelsDeleteObjectRequest
	isSet bool
}

func (v NullableModelsDeleteObjectRequest) Get() *ModelsDeleteObjectRequest {
	return v.value
}

func (v *NullableModelsDeleteObjectRequest) Set(val *ModelsDeleteObjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsDeleteObjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsDeleteObjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsDeleteObjectRequest(val *ModelsDeleteObjectRequest) *NullableModelsDeleteObjectRequest {
	return &NullableModelsDeleteObjectRequest{value: val, isSet: true}
}

func (v NullableModelsDeleteObjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsDeleteObjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


