/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.19.1
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
)

// checks if the ProductUI type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductUI{}

// ProductUI struct for ProductUI
type ProductUI struct {
	// Display name for UI
	DisplayName *string `json:"display_name,omitempty"`
	// Short tagline
	Tagline *string `json:"tagline,omitempty"`
	// List of product features
	Features []string `json:"features,omitempty"`
	// Badge text (e.g., \"Popular\", \"Best Value\")
	Badge *string `json:"badge,omitempty"`
	// Call-to-action button text
	CtaText *string `json:"cta_text,omitempty"`
	// Whether to highlight this product
	Highlighted *bool `json:"highlighted,omitempty"`
	// Display order for sorting
	SortOrder *int32 `json:"sort_order,omitempty"`
}

// NewProductUI instantiates a new ProductUI object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductUI() *ProductUI {
	this := ProductUI{}
	return &this
}

// NewProductUIWithDefaults instantiates a new ProductUI object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductUIWithDefaults() *ProductUI {
	this := ProductUI{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ProductUI) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUI) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ProductUI) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ProductUI) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetTagline returns the Tagline field value if set, zero value otherwise.
func (o *ProductUI) GetTagline() string {
	if o == nil || IsNil(o.Tagline) {
		var ret string
		return ret
	}
	return *o.Tagline
}

// GetTaglineOk returns a tuple with the Tagline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUI) GetTaglineOk() (*string, bool) {
	if o == nil || IsNil(o.Tagline) {
		return nil, false
	}
	return o.Tagline, true
}

// HasTagline returns a boolean if a field has been set.
func (o *ProductUI) HasTagline() bool {
	if o != nil && !IsNil(o.Tagline) {
		return true
	}

	return false
}

// SetTagline gets a reference to the given string and assigns it to the Tagline field.
func (o *ProductUI) SetTagline(v string) {
	o.Tagline = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *ProductUI) GetFeatures() []string {
	if o == nil || IsNil(o.Features) {
		var ret []string
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUI) GetFeaturesOk() ([]string, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *ProductUI) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []string and assigns it to the Features field.
func (o *ProductUI) SetFeatures(v []string) {
	o.Features = v
}

// GetBadge returns the Badge field value if set, zero value otherwise.
func (o *ProductUI) GetBadge() string {
	if o == nil || IsNil(o.Badge) {
		var ret string
		return ret
	}
	return *o.Badge
}

// GetBadgeOk returns a tuple with the Badge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUI) GetBadgeOk() (*string, bool) {
	if o == nil || IsNil(o.Badge) {
		return nil, false
	}
	return o.Badge, true
}

// HasBadge returns a boolean if a field has been set.
func (o *ProductUI) HasBadge() bool {
	if o != nil && !IsNil(o.Badge) {
		return true
	}

	return false
}

// SetBadge gets a reference to the given string and assigns it to the Badge field.
func (o *ProductUI) SetBadge(v string) {
	o.Badge = &v
}

// GetCtaText returns the CtaText field value if set, zero value otherwise.
func (o *ProductUI) GetCtaText() string {
	if o == nil || IsNil(o.CtaText) {
		var ret string
		return ret
	}
	return *o.CtaText
}

// GetCtaTextOk returns a tuple with the CtaText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUI) GetCtaTextOk() (*string, bool) {
	if o == nil || IsNil(o.CtaText) {
		return nil, false
	}
	return o.CtaText, true
}

// HasCtaText returns a boolean if a field has been set.
func (o *ProductUI) HasCtaText() bool {
	if o != nil && !IsNil(o.CtaText) {
		return true
	}

	return false
}

// SetCtaText gets a reference to the given string and assigns it to the CtaText field.
func (o *ProductUI) SetCtaText(v string) {
	o.CtaText = &v
}

// GetHighlighted returns the Highlighted field value if set, zero value otherwise.
func (o *ProductUI) GetHighlighted() bool {
	if o == nil || IsNil(o.Highlighted) {
		var ret bool
		return ret
	}
	return *o.Highlighted
}

// GetHighlightedOk returns a tuple with the Highlighted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUI) GetHighlightedOk() (*bool, bool) {
	if o == nil || IsNil(o.Highlighted) {
		return nil, false
	}
	return o.Highlighted, true
}

// HasHighlighted returns a boolean if a field has been set.
func (o *ProductUI) HasHighlighted() bool {
	if o != nil && !IsNil(o.Highlighted) {
		return true
	}

	return false
}

// SetHighlighted gets a reference to the given bool and assigns it to the Highlighted field.
func (o *ProductUI) SetHighlighted(v bool) {
	o.Highlighted = &v
}

// GetSortOrder returns the SortOrder field value if set, zero value otherwise.
func (o *ProductUI) GetSortOrder() int32 {
	if o == nil || IsNil(o.SortOrder) {
		var ret int32
		return ret
	}
	return *o.SortOrder
}

// GetSortOrderOk returns a tuple with the SortOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUI) GetSortOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.SortOrder) {
		return nil, false
	}
	return o.SortOrder, true
}

// HasSortOrder returns a boolean if a field has been set.
func (o *ProductUI) HasSortOrder() bool {
	if o != nil && !IsNil(o.SortOrder) {
		return true
	}

	return false
}

// SetSortOrder gets a reference to the given int32 and assigns it to the SortOrder field.
func (o *ProductUI) SetSortOrder(v int32) {
	o.SortOrder = &v
}

func (o ProductUI) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductUI) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.Tagline) {
		toSerialize["tagline"] = o.Tagline
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	if !IsNil(o.Badge) {
		toSerialize["badge"] = o.Badge
	}
	if !IsNil(o.CtaText) {
		toSerialize["cta_text"] = o.CtaText
	}
	if !IsNil(o.Highlighted) {
		toSerialize["highlighted"] = o.Highlighted
	}
	if !IsNil(o.SortOrder) {
		toSerialize["sort_order"] = o.SortOrder
	}
	return toSerialize, nil
}

type NullableProductUI struct {
	value *ProductUI
	isSet bool
}

func (v NullableProductUI) Get() *ProductUI {
	return v.value
}

func (v *NullableProductUI) Set(val *ProductUI) {
	v.value = val
	v.isSet = true
}

func (v NullableProductUI) IsSet() bool {
	return v.isSet
}

func (v *NullableProductUI) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductUI(val *ProductUI) *NullableProductUI {
	return &NullableProductUI{value: val, isSet: true}
}

func (v NullableProductUI) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductUI) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


