/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control via Ory Keto  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.9.16
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserTenantListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserTenantListItem{}

// UserTenantListItem Simplified tenant info for user's tenant list
type UserTenantListItem struct {
	Tenant Tenant `json:"tenant"`
	// Whether this is the user's currently active tenant
	IsActive bool `json:"is_active"`
}

type _UserTenantListItem UserTenantListItem

// NewUserTenantListItem instantiates a new UserTenantListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserTenantListItem(tenant Tenant, isActive bool) *UserTenantListItem {
	this := UserTenantListItem{}
	this.Tenant = tenant
	this.IsActive = isActive
	return &this
}

// NewUserTenantListItemWithDefaults instantiates a new UserTenantListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserTenantListItemWithDefaults() *UserTenantListItem {
	this := UserTenantListItem{}
	return &this
}

// GetTenant returns the Tenant field value
func (o *UserTenantListItem) GetTenant() Tenant {
	if o == nil {
		var ret Tenant
		return ret
	}

	return o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value
// and a boolean to check if the value has been set.
func (o *UserTenantListItem) GetTenantOk() (*Tenant, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tenant, true
}

// SetTenant sets field value
func (o *UserTenantListItem) SetTenant(v Tenant) {
	o.Tenant = v
}

// GetIsActive returns the IsActive field value
func (o *UserTenantListItem) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *UserTenantListItem) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *UserTenantListItem) SetIsActive(v bool) {
	o.IsActive = v
}

func (o UserTenantListItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserTenantListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenant"] = o.Tenant
	toSerialize["is_active"] = o.IsActive
	return toSerialize, nil
}

func (o *UserTenantListItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenant",
		"is_active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserTenantListItem := _UserTenantListItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserTenantListItem)

	if err != nil {
		return err
	}

	*o = UserTenantListItem(varUserTenantListItem)

	return err
}

type NullableUserTenantListItem struct {
	value *UserTenantListItem
	isSet bool
}

func (v NullableUserTenantListItem) Get() *UserTenantListItem {
	return v.value
}

func (v *NullableUserTenantListItem) Set(val *UserTenantListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableUserTenantListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableUserTenantListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserTenantListItem(val *UserTenantListItem) *NullableUserTenantListItem {
	return &NullableUserTenantListItem{value: val, isSet: true}
}

func (v NullableUserTenantListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserTenantListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


