/*
Omnibase REST API

Self-hostable Backend-as-a-Service providing database management, authentication, payments, storage, and email services.  ## Features - **Database**: PostgreSQL with RLS and migrations - **Authentication**: Ory Kratos integration with session management - **Payments**: Stripe integration with version-controlled billing configs - **Storage**: S3-compatible object storage with RLS - **Email**: Transactional email service - **Permissions**: Fine-grained access control  ## Authentication Most endpoints require authentication via session cookies or JWT tokens. Use the appropriate security scheme based on the endpoint requirements. 

API version: 0.19.0
Contact: support@omnibase.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omnibase

import (
	"encoding/json"
)

// checks if the MeterChanges type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeterChanges{}

// MeterChanges Summary of meter changes made during configuration update
type MeterChanges struct {
	// Meters that were created in Stripe
	Created []MeterChange `json:"created,omitempty"`
	// Meters that were updated
	Updated []MeterChange `json:"updated,omitempty"`
	// Meters that were archived
	Archived []MeterChange `json:"archived,omitempty"`
}

// NewMeterChanges instantiates a new MeterChanges object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeterChanges() *MeterChanges {
	this := MeterChanges{}
	return &this
}

// NewMeterChangesWithDefaults instantiates a new MeterChanges object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeterChangesWithDefaults() *MeterChanges {
	this := MeterChanges{}
	return &this
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *MeterChanges) GetCreated() []MeterChange {
	if o == nil || IsNil(o.Created) {
		var ret []MeterChange
		return ret
	}
	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterChanges) GetCreatedOk() ([]MeterChange, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *MeterChanges) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given []MeterChange and assigns it to the Created field.
func (o *MeterChanges) SetCreated(v []MeterChange) {
	o.Created = v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *MeterChanges) GetUpdated() []MeterChange {
	if o == nil || IsNil(o.Updated) {
		var ret []MeterChange
		return ret
	}
	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterChanges) GetUpdatedOk() ([]MeterChange, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *MeterChanges) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given []MeterChange and assigns it to the Updated field.
func (o *MeterChanges) SetUpdated(v []MeterChange) {
	o.Updated = v
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *MeterChanges) GetArchived() []MeterChange {
	if o == nil || IsNil(o.Archived) {
		var ret []MeterChange
		return ret
	}
	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeterChanges) GetArchivedOk() ([]MeterChange, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *MeterChanges) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given []MeterChange and assigns it to the Archived field.
func (o *MeterChanges) SetArchived(v []MeterChange) {
	o.Archived = v
}

func (o MeterChanges) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeterChanges) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	return toSerialize, nil
}

type NullableMeterChanges struct {
	value *MeterChanges
	isSet bool
}

func (v NullableMeterChanges) Get() *MeterChanges {
	return v.value
}

func (v *NullableMeterChanges) Set(val *MeterChanges) {
	v.value = val
	v.isSet = true
}

func (v NullableMeterChanges) IsSet() bool {
	return v.isSet
}

func (v *NullableMeterChanges) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeterChanges(val *MeterChanges) *NullableMeterChanges {
	return &NullableMeterChanges{value: val, isSet: true}
}

func (v NullableMeterChanges) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeterChanges) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


