id: microsoft
provider: microsoft
client_id: ${MICROSOFT_CLIENT_ID}
client_secret: ${MICROSOFT_CLIENT_SECRET}
microsoft_tenant: ${MICROSOFT_TENANT:-common}
scope:
  - profile
  - openid
  - email
mapper_url: file:///etc/config/kratos/oidc/microsoft/oidc.microsoft.jsonnet