import type { NamespaceDefinition, RelationMetadata } from "@omnibase/core-js";

// Legacy definitions without relationsMetadata (for backwards compatibility testing)
export const mockRoleCreatorDefinitions: NamespaceDefinition[] = [
  {
    id: "76e04dcc-2ab5-45aa-96da-8239f7ca01f2",
    namespace: "Project",
    relations: [
      "can_view_db_secret_key",
      "can_rotate_keys",
      "can_view_database_password",
      "can_view_database_connection_string",
      "can_view_postmark_server_token",
      "can_view_api_service_key",
      "can_update_project_env",
      "can_view_project_env",
      "can_view_storage_credentials",
      "parent_project",
      "tenant",
    ],
    subjectRelations: {
      ApiKey: [
        "can_view_db_secret_key",
        "can_rotate_keys",
        "can_view_database_password",
        "can_view_database_connection_string",
        "can_view_postmark_server_token",
        "can_view_api_service_key",
        "can_update_project_env",
        "can_view_project_env",
        "can_view_storage_credentials",
      ],
      Project: ["parent_project"],
      Tenant: ["tenant"],
      User: [
        "can_view_db_secret_key",
        "can_rotate_keys",
        "can_view_database_password",
        "can_view_database_connection_string",
        "can_view_postmark_server_token",
        "can_view_api_service_key",
        "can_update_project_env",
        "can_view_project_env",
        "can_view_storage_credentials",
      ],
    },
    updatedAt: new Date(),
  },
  {
    id: "165d9786-7666-4b1f-ab7a-96e25238480f",
    namespace: "Tenant",
    relations: [
      "can_rotate_keys",
      "can_view_db_secret_key",
      "can_view_database_password",
      "can_view_database_connection_string",
      "can_view_postmark_server_token",
      "can_view_api_service_key",
      "can_update_project_env",
      "can_view_project_env",
      "can_view_storage_credentials",
      "can_delete_tenant",
      "can_invite_user",
      "can_update_user_role",
      "can_update_user_role_to_owner",
      "can_remove_owner_role",
      "can_remove_user",
      "can_view_users",
      "can_update_roles",
      "can_create_api_keys",
      "can_view_api_keys",
      "can_revoke_api_keys",
    ],
    subjectRelations: {
      ApiKey: [
        "can_rotate_keys",
        "can_view_db_secret_key",
        "can_view_database_password",
        "can_view_database_connection_string",
        "can_view_postmark_server_token",
        "can_view_api_service_key",
        "can_update_project_env",
        "can_view_project_env",
        "can_view_storage_credentials",
      ],
      User: [
        "can_rotate_keys",
        "can_view_db_secret_key",
        "can_view_database_password",
        "can_view_database_connection_string",
        "can_view_postmark_server_token",
        "can_view_api_service_key",
        "can_update_project_env",
        "can_view_project_env",
        "can_view_storage_credentials",
        "can_delete_tenant",
        "can_invite_user",
        "can_update_user_role",
        "can_update_user_role_to_owner",
        "can_remove_owner_role",
        "can_remove_user",
        "can_view_users",
        "can_update_roles",
        "can_create_api_keys",
        "can_view_api_keys",
        "can_revoke_api_keys",
      ],
    },
    updatedAt: new Date(),
  },
];

// Enriched definitions with relationsMetadata (demonstrates hierarchical grouping)
export const mockEnrichedDefinitions: NamespaceDefinition[] = [
  {
    id: "76e04dcc-2ab5-45aa-96da-8239f7ca01f2",
    namespace: "Project",
    relations: [
      "can_view_db_secret_key",
      "can_rotate_keys",
      "can_view_database_password",
      "can_view_database_connection_string",
      "can_view_postmark_server_token",
      "can_view_api_service_key",
      "can_update_project_env",
      "can_view_project_env",
      "can_view_storage_credentials",
      "parent_project",
      "tenant",
    ],
    relationsMetadata: [
      {
        name: "can_view_db_secret_key",
        displayName: "View DB Secret Key",
        group: "Database",
        subGroup: "Secrets",
        roles: ["owner", "admin"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_rotate_keys",
        displayName: "Rotate Keys",
        group: "Database",
        subGroup: "Secrets",
        roles: ["owner", "admin"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_view_database_password",
        displayName: "View Database Password",
        group: "Database",
        subGroup: "Secrets",
        roles: ["owner", "admin"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_view_database_connection_string",
        displayName: "View Connection String",
        group: "Database",
        subGroup: "Connection",
        roles: ["owner", "admin", "developer"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_view_postmark_server_token",
        displayName: "View Postmark Token",
        group: "Email",
        roles: ["owner", "admin"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_view_api_service_key",
        displayName: "View API Service Key",
        group: "API",
        roles: ["owner", "admin"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_update_project_env",
        displayName: "Update Environment",
        group: "Configuration",
        roles: ["owner", "admin", "developer"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_view_project_env",
        displayName: "View Environment",
        group: "Configuration",
        roles: ["owner", "admin", "developer", "viewer"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_view_storage_credentials",
        displayName: "View Storage Credentials",
        group: "Storage",
        roles: ["owner", "admin"],
        subjects: ["User", "ApiKey"],
      },
    ] as RelationMetadata[],
    subjectRelations: {
      ApiKey: [
        "can_view_db_secret_key",
        "can_rotate_keys",
        "can_view_database_password",
        "can_view_database_connection_string",
        "can_view_postmark_server_token",
        "can_view_api_service_key",
        "can_update_project_env",
        "can_view_project_env",
        "can_view_storage_credentials",
      ],
      Project: ["parent_project"],
      Tenant: ["tenant"],
      User: [
        "can_view_db_secret_key",
        "can_rotate_keys",
        "can_view_database_password",
        "can_view_database_connection_string",
        "can_view_postmark_server_token",
        "can_view_api_service_key",
        "can_update_project_env",
        "can_view_project_env",
        "can_view_storage_credentials",
      ],
    },
    updatedAt: new Date(),
  },
  {
    id: "165d9786-7666-4b1f-ab7a-96e25238480f",
    namespace: "Tenant",
    relations: [
      "can_rotate_keys",
      "can_view_db_secret_key",
      "can_view_database_password",
      "can_view_database_connection_string",
      "can_view_postmark_server_token",
      "can_view_api_service_key",
      "can_update_project_env",
      "can_view_project_env",
      "can_view_storage_credentials",
      "can_delete_tenant",
      "can_invite_user",
      "can_update_user_role",
      "can_update_user_role_to_owner",
      "can_remove_owner_role",
      "can_remove_user",
      "can_view_users",
      "can_update_roles",
      "can_create_api_keys",
      "can_view_api_keys",
      "can_revoke_api_keys",
    ],
    relationsMetadata: [
      // User Management group
      {
        name: "can_invite_user",
        displayName: "Invite Users",
        group: "User Management",
        roles: ["owner", "admin"],
        subjects: ["User"],
      },
      {
        name: "can_view_users",
        displayName: "View Users",
        group: "User Management",
        roles: ["owner", "admin", "member"],
        subjects: ["User"],
      },
      {
        name: "can_remove_user",
        displayName: "Remove Users",
        group: "User Management",
        roles: ["owner", "admin"],
        subjects: ["User"],
      },
      {
        name: "can_update_user_role",
        displayName: "Update User Roles",
        group: "User Management",
        subGroup: "Role Assignment",
        roles: ["owner", "admin"],
        subjects: ["User"],
      },
      {
        name: "can_update_user_role_to_owner",
        displayName: "Promote to Owner",
        group: "User Management",
        subGroup: "Role Assignment",
        roles: ["owner"],
        subjects: ["User"],
      },
      {
        name: "can_remove_owner_role",
        displayName: "Demote Owner",
        group: "User Management",
        subGroup: "Role Assignment",
        roles: ["owner"],
        subjects: ["User"],
      },
      // Roles & Permissions group
      {
        name: "can_update_roles",
        displayName: "Manage Roles",
        group: "Roles & Permissions",
        roles: ["owner", "admin"],
        subjects: ["User"],
      },
      // API Keys group
      {
        name: "can_create_api_keys",
        displayName: "Create API Keys",
        group: "API Keys",
        roles: ["owner", "admin"],
        subjects: ["User"],
      },
      {
        name: "can_view_api_keys",
        displayName: "View API Keys",
        group: "API Keys",
        roles: ["owner", "admin", "developer"],
        subjects: ["User"],
      },
      {
        name: "can_revoke_api_keys",
        displayName: "Revoke API Keys",
        group: "API Keys",
        roles: ["owner", "admin"],
        subjects: ["User"],
      },
      // Tenant Administration group
      {
        name: "can_delete_tenant",
        displayName: "Delete Tenant",
        group: "Tenant Administration",
        roles: ["owner"],
        subjects: ["User"],
      },
      // Database group with subgroups
      {
        name: "can_view_db_secret_key",
        displayName: "View DB Secret Key",
        group: "Database",
        subGroup: "Secrets",
        roles: ["owner", "admin"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_rotate_keys",
        displayName: "Rotate Keys",
        group: "Database",
        subGroup: "Secrets",
        roles: ["owner", "admin"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_view_database_password",
        displayName: "View Database Password",
        group: "Database",
        subGroup: "Secrets",
        roles: ["owner", "admin"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_view_database_connection_string",
        displayName: "View Connection String",
        group: "Database",
        subGroup: "Connection",
        roles: ["owner", "admin", "developer"],
        subjects: ["User", "ApiKey"],
      },
      // Other services
      {
        name: "can_view_postmark_server_token",
        displayName: "View Postmark Token",
        group: "Email",
        roles: ["owner", "admin"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_view_api_service_key",
        displayName: "View API Service Key",
        group: "API",
        roles: ["owner", "admin"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_update_project_env",
        displayName: "Update Environment",
        group: "Configuration",
        roles: ["owner", "admin", "developer"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_view_project_env",
        displayName: "View Environment",
        group: "Configuration",
        roles: ["owner", "admin", "developer", "viewer"],
        subjects: ["User", "ApiKey"],
      },
      {
        name: "can_view_storage_credentials",
        displayName: "View Storage Credentials",
        group: "Storage",
        roles: ["owner", "admin"],
        subjects: ["User", "ApiKey"],
      },
    ] as RelationMetadata[],
    subjectRelations: {
      ApiKey: [
        "can_rotate_keys",
        "can_view_db_secret_key",
        "can_view_database_password",
        "can_view_database_connection_string",
        "can_view_postmark_server_token",
        "can_view_api_service_key",
        "can_update_project_env",
        "can_view_project_env",
        "can_view_storage_credentials",
      ],
      User: [
        "can_rotate_keys",
        "can_view_db_secret_key",
        "can_view_database_password",
        "can_view_database_connection_string",
        "can_view_postmark_server_token",
        "can_view_api_service_key",
        "can_update_project_env",
        "can_view_project_env",
        "can_view_storage_credentials",
        "can_delete_tenant",
        "can_invite_user",
        "can_update_user_role",
        "can_update_user_role_to_owner",
        "can_remove_owner_role",
        "can_remove_user",
        "can_view_users",
        "can_update_roles",
        "can_create_api_keys",
        "can_view_api_keys",
        "can_revoke_api_keys",
      ],
    },
    updatedAt: new Date(),
  },
];
