import type { NamespaceDefinition } from "@omnibase/core-js";

export const mockRoleCreatorDefinitions: NamespaceDefinition[] = [
  {
    id: "76e04dcc-2ab5-45aa-96da-8239f7ca01f2",
    namespace: "Project",
    relations: [
      "can_view_db_secret_key",
      "can_rotate_keys",
      "can_view_database_password",
      "can_view_database_connection_string",
      "can_view_postmark_server_token",
      "can_view_api_service_key",
      "can_update_project_env",
      "can_view_project_env",
      "can_view_storage_credentials",
      "parent_project",
      "tenant",
    ],
    subjectRelations: {
      ApiKey: [
        "can_view_db_secret_key",
        "can_rotate_keys",
        "can_view_database_password",
        "can_view_database_connection_string",
        "can_view_postmark_server_token",
        "can_view_api_service_key",
        "can_update_project_env",
        "can_view_project_env",
        "can_view_storage_credentials",
      ],
      Project: ["parent_project"],
      Tenant: ["tenant"],
      User: [
        "can_view_db_secret_key",
        "can_rotate_keys",
        "can_view_database_password",
        "can_view_database_connection_string",
        "can_view_postmark_server_token",
        "can_view_api_service_key",
        "can_update_project_env",
        "can_view_project_env",
        "can_view_storage_credentials",
      ],
    },
    updatedAt: new Date(),
  },
  {
    id: "165d9786-7666-4b1f-ab7a-96e25238480f",
    namespace: "Tenant",
    relations: [
      "can_rotate_keys",
      "can_view_db_secret_key",
      "can_view_database_password",
      "can_view_database_connection_string",
      "can_view_postmark_server_token",
      "can_view_api_service_key",
      "can_update_project_env",
      "can_view_project_env",
      "can_view_storage_credentials",
      "can_delete_tenant",
      "can_invite_user",
      "can_update_user_role",
      "can_update_user_role_to_owner",
      "can_remove_owner_role",
      "can_remove_user",
      "can_view_users",
      "can_update_roles",
      "can_create_api_keys",
      "can_view_api_keys",
      "can_revoke_api_keys",
    ],
    subjectRelations: {
      ApiKey: [
        "can_rotate_keys",
        "can_view_db_secret_key",
        "can_view_database_password",
        "can_view_database_connection_string",
        "can_view_postmark_server_token",
        "can_view_api_service_key",
        "can_update_project_env",
        "can_view_project_env",
        "can_view_storage_credentials",
      ],
      User: [
        "can_rotate_keys",
        "can_view_db_secret_key",
        "can_view_database_password",
        "can_view_database_connection_string",
        "can_view_postmark_server_token",
        "can_view_api_service_key",
        "can_update_project_env",
        "can_view_project_env",
        "can_view_storage_credentials",
        "can_delete_tenant",
        "can_invite_user",
        "can_update_user_role",
        "can_update_user_role_to_owner",
        "can_remove_owner_role",
        "can_remove_user",
        "can_view_users",
        "can_update_roles",
        "can_create_api_keys",
        "can_view_api_keys",
        "can_revoke_api_keys",
      ],
    },
    updatedAt: new Date(),
  },
];
