import type { Metadata } from "next";
import { protectedRoute } from "@omnibase/nextjs/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await protectedRoute("/auth/login");
  return <>{children}</>;
}
