FROM golang:1.25.7

RUN go install github.com/air-verse/air@v1.62.0

COPY sdk/core/go /sdk/core/go

WORKDIR /app

COPY apps/api/go.mod apps/api/go.sum ./

RUN go mod download

COPY apps/api ./

RUN rm -rf tmp

EXPOSE 8080

CMD ["air"]