# Development overrides - local builds with hot-reload
services:
  auth-migrate:
    image: ""
    build:
      context: ../../../docker/auth
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../../../docker/auth
        target: /etc/config/auth

  auth:
    image: ""
    build:
      context: ../../../docker/auth
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../../../docker/auth
        target: /etc/config/auth

  rest-api:
    image: ""
    build:
      context: ../../../apps/api
      dockerfile: Dockerfile.dev
    environment:
      - ENABLE_PPROF=true
    volumes:
      - ../../../apps/api:/app

  permissions-migrate:
    image: ""
    build:
      context: ../../../docker/permissions
      dockerfile: Dockerfile

  permissions:
    image: ""
    build:
      context: ../../../docker/permissions
      dockerfile: Dockerfile
