# Development overrides - local builds with hot-reload
services:
  auth-migrate:
    image: ""
    build:
      context: ../../../docker/auth
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../../../docker/auth
        target: /etc/config/auth
        bind:
          selinux: z

  auth:
    image: ""
    build:
      context: ../../../docker/auth
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../../../docker/auth
        target: /etc/config/auth
        bind:
          selinux: z

  rest-api:
    image: ""
    build:
      context: ../../..
      dockerfile: apps/api/Dockerfile.dev
    environment:
      - ENABLE_PPROF=true
    volumes:
      - ../../../apps/api:/app:z
      - ../../../sdk/core/go:/sdk/core/go:z

  permissions-migrate:
    image: ""
    build:
      context: ../../../docker/permissions
      dockerfile: Dockerfile

  permissions:
    image: ""
    build:
      context: ../../../docker/permissions
      dockerfile: Dockerfile
