# Test overrides - local builds without hot-reload (runs Go binary directly)
services:
  auth-migrate:
    image: ""
    build:
      context: ../../../docker/auth
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../../../docker/auth
        target: /etc/config/auth
        bind:
          selinux: z

  auth:
    image: ""
    build:
      context: ../../../docker/auth
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../../../docker/auth
        target: /etc/config/auth
        bind:
          selinux: z

  rest-api:
    image: ""
    build:
      context: ../../../apps/api
      dockerfile: Dockerfile.test
    environment:
      - ENABLE_PPROF=true
    volumes:
      - ../../../apps/api:/app:z

  permissions-migrate:
    image: ""
    build:
      context: ../../../docker/permissions
      dockerfile: Dockerfile

  permissions:
    image: ""
    build:
      context: ../../../docker/permissions
      dockerfile: Dockerfile
